### ISSUE TITLE
[Bug]: Forbid problematic characters in model labels.

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1002]
### Description
If users name their model components in the Model Fitting plugin something like "model-1" (with a dash in it), the dash will be interpreted as a subtraction operator and cause the fitting to crash. We need to do some checking/sanitizing of the model label strings to ensure this doesn't happen.

[🐱](https://jira.stsci.edu/browse/JDAT-2019)

**Comment by pllim** [comment]
Regex check might work... 💭
