### ISSUE TITLE
Plugin tray partly hidden when some fields too wide in Jupyter Lab

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1005]
Workflow to reproduce:

1. Fire up Cubeviz example notebook in Lab.
2. Give a really long data label, for example, `viz.load_data(fn, data_label='28a88k1qfipo4yxc4p4d40v4axtlal8y.fits')`.
3. Click on "hamburger" icon to bring up plugin tray, then select Collapse.
4. See the tray partially hidden (screenshot).  The "hamburger" is now hidden. You have to drag the left border to widen the plugin tray for it to reappear.

![Screenshot 2021-12-14 163613](https://user-images.githubusercontent.com/2090236/146087775-35254c2c-2e7e-406d-950e-afdf111cf628.jpg)

cc @kecnry 

Possibly related to #984 ?

[🐱](https://jira.stsci.edu/browse/JDAT-2032)

**Comment by kecnry** [comment]
Confirmed that I can reproduce this even with padding updates in #1008.  I suspect the CSS rules for the split panes in Lab non-defaults and causing conflicts with ours.  See recording below:

https://user-images.githubusercontent.com/877591/146571383-b4df4dbc-9e6a-4c69-a318-4accaabc6282.mov

**Comment by rosteen** [comment]
This seems to have been fixed, closing.
