### ISSUE TITLE
Change to showing plugins in sidebar instead of modal dialog

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#102]
The current plugins pop up as modal dialogs.  Following some user testing and input from @jenneh the thinking is that a sidebar with fold-out panels for plugins is the preferred way to go.  So this issue is to implement that.

Some specific constraints:

* The plugins should be "acoordian-able" so that the user only sees those they have opened up
* The plugin pane should be hide-able
* bonus/could be in later PR: the plugin pane should be tear-off-able, or at least movable
* bonus/could be in later PR: the plugins in the pane should be re-orderable

One other bit of user feedback: having *lots* of panes that organize the plugins via some complicated scheme is an anti-feature, so we should avoid that.

**Comment by Jenneh** [comment]
Here is a link to the UX spec: http://www.stsci.edu/~jkotler/Spectra/#g=1&p=ux_wireframes

To see the mock-ups of this feature, scroll down to the very bottom of the page to the section 'PLUGINS - POPUP VS SIDE PANEL'.  The Side Panel mock-ups are in the 'SIDE PANEL' subsection.
