### ISSUE TITLE
BUG: Imviz coordinate info inaccurate when plugin width is manually readjusted

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1027]
Perhaps this is caused by the same thing that is causing the bug @kecnry is seeing over at #1013. Workflow to reproduce this:

1. Display data in Imviz example notebook.
2. Zoom in to the lower left corner of the image until you see individual pixels. Mouse over `X=0 Y=0`. Coordinate info shows the same.
3. Open plugin tray. Mouse over the same pixel. See it is still `X=0 Y=0`.
4. Manually drag to widen the plugin tray. Wait for display to adjust. Mouse over the same pixel. Now it shows `X=-1 Y=0`.
5. Close the plugin tray, Mouse over the same pixel. Now it shows `X=0 Y=0` again.

![Screenshot 2022-01-05 111540](https://user-images.githubusercontent.com/2090236/148251939-0e076209-c2be-4ba5-8c4f-284eff8f4210.jpg)

https://github.com/spacetelescope/jdaviz/blob/2c2d2fb285e58e05935f807e20053f92a5a65638/jdaviz/configs/imviz/plugins/viewers.py#L75-L77

[🐱](https://jira.stsci.edu/browse/JDAT-2064)

**Comment by pllim** [comment]
Is this a matter of listening to some sort of "width changed" event from somewhere here

https://github.com/spacetelescope/jdaviz/blob/2c2d2fb285e58e05935f807e20053f92a5a65638/jdaviz/app.vue#L48

and then emit a [domain_changed](https://github.com/bqplot/bqplot/search?q=domain_changed) event for `bqplot`?

Maybe @mariobuikhuizen has ideas?

**Comment by pllim** [comment]
This bug no longer shows up. 🤷

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JDAT-2064](https://jira.stsci.edu/browse/JDAT-2064)._

**Comment by stscijgbot-jwql** [comment]
_Comment by [Pey-Lian Lim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lim) on [JIRA](https://jira.stsci.edu/browse/JDAT-2064?focusedCommentId=619291#comment-619291):_

I cannot reproduce this anymore. Seems to work fine now, so archiving.
