### ISSUE TITLE
Decide whether mosviz spectrum view should be a full-fledged specviz  or a subset of the specviz viewer

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#103]
What it says on the tin - partly driven by some of the discussion around #100.  Some complexity, though:

The solution from the qt mosviz was a "open in specviz" button, which launched basically a separate app window.  That idiom doesn't work so well in `jdaviz` because in jupyter there's not really a natural way to launch a "new window", although we presumably could do something in the notebook view that presents it as a new cell.  So that leads me in the direction of thinking we should aim for having the spectrum viewer have basically all the capabilities of specviz (including relevant plugins), but have them only operate on the currently active spectrum. 

With that proposal, the biggest hurdle I see is that Mosviz (at least the #100 concept) can change which spectrum is being shown at any time.  We need to make sure any relevant specviz functionality isn't broken by that.  My thinking is just to basically reset the viewer when a new spectrum is shown.  Later we might consider remembering state, but that at least works around the complexity for now.

cc @hcferguson @nmearl @robelgeda

**Comment by hcferguson** [comment]
I think there may be common considerations for cubviz as well? Not sure if it's allowed, but I can imagine you might have a spatially smoothed view of a cube in one image viewer and a non-smoothed one in the other. Is it always taking the one-D profile from the first viewer, or could it taking it from the second (in which case similar confusion could arise).

**Comment by hcferguson** [comment]
If it's practical, one approach might be to throw a mouseover event and catch that to make the spectrum you are highlighting with the cursor bold, and at the same time making the viewer outline and selections that were the source of that spectrum bold elsewhere in the app.

**Comment by hcferguson** [comment]
I agree with trying to make the specviz windows the full-featured specviz. But the ability to overlay spectra is part of that feature set, so I'm not sure reseting the viewer when a new spectrum is shown is going to be a good solution. Not a crazy approach for now, but I think we will need to think this through sooner rather than later anyway.

**Comment by eteq** [comment]
Note that #133 discusses something about this - with the evolving idea of the helper classes, I think there's a way to use composition and naming conventions to mostly deal with this.

**Comment by rosteen** [comment]
@eteq This ship has sailed and we can close this, right?

**Comment by pllim** [comment]
So did it turn out full-fledged or half-fledged? Don't keep us hanging like George R. R. Martin!

**Comment by rosteen** [comment]
Full, I believe.

**Comment by pllim** [comment]
I am just gonna close it then.
