### ISSUE TITLE
Revisit/decide whether the viz apps should be subclasses 

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#104]
This issue is to record discussion about whether or not the viz apps should be sub-classes with custom methods/etc of the glue application object, vs purely configuration.

The idea is that *regardless* of the answer to this question, the UI layout and the like would still all be configuration.  The stuff in the sub-classes I imagine to be primarily notebook-friendly API to allow users to interact with the apps in a way that's natural in Python without having to push a lot of complicated app-specific machinery onto the generic `Application` object.

**Comment by eteq** [comment]
To lay this out a bit more:

#100 (particularly 932d08201803f232a30a905bd70a5d201967e8de) provides concrete examples of the sort of sub-class based workflow that a user might want to do with mosviz in a notebook.  https://github.com/spacetelescope/jdaviz/blob/master/notebooks/concepts/Example%20cubeviz%20spectral%20and%20spatial%20interactions.ipynb also provides some examples, although an alternative access perspective is at least partially  provided by the idioms shown in #83.

The primary advantages I see for a sub-class based approach are these:
* More easily "findable" by the user: no imports are required, the user just creates e.g. a `MosVizApp` and then does `mosapp.<tab>`, and looks at the method names. In practice this is a very non-negligble discovery pathway for notebook or other interactive-python science users.
* State that is particular to a science workflow can be counted on in a specific app's workflow.  For example, in the mosviz concept notebook, the mosviz app can trust that there is always going to be a table viewer, and hence can store state about whether or not the user has loaded a table in that viewer rather than having to check if a viewer exists, etc.
* Easier to implement separation-of-concerns: these methods would all live in the viztool specific class, so there's no danger of mixing mosviz-workflow-specific functionality with cubeviz-specific workflows

Disadvantages that strike me:
* The "separation-of-concerns" above is a double-edged sword: some `specviz` functionality we may *want* in the other viz apps, and enforcing a class hierarchy makes that hard to work out. Amelioration: try to put "shared" functionality at the viewer level (i.e. in glupyter itself where possible).  This implies an active choice to say that the purpose of the specific viztool apps is to enable specific, typically multi-viewer workflows.
* (channeling @nmearl) Subclasses make it much harder to gently transition to and from different glue configurations.  You can't just "update the configuration" if there's a specific subclass carrying state and operations around.  There are work-arounds like saying all the application objects take another application object as an argument so that things like:
```
svapp = SpecVizApp(...)
... do stuff ...
app = GlueApplication(app=svapp)
... do stuff ...
CubeVizApp(app=app)
```
is possible, but that's potentially full of implementation landmines.

There is a possible "kick the can down the line" solution: anything proposed as a method can for now be implemented as a *function*, which takes the Application object as the first argument.  Then if we decide to go the subclass route *later*, it's a find-and replace of that argument name to `self` and indent-by-one. In that idiom we would use package-namespaces instead of classes to communicate to the user what their workflow specific functionality is in.  E.g., `mosviz` specific functionality would be `jdaviz.mosivz.load_table_data` or whatever, so they can still do `jdaviz.mosviz.<tab>`

**Comment by nmearl** [comment]
The discussion centers on the API case for the viz apps. Essentially, Erik’s suggesting we switch to light subclasses for each of the viz apps in order to do things like

```>>> app = CubeVizApplication()
>>> app.get_spectrum()
[Spectrum1D object representing the _original_ loaded data in the spectrum viewer]```
This is in contrast to generic accessors like `app.get_viewer('spectrum').data`, which would return a list of the currently data plot — or, optionally `app.get_data('spectrum')` to return what Erik’s suggesting (the specific loaded data spectrum for the ‘spectrum’ viewer). Erik’s argument is that this is too “dictionary” like instead of API-like in which the user has to be aware of the _name_ of the viewer in order to get access to it.

My apprehensions with the subclass approach are

1. We’re no longer really generating specific application setups via configuration, we’re hard-coding usage instances by using light subclasses. What I mean is that specific applications are no longer just composed from a configuration file, it would now be what’s defined in the subclass.

2. We’d no longer be able to switch e.g. from CubeViz to regular Glue, or from MOSViz to SpecViz without setting up a new application instance. Likewise, the user can’t do what Jen had suggested in that when they start up the JDAViz app, they could choose the type of analysis they’d like to do (by showing the list of available setups).

3. The API seems very specific: `app.get_spectrum()` would return only the original loaded spectrum object, and not e.g. a smooth spectrum that’s been added to the spectrum viewer. For that case, users would still have to get access to the data collection and choose that particular data.

Erik’s issues with the pure configuration approach seems to be:

1. We can’t control the API enough, and thus the generated API docs would be lacking in specific use cases.

2. The auto-complete would be too general. A user ought to be able to tab on an `app` instance to see how to access obvious API features.

@etollerud please add any big topics I missed!

**Comment by eteq** [comment]
Below are some short-hand notes I just took on a call about this.  I will translate these notes into a more readable write-up in a bit, but just wanted to make sure it doesn't get lost 

"helper class"
* generator class
* generator function
* "inverted" class heirarchy

* do we want super glupyter to be a class?

* need to know where methods go, esp. without a super glupyter class
* does it require use-case-specific state? If so, definitely belongs in method

* state in wrapper classes?  Generally against it, although might be easier on users some time?
* related question: how do we ensure people follow this idiom?
* General agreement that as little state as possible should be in wrapper classes - it should all live in the application and/or the data objects to whatever extent is practical.

* mosviz: the table is a good example/test case of whether we can stuff all necessary state into the glue-compliant things. 
* Perhaps as much state as possible should be in the table?  
* Another possibility is to put as much as possible into glue *data* class subclasses.  then it would work in the superglupyter context

* Agreement on the "helper class" idiom. Emphasis that we have to try it out a bit before anyone's willing to commit (and thereby close this issue).  In the meantime we will try to ensure anyone doing reviews is aware the idiom is a "testing" idiom

**Comment by eteq** [comment]
Alright, here's my summary of a discussion including @nmearl @astrofrog @rosteen @dtn5ah @robelgeda on this topic.



I also decided I should add a bit to the mosviz concept to illustrate this idiom in action.  I think it works out pretty well. I'll add that to #100 before merging

**Comment by eteq** [comment]
Alright, here's my summary of a discussion including @nmearl @astrofrog @rosteen @dtn5ah @robelgeda on this topic.

We considered a few alternatives, including those mentioned here as well as a generator class or a generator function that adds methods/functions/etc, but generally those seemed a bit overly complex (i.e., non-standard approaches hard for others to understand).

The consensus was that the best compromise on this is to do sort of an "inverted" version of the subclass paradigm, and use helper classes that provide the methods I'm discussing here, but which contain an `app` attribute which is the glue `Application` object.  That's actually better for the interface items I was discussing above because it provides a cleaner separation about what is "regular" glupyter functionality (the `app` object) vs the viz-app specific functionality (which are methods on the helper).

Some consequences of this are:
* We need to be clear that wherever possible, state should live in glue/glupyter.  We should only have state in the "helper" class if *absolutely* necessary, meaning specific to that viz tool and for some reason not representable via Glue-level state.  We discussed baking this in by using `__slots__` or some other mechanism to prevent setting of attributes, but decided that was too heavy-handed and it's better just to say (here and in the documentation) the philosophy and catch such issues in PR review.
* We discussed whether or not there should be a helper class for "generic" glupyter ("super glue-pyter"?), which would then put "generic" glupyter on the same footing as the specific-use viz tools.  But the current thinking is that's not necessary because anything in "generic" glupyter should live on the `Application` class, so the way to transition to that is to just grab `<viztoolhelper>.app`
* Since it's already been used as an example, mosviz is a good place to try some of these idioms. I'll add some examples of this to #100 before merging, and then we can use mosviz to make a prototype of this idea and "kick the tires".  So whoever ends up implementing this prototype can use the bottom of that notebook as an initial guide to building the framework.
* We agreed this approach should be thought of as a prototype for now.  Once we've had some experience with users as well (probably with mosviz first) we'll decide for sure.  So this issue will remain open until that time.

One question remains that occurred to me after our meeting: is there a natural way to store the app configuration in the helper's module?  That seems like a good way to keep the "code" and "configuration" in the same place for developer convenience.

**Comment by nmearl** [comment]
>  is there a natural way to store the app configuration in the helper's module

The configuration is stored as a dictionary in the app-level settings state (which lives on the top-level `app` object). But it's a good point that this dictionary is distinct for each application implementation and perhaps _distinct_ settings should live in the down stream app wrapper.

**Comment by eteq** [comment]
@nmearl's

> The configuration is stored as a dictionary in the app-level settings state

Ah, sorry, I didn't necessarily mean the "live" version that stores the configuration, but I more meant the canonical copy of it *in the code*.  That is, I think it might be difficult/confusing if the "meant to be used with" configuration is in some completely different corner of `jdaviz` than the helper itself.  So I'm imagining the configuration could be stored either in the same place as the helper, or something like:
```
jdaviz/mosviz/__init__.py
jdaviz/mosviz/mosviz_helper.py
jdaviz/mosviz/mosviz_conf.json (or maybe .py with the configuration a global variable?)
```
that way their all right next to each other so it'll be easier to understand, say "I renamed one of the viewers, and also updated the corresponding helper methods that use it"

**Comment by nmearl** [comment]
Ideally, everything this is "mosviz" -- the configuration, the wrapper class, and all associated plugins would be a package itself installed into some entry point group (e.g. `jdaviz_plugins`) that would get picked up by the top-level glupyter application. So, yeah, it definitely makes sense to have them all together.

**Comment by pllim** [comment]
Ship has sailed.
