### ISSUE TITLE
[BUG] Specviz: Unit Conversion breaks Line Analysis using Jupyter-lab

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#1067]
**Describe the bug**
Using the Line Analysis plugin on unit converted data causes the plugin tray and right side of the viewer to move off screen.

**To Reproduce**
1. Open jdaviz in jupyer-lab
2. Run Specviz and load data
2. Use Unit Conversion on the Spectral Axis and Apply
3. Go to the Line Analysis plugin
4. Select unit converted data from the drop down
5. See error

**Expected behavior**
Line Analysis on the unit converted data.

**Screenshots**
<img width="1492" alt="Screen Shot 2022-02-07 at 12 23 54 PM" src="https://user-images.githubusercontent.com/7179333/152839713-e773b552-5247-47c4-89d0-f21c2cad4695.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - jupyterlab version 3.2.9

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
Numpy 1.22.2
astropy 5.0.1
specutils 1.6.0
spectral-cube 0.6.0
pyyaml 6.0
click 8.0.3
asteval 0.9.26
idna 2.10
traitlets 5.1.1
bqplot 0.12.32
bqplot-image-gl 1.4.5
glue-core 1.2.4
glue-jupyter 0.10.1
glue-astronomy 0.3.2
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.1
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.3.1
vispy 0.9.4
Jdaviz 2.2.1.dev113+gf9557d6

**Additional context (e.g. data files)**

**Comment by kecnry** [comment]
Good catch!  This probably applies to many other plugins as well... basically any dropdown that references the data-set names will likely need to have a max-width or overflow set on the input element (I'm just guessing, will need some actual diagnosis to confirm).  For that matter, it might be easiest to just apply across _all_ input elements in the global app css.
