### ISSUE TITLE
application embed into front-end

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#107]
I've got a working prototype of the jdaviz application embedded into a separate front-end using `voila-embed`.  My embed notebook is the following:

Import the application
```
import ipyvuetify as v
from jdaviz.app import Application
app = Application(configuration='specviz')
app
```
Function to load data on change event
```
def update_data_handler(widget, event, data):
    # get new data from selected target
    selected_src = int(data)
    data = prep_data(selected_src)
    app.load_data(data)
```
Embed the app in a ipyvuetify row/col layout to attach specific mount_id and event handler. 
```
col = v.Col(xs12=True, lg6=True, xl4=True, children=[app])
row = v.Row(_metadata={'mount_id': 'specviz'}, dense=True, row=True, wrap=True, align_center=True, children=[col])
row.on_event('change', update_data_handler)
```
The primary reason I wrap the application in an `ipyvuetify Row/Col` is to attach a `mount_id` so I can embed it in my front-end and add a custom event handler for updating the data.    Is there a better way of doing this?   I noticed the application has a `mount_id` in `app._metadata`.  Is this currently being used, or something I can modify?  I also wasn't sure if custom event handlers can be attached to the application directly.

**Comment by rosteen** [comment]
I hope we answered your question in a separate channel from this...given how old this is and the fact that we have a working Jdaviz in MAST solution, I'm going to close it.
