### ISSUE TITLE
Bug: Importing Jdaviz before running the JWST pipeline results in Logging that should not be turned on

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdaviz#1084]
If you import jdaviz, you end up turning on logging when running the jwst pipeline and, subsequently, when opening jdaviz. You get a series of stpipe errors that, in some cases, completely hide jdaviz from appearing.

[🐱](https://jira.stsci.edu/browse/JP-2280) [🐱](https://jira.stsci.edu/browse/JDAT-1506)

**Comment by pllim** [comment]
Turns out it was the glue logger, see glue-viz/glue#2278.
