### ISSUE TITLE
Multiple data objects don't render simultenaously

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/jdaviz#113]
Currently, the glue viewers don't seem keen on rendering multiple data items simultaneously. E.g. plotting a spectrum and then adding a smoothed spectrum from a manipulation task does not show both, and the plot will need to be cleared and afterward only a single spectrum can be added to the viewer.

I was under the impression that this was consequence of the wcs linking in glue, but maybe @astrofrog can weigh in on that. In discussions over PR #83, @eteq seems to indicate that it's just a scaling issue (i.e. that plots are not auto-scaling to the data that's plotted within them), but I can't seem to replicate this behavior.

**Comment by hcferguson** [comment]
@eteq @nmearl I would suggest being careful about autoscaling when adding a new dataset to the plot (and maybe defer working on that). The usability issues aren't obvious here without user testing....autoscaling can confuse people just as much as data sets that aren't immediately evident.

**Comment by eteq** [comment]
This was fixed at some point.  I'm not sure when, but this is now working!
