### ISSUE TITLE
Imviz: performance issues with large images due to compass drawing

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#1150]
The ImVIz viewer is currently **extremely** slow for large (e.g. 1Gb) images while the image viewer in glue-jupyter is not. I have investigated this and found the cause to the the drawing of the compass. There are several issues here.

First, the following lines will cause the entirety of the data to be loaded:

https://github.com/spacetelescope/jdaviz/blob/45dc2e1df389e2fe974619e8ac2eba9bb5316dad/jdaviz/configs/imviz/plugins/viewers.py#L204-L205

which is not desirable. It's not clear to me why the data values are needed at all? If someone can clarify this I can try and give a reasonable alternative - but we should definitely never load all the data. Alternatives would include loading a random subset of pixels, or loading a cutout if it is to do where the location where the compass will be shown.

Next, the ``draw_compass_mpl`` function is currently setting up a Matplotlib figure and axes and plotting the entire image (not downsampled) in the Matplotlib figure:

https://github.com/spacetelescope/jdaviz/blob/45dc2e1df389e2fe974619e8ac2eba9bb5316dad/jdaviz/configs/imviz/wcs_utils.py#L195-L199

This also should not be happening.

These two issues account for most of the extreme lag seen currently. Once these are resolved, I think we can speed things up a little more by avoiding duplicate calls to the glue backend, but the two issues above account for >95% of the slowness for me.

[🐱](https://jira.stsci.edu/browse/JDAT-2162)

**Comment by pllim** [comment]
> why the data values are needed at all?

To make the mini image visible on compass. Otherwise, you don't see anything.

> the entire image (not downsampled)

But you need the entire image to downsample it in the first place, no?

**Comment by pllim** [comment]
I am trying to have something like this: https://ginga.readthedocs.io/en/stable/manual/plugins_global/pan.html

**Comment by astrofrog** [comment]
I think the very simplest solution is just to make the compass some color that works well on black or white, and then have the option for the user to customize it if needed.

**Comment by astrofrog** [comment]
Ah I'm confused, if you want a pan birds-eye view, which is different from a compass, you can simply change:

```
arr = image[image.main_components[0]]
```

to e.g.

```
arr = image[image.main_components[0]][::100, ::100]
```

although of course the step value would need to be adjusted depending on image size - my point is that you should downsample the array before using it. Since ``image[image.main_components[0]]`` is a memory-mapped array, it's not actually loaded until you compute the limits or plot it so you can still slice it and it will be fast.

**Comment by pllim** [comment]
OK I will try downsampling, thanks!

> What about just picking a colour like orange or green which should be visible on the default image scale?

Does matplotlib imshow work like that? Or are you talking about glue behavior?

**Comment by astrofrog** [comment]
Note that if you downsample, you will need to pass ``extents`` to the ``imshow`` call to make it still be shown for the same x/y limits.

> Does matplotlib imshow work like that? Or are you talking about glue behavior?

Ignore my comments about this, I had misunderstood the purpose of the array.

**Comment by pllim** [comment]
Downsampling seems to be enough without other stuff, though we will still consider #1153 as that is nice to have.

Thanks again for the quick diagnosis, @astrofrog ! The compass stuff was an embarrassing oversight on my part.
