### ISSUE TITLE
Warn/error when adding data with conflicting labels

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/jdaviz#116]
This issue covers two use cases that should be dealt with similarly borne out from discussions in #83:

1. Data added to the `data_collection` with the same name (names aren't used in storing unique data sets) should raise a warning or error when using `app.add_data`. This can be confusing in the display to a user, and we should enforce uniqueness on the labels.

2. In the case where a user adds data to a viewer wherein the viewer already has that data viewed (e.g. `app.add_viewer_data('spectrum-viewer', 'some data label')`) should raise a warning to indicate that the data was already visible.

**Comment by rosteen** [comment]
@javerbukh would you consider this closed by #1672 ? Or at least out of date and able to be closed?
