### ISSUE TITLE
no data displays in cubeviz after recent update

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#118]
I've pulled in the latest changes (as of yesterday) to test some of the programmatic data/viewer loading, but now when I load the app with the cubeviz config, and load data, no data displays.  

After I pulled I also tried reinstalling jdaviz with `pip install -e .` just for good measure.  There was no obvious error or warning when loading the data.  Am I missing an update of something else?

I run 
```
from jdaviz.app import Application
app = Application(configuration='cubeviz')
app
data = '/Users/bcherinka/Work/notebooks/datb/manga-7495-12704-LOGCUBE.fits'
app.load_data(data)
```
but in each viewer, no data is displayed in the data or layer panels.

<img width="1205" alt="Screen Shot 2020-05-13 at 10 07 29 AM" src="https://user-images.githubusercontent.com/1836302/81822964-c3296f80-9501-11ea-9d15-b2883fe2a146.png">

**Comment by havok2063** [comment]
Ok, I think I fixed it now.  I had to manually update and reinstall `glue` and `glue-jupyter`.

**Comment by nmearl** [comment]
Thanks for checking this out @havok2063! I will investigate why the dependencies aren't being updated.

**Comment by havok2063** [comment]
Does it matter if they weren't originally linked to their repos?  I probably installed the repos straight with `pip install .`.  I reinstalled them in editable mode so they all point to the correct locations now.

**Comment by nmearl** [comment]
Perhaps! I'll be sure to look into it.
