### ISSUE TITLE
[BUG] Cubeviz: Can't enter exponential in Layer Stretch Limits

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#1188]
**Describe the bug**

**To Reproduce**
1. Launch Cubeviz
2. Load image or cube into cube viewer
3. Enter custom limits in min or max field of Layer tab
4. It is not possible to enter an exponential with 2 digits (e.g. 1E-12) because it auto corrects to, e. g. 0.1

**Expected behavior**
Don't autocorrect exponentials with double digits

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome 88, safari 22]
 - Jupyter: [run "jupyter --version"]
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.14.0
ipykernel        : 5.3.0
jupyter client   : 6.1.11
jupyter lab      : 3.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.6.5
nbformat         : 5.0.6
traitlets        : 5.0.5

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ]
Numpy 1.20.3
astropy 4.3.1
specutils 1.7.0
pyyaml 5.4.1
click 7.1.2
asteval 0.9.23
idna 2.10
traitlets 5.0.5
bqplot 0.12.33
bqplot-image-gl 1.4.5
glue-core 1.2.2
glue-jupyter 0.10.1
glue-astronomy 0.3.2
echo 0.5
ipyvue 1.7.0
ipyvuetify 1.8.1
ipysplitpanes 0.1.0
ipygoldenlayout 0.3.0
voila 0.2.6
vispy 0.6.6
Jdaviz 2.3.0

**Additional context (e.g. data files)**

**Comment by mariobuikhuizen** [comment]
This looks similar to: https://github.com/spacetelescope/jdaviz/issues/574

**Comment by astrofrog** [comment]
I'm re-opening just so that someone here can confirm that it fixes the issue in jdaviz - glue-jupyter v0.11.4 includes the fix so you may want to require that as a minimum version here?

**Comment by kecnry** [comment]
Works for me!  We should definitely make use of `glue-float-field` elsewhere in the app to take advantage of this and be self-consistent.  I'll open a PR to require v0.11.4 in jdaviz.
