### ISSUE TITLE
[BUG] Imviz: Clicking on regions after they're finalized breaks things

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1200]
**Describe the bug**
After finalizing regions, you can now apparently click them to go back into editing mode an drag them around, resize them, etc. Seems useful! However, it appears that after doing this, the mouse events (and even keyboard, actually) seem like they're never released from this state, so you can never blink images or see the coordinates/flux update on hover again after doing this. I'm not sure if a glue-jupyter update broke this, I listed my versions below but haven't checked with older versions yet. 

**To Reproduce**
1. Create a few regions.
2. Click on the first region, it should now be selected in the subset menu and you can drag it around
3. Try to do anything else with the mouse - hover, blink, etc. Doesn't work for anything but subset stuff now.

**Screenshots**

https://user-images.githubusercontent.com/39831871/160140020-b6076490-85e6-4073-98e2-de4a4ad5875f.mov

**Package versions (please complete the following information):**
macOS-10.15.7-x86_64-i386-64bit
Python 3.9.7 (default, Sep 16 2021, 08:50:36)
[Clang 10.0.0 ]
Numpy 1.22.3
astropy 5.0.2
specutils 1.7.0
spectral-cube 0.6.0
pyyaml 6.0
click 8.0.4
asteval 0.9.26
idna 3.3
traitlets 5.1.1
bqplot 0.12.33
bqplot-image-gl 1.4.6
glue-core 1.2.4
glue-jupyter 0.11.2
glue-astronomy 0.3.3
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.2
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.3.4
vispy 0.9.6
Jdaviz 2.3.1.dev112+g56fcebf7.d20220325 (main)

**Comment by rosteen** [comment]
I just checked, this is also a problem in the image viewers in Cubeviz, but doesn't seem to affect the profile viewers in Cubeviz/Specviz.

**Comment by pllim** [comment]
> doesn't seem to affect

Does this mean you cannot edit in profile viewer at all, or you can but it didn't break anything?

**Comment by rosteen** [comment]
It means that I can't get back into the edit state for the subset in the profile viewer by clicking on it. Probably because the x-range subset totally disappears after finalizing, and you're left with just the highlighted region of the spectrum.

**Comment by javerbukh** [comment]
I was able to get the bug to not trigger by clicking on another tool in the toolbar before right clicking. You can see the app start to behave weird with subsets blinking out and the wrong shape being selected.

https://user-images.githubusercontent.com/7179333/160150760-5d70238e-38cf-436f-9b00-2d27f390d9e8.mov

**Comment by rosteen** [comment]
Very strange that the ellipse selector created a rectangular region, are you sure your install is correct?

That aside, you need another step after what your gif shows to actually trigger the bug. Deselect any tools and then click on Subset 1. It should select that subset in the subset menu, and you can drag it around/resize it.

**Comment by javerbukh** [comment]
🤦‍♂️ Yeah wow my bad. Not sure how that region thing happened, it's a new conda environment.

**Comment by rosteen** [comment]
A potential clue from the console log: the event when clicking the subset with no tools selected appears to be firing a `dragstart` event that is then somehow getting picked up by `bqplot-image-gl`'s `BrushEllipseSelector` for some reason.

**Comment by pllim** [comment]
Is it related to this?

https://github.com/spacetelescope/jdaviz/blob/56fcebf7aa4772fe508fd01b47be9ea48761e27f/jdaviz/app.py#L172-L175

When did this start working like this? So many questions!

**Comment by pllim** [comment]
Hooks up to this but this is not new code:

https://github.com/glue-viz/glue-jupyter/blob/02fbb85cf011be5742ae4b49971c3a0aefdf8545/glue_jupyter/bqplot/common/tools.py#L37-L43

**Comment by javerbukh** [comment]
I did notice that this ticket has the same console error code that I see:
https://github.com/glue-viz/glue-jupyter/issues/94
```
ImageGLView.data is a Float64Array which WebGL does not support, will convert to a Float32Array
(consider sending float32 data for better performance).
```

**Comment by pllim** [comment]
The `Float64Array` is just a warning. It has never caused problems before.

**Comment by javerbukh** [comment]
Hmm. Have you or Ricky found which version of glue-jupyter might have introduced this? If not I'll try to figure it out. Something tells me that's where this originates.

**Comment by pllim** [comment]
Re: Subset edit behavior -- no, I have not have the chance to look into it.

Re: `Float64Array` -- It has been there since the beginning of Imviz. I wouldn't waste time on it right now.

**Comment by javerbukh** [comment]
Switched to glue-jupyter v11.1, v11.0, and v10.1, as well as bqplot-image-gl 1.4.5 and 1.4.4, and the error appeared every time.

**Comment by rosteen** [comment]
> Could it be that this bug has always been there but we just never realized?

It's possible, but I rate it as unlikely, since I'm pretty sure I remember the POs at some point wishing that they had the ability to go back and edit subsets but didn't. I could be misremembering though. The only work for something similar to this that I explicitly remember is when Nick added the capability to edit the region selection before clicking away/finalizing the selection.

What I do think is possible is that it's been in there for a while (but not forever) rather than being very recent.

@javerbukh I tried similar versions to you. I also tried reverting back to the commit in Jdaviz before @kecnry introduced the `toolbar_nested` since I thought that there might be confusion on the backend where it was registering something from `toolbar`, but the bug still appeared with the flat toolbar.

**Comment by pllim** [comment]
Good news is... API calls still work, so theoretically you can still zoom/pan after this bug all with API calls... 😒

**Comment by pllim** [comment]
This got me stumped. I played around in glue-jupyter at a few places where I thought this might trigger but I can't find it. I failed to disable the edit "feature". Hopefully @astrofrog will have some ideas next week. 🤞

**Comment by pllim** [comment]
As far as my glue-fu allows, I caught this event (re-entering editing mode after finalization) here:

https://github.com/glue-viz/glue-jupyter/blob/02fbb85cf011be5742ae4b49971c3a0aefdf8545/glue_jupyter/widgets/subset_mode_vuetify.py#L81

Instead of `msg.subset = []`, at this point it has `msg.subset = [<Subset ...>]`. I tried catching that and return a no-op but it didn't work. The bug seems to be already triggered before this point, so maybe @rosteen and @kecnry 's suspicion of https://github.com/glue-viz/bqplot-image-gl/blob/master/js/lib/BrushEllipseSelector.js#L30 and https://github.com/glue-viz/bqplot-image-gl/blob/master/js/lib/BrushEllipseSelector.js#L117-L118 might be on the point but I am not sure how to fix that. 🐰 🕳️

**Comment by rosteen** [comment]
@astrofrog Checking now...
