### ISSUE TITLE
WCS linking and showing multiple layers

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/jdaviz#121]
Currently it does not seem to be possible to display multiple layers on the same plot. This seems like it might be related to not being able to link the WCS's?

1. Creating a collapsed 2D image and adding it to a viewer with some data already plotted does not seem to allow the user to flip back and forth or show/hide the layers. (They must "uncheck" all data, then "recheck" data to switch the shown data set, but can never seem to e.g. mess with the opacity of one layer to view the other underneath).

2. Spectral data (plotting the data of a cube, and then also plotting the data of smoothed data) doesn't seem to render on the same plot. The user must also "uncheck" all data and "recheck" the data they want to view. (This maybe due to WCS information?)

**Comment by astrofrog** [comment]
This should be fixed in #122
