### ISSUE TITLE
Make a "truly minimal" specviz configuration and corresponding helper app

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#124]
The title here minimal in terms of functionality, which is not sufficient for minimal scientific workflows, but sufficient to just get data into a spectrum viewer.  Specifically, what is needed is a configuration that:

1. Shows a viewer that looks the same (and can be interact with by plugins the same way as) the bottom panel of the `cubeviz` configuration
2.  Has a helper class a la #104 with a `load_data` method that takes a `Spectrum1D`, loads it into glue-jupyter and auto-selects the correct data in the UI accordingly
2b (stretch goal, not truly "minimal": have this also support a filename instead of a `Spectrum1D`, which just is syntactic sugar for `Spectrum1D.read(filename)`
3. Can get data out (via `specviz.app.get_data`, although possibly just `specviz.get_data` since there's only one viewer?) that looks the same as what was loaded in.

**Comment by havok2063** [comment]
I started working on this with #93 since I needed something similar.  I'm happy to flesh this out more if you want to take a look at it.  It probably needs more work to satisfy numbers 2 and 3.

**Comment by eteq** [comment]
Closed via #149
