### ISSUE TITLE
[BUG] Mosviz: 2D Spectrum data invisible

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#1243]
**Describe the bug**
This issue is a little sporadic. When loading Mosviz data, *sometimes* the 2D spectrum data is invisible. Interacting with the data makes it reappear. Happens in both desktop mode and within the jupyter notebook, but easier to reproduce in the desktop app.

**To Reproduce**
1. Load our sample dataset
2. Notice the 2D spectrum isn't visible
3. Interact with the 2d viewer, say with the pan tool
4. Notice the 2D spectrum appear after releasing

**Expected behavior**
The 2D spectrum should be visible from the beginning

**Screenshots**
https://user-images.githubusercontent.com/25206008/162973781-fd8e2c53-8602-4d13-9d03-1fc69db9f47d.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 100.0.4896.60 (Official Build) (x86_64)

**Package versions (please complete the following information):**
[freeze_april12.txt](https://github.com/spacetelescope/jdaviz/files/8473338/freeze_april12.txt)

**Comment by duytnguyendtn** [comment]
Found when reviewing #1232

**Comment by astrofrog** [comment]
https://github.com/glue-viz/glue-jupyter/pull/310 has been merged, can someone try it out?

**Comment by duytnguyendtn** [comment]
I tried to cycle through a few instances of mosviz and I couldn't reproduce, so it appears to be gone for now. Thanks for the fix!!
