### ISSUE TITLE
[BUG] Cubeviz: model fitting over the cube fails with spectral subset

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1245]
**Describe the bug**
If you select a spectral subset in the dropdown in Model Fitting before fitting over the cube, the result cube will come back with all 0 values.

**To Reproduce**
1. Select a subset in the spectrum viewer
2. Open model fitting, select the spectral subset, create a linear component model
3. Click "Apply to Cube"
4. Retrieve the fitted cube in the notebook, see that it's all 0.

**Expected behavior**
The fit will be done on the selected spectral region for every spaxel.

**Comment by pllim** [comment]
Is there a JIRA ticket for this? I cannot find it.
