### ISSUE TITLE
[BUG] Imviz: Error when trying to save list of photometry results

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdaviz#1330]
results.write('myphotometry.ecsv', overwrite=True) results in an error (pated below). It's a bit hard to reproduce the steps, but here's what the Photometry Table Looks like:

id | xcentroid | ycentroid | sky_centroid | background | sum | sum_aper_area | pixarea_tot | aperture_sum_counts | aperture_sum_counts_err | counts_fac | aperture_sum_mag | flux_scaling | min | max | mean | median | mode | std | mad_std | var | biweight_location | biweight_midvariance | fwhm | semimajor_sigma | semiminor_sigma | orientation | eccentricity | data_label | subset_label | timestamp
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 615.7815137849891 | 558.00633129254 | 0.004131885658486467,-0.0016110734013966297 | 0.01738896034657955 | 4.348690039115338e-09 | 427.10173216713656 | 1.2146927426189528e-10 | None | None | None | None | None | -0.06539987586438656 | 3.4819348845630884 | 0.08341204984322273 | 0.012704982422292233 | -0.12870915241956876 | 0.34871342809064065 | 0.03175057456368669 | 0.1216010549307264 | 0.010911158671512966 | 0.0012430045972846328 | 5.1379338870583835 | 2.595769671558915 | 1.6682857208029946 | 9.660929038337956 | 0.7661229400186473 | F770W[DATA] | Subset 2 | 2022-05-19 15:19:04.501972
2 | 615.4127837763052 | 557.8908187811392 | 0.004142881814287413,-0.0016156078170025405 | 0.018219906836748123 | 1.842493135268601e-09 | 190.0153141226625 | 5.404104120114793e-11 | None | None | None | None | None | -0.030369767919182777 | 3.48110393807292 | 0.17745605534651077 | 0.03398430347442627 | -0.2529592002697427 | 0.5038940927742009 | 0.06072074792202693 | 0.25390925673273507 | 0.036648992805297695 | 0.0034283332216201675 | 3.8645768936743043 | 1.7314891703154704 | 1.5455068668732033 | -42.697942651491445 | 0.45087275165266144 | F770W[DATA] | Subset 3 | 2022-05-19 15:19:36.251051
3 | 615.4127837763052 | 557.8908187811392 | 0.004142881814287413,-0.0016156078170025405 | 0.018219906836748123 | 1.842493135268601e-09 | 190.0153141226625 | 5.404104120114793e-11 | 1.7047165397966677 ct | 1.3056479386866384 ct | 20.0 MJy / (ct sr) | nan mag | -5.0 MJy / sr | -0.030369767919182777 | 3.48110393807292 | 0.17745605534651077 | 0.03398430347442627 | -0.2529592002697427 | 0.5038940927742009 | 0.06072074792202693 | 0.25390925673273507 | 0.036648992805297695 | 0.0034283332216201675 | 3.8645768936743043 | 1.7314891703154704 | 1.5455068668732033 | -42.697942651491445 | 0.45087275165266144 | F770W[DATA] | Subset 3 | 2022-05-19 15:20:01.753599
4 | 615.4127837763052 | 557.8908187811392 | 0.004142881814287413,-0.0016156078170025405 | 0.018219906836748123 | 1.842493135268601e-09 | 190.0153141226625 | 5.404104120114793e-11 | 1.7047165397966677 ct | 1.3056479386866384 ct | 20.0 MJy / (ct sr) | -2.084280415473245 mag | 5.0 MJy / sr | -0.030369767919182777 | 3.48110393807292 | 0.17745605534651077 | 0.03398430347442627 | -0.2529592002697427 | 0.5038940927742009 | 0.06072074792202693 | 0.25390925673273507 | 0.036648992805297695 | 0.0034283332216201675 | 3.8645768936743043 | 1.7314891703154704 | 1.5455068668732033 | -42.697942651491445 | 0.45087275165266144 | F770W[DATA] | Subset 3 | 2022-05-19 15:20:11.235011

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Input In [18], in <cell line: 4>()
      1 # Get and save photometry
      3 results = imviz.get_aperture_photometry_results()
----> 4 results.write('myphotometry.ecsv', overwrite=True)
      5 results

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/table/connect.py:129, in TableWrite.__call__(self, serialize_method, *args, **kwargs)
    127 instance = self._instance
    128 with serialize_method_as(instance, serialize_method):
--> 129     self.registry.write(instance, *args, **kwargs)

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/registry/core.py:354, in UnifiedOutputRegistry.write(self, data, format, *args, **kwargs)
    350     format = self._get_valid_format(
    351         'write', data.__class__, path, fileobj, args, kwargs)
    353 writer = self.get_writer(format, data.__class__)
--> 354 return writer(data, *args, **kwargs)

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/connect.py:26, in io_write(format, table, filename, **kwargs)
     24     format = re.sub(r'^ascii\.', '', format)
     25     kwargs['format'] = format
---> 26 return write(table, filename, **kwargs)

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/ui.py:840, in write(table, output, format, Writer, fast_writer, overwrite, **kwargs)
    837     writer.write(table, output)
    838     return
--> 840 lines = writer.write(table)
    842 # Write the lines to output
    843 outstr = os.linesep.join(lines)

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/core.py:1494, in BaseReader.write(self, table)
   1492 lines = []
   1493 self.write_header(lines, table.meta)
-> 1494 self.data.write(lines)
   1496 return lines

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/core.py:926, in BaseData.write(self, lines)
    923 while len(lines) < data_start_line:
    924     lines.append(itertools.cycle(self.write_spacer_lines))
--> 926 col_str_iters = self.str_vals()
    927 for vals in zip(*col_str_iters):
    928     lines.append(self.splitter.join(vals))

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/ecsv.py:392, in EcsvData.str_vals(self)
    389         return str(col[idx])
    391 try:
--> 392     col.str_vals = [format_col_item(idx) for idx in range(len(col))]
    393 except TypeError as exc:
    394     raise TypeError(f'could not convert column {col.info.name!r}'
    395                     f' to string: {exc}') from exc

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/ecsv.py:392, in <listcomp>(.0)
    389         return str(col[idx])
    391 try:
--> 392     col.str_vals = [format_col_item(idx) for idx in range(len(col))]
    393 except TypeError as exc:
    394     raise TypeError(f'could not convert column {col.info.name!r}'
    395                     f' to string: {exc}') from exc

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/io/ascii/ecsv.py:383, in EcsvData.str_vals.<locals>.format_col_item(idx)
    381 obj = col[idx]
    382 try:
--> 383     obj = obj.tolist()
    384 except AttributeError:
    385     pass

File ~/miniconda3/envs/documentation2/lib/python3.8/site-packages/astropy/units/quantity.py:1522, in Quantity.tolist(self)
   1521 def tolist(self):
-> 1522     raise NotImplementedError("cannot make a list of Quantities.  Get "
   1523                               "list of values with q.value.tolist()")

NotImplementedError: cannot make a list of Quantities.  Get list of values with q.value.tolist()`
```

**Comment by pllim** [comment]
That is weird. QTable should not have crashed with Quantity stuff. What astropy version is this?

**Comment by pllim** [comment]
Ori, is your table a `Table` or `QTable`? I do not see any units listed in your table above.

**Comment by pllim** [comment]
@orifox , do you have a workflow that can consistently reproduce this error? If you have not seen this lately, maybe we should just close this.

**Comment by pllim** [comment]
I never heard back...
