### ISSUE TITLE
[FEAT] Imviz: Add Roman ASDF Support

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/jdaviz#1355]
### Description

Need to add support for Roman ASDF files. Currently imviz does not understand what an ASDF file is (it complains that it's not a FITS file).

### Additional context

[🐱](https://jira.stsci.edu/browse/JDAT-2478)

**Comment by pllim** [comment]
Looking forward to your exploratory draft PR from https://github.com/tddesjardins/jdaviz/tree/roman_imviz 😸
