### ISSUE TITLE
Update icons to material design icons + Jenn's designs on github

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#138]

**Comment by astrofrog** [comment]
Can we see a preview here? :)

**Comment by Jenneh** [comment]
<img width="939" alt="Screen Shot 2020-06-08 at 10 27 37 AM" src="https://user-images.githubusercontent.com/2945880/84042139-b4a06d80-a972-11ea-8f51-5655c42d44e5.png">

Icons can be found in the repo at: jdaviz/jdaviz/data/icons/

**Comment by Jenneh** [comment]
<img width="435" alt="Screen Shot 2020-06-08 at 10 40 48 AM" src="https://user-images.githubusercontent.com/2945880/84043790-b9feb780-a974-11ea-8a42-88d00c17e962.png">
