### ISSUE TITLE
Discuss option of keeping hamburger menu always open

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#140]

**Comment by Jenneh** [comment]
We may choose to  switch the collapsible panel  to a normal toolbar to prevent overlap and blocking data plotted on the graph.

<img width="109" alt="Screen Shot 2020-06-08 at 10 21 19 AM" src="https://user-images.githubusercontent.com/2945880/84041448-db11d900-a971-11ea-8cdb-6854f5a274e2.png">
<img width="197" alt="Screen Shot 2020-06-08 at 10 21 22 AM" src="https://user-images.githubusercontent.com/2945880/84041450-db11d900-a971-11ea-809a-f116f0ae19b5.png">

**Comment by camipacifici** [comment]
This has been done. Closing.
