### ISSUE TITLE
[BUG] Imviz: Markers are creating an image rather than a plot overlay?

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1411]
-  When trying to overlay positions from a catalog, I'm getting some sort of image overlay rather than the markers.
- The window is resizing unexpectedly when I try to inspect the image planes 
- Removing the markers seems to work, but throws an error message nonetheless

**To Reproduce**

See video screen capture at https://drive.google.com/file/d/1NbKlT4mICiXBUoRXTyYLz8iWmq9Es3Zo/view?usp=sharing

**Expected behavior**
Expected to see circles of the catalog positions overlayed on the image as green circles.

**Screenshots**
https://drive.google.com/file/d/1NbKlT4mICiXBUoRXTyYLz8iWmq9Es3Zo/view?usp=sharing

**Desktop (please complete the following information):**
 - MacBook Pro 16" 2019 OS 10.15.7
 - Browser: safari 15.5
 - Python 3.10
 - Jupyter: 
Selected Jupyter core packages...
IPython          : 8.3.0
ipykernel        : 6.13.0
ipywidgets       : 7.7.0
jupyter_client   : 7.3.1
jupyter_core     : 4.10.0
jupyter_server   : 1.17.0
jupyterlab       : 3.4.2
nbclient         : 0.5.13
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.11
qtconsole        : 5.3.0
traitlets        : 5.2.1.post0

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:43:32) [Clang 12.0.1 ]
Numpy 1.22.3
astropy 5.0.4
matplotlib 3.5.2
scipy 1.8.1
scikit-image 0.19.2
asdf 2.11.1
gwcs 0.18.1
regions 0.6
specutils 1.7.0
photutils 1.4.0
pyyaml 6.0
click 8.1.3
asteval 0.9.27
idna 3.3
traitlets 5.2.1.post0
bqplot 0.12.33
bqplot-image-gl 1.4.9
glue-core 1.3.0
glue-jupyter 0.12.0
glue-astronomy 0.4.0
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.2
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.3.5
vispy 0.10.0
sidecar 0.5.1
Jdaviz 2.6.1.dev3+g70eb5f1

**Additional context (e.g. data files)**

FITS image https://drive.google.com/file/d/1uv-MxWCXFEBZNkglPy-jZWeLDqSuokKK/view?usp=sharing
FITS catalog https://drive.google.com/file/d/14YenkfVKNezdqjA7mjMEzyN3q9xzl-zc/view?usp=sharing

**Comment by pllim** [comment]
I can reproduce this and I think the problem is you are trying to mark almost 1.5 million markers. That probably crowded out the display, causing undefined behavior. They appear fine if I only try to plot the first 999 markers.

Have you tried to filter to the markers that you really care about first before trying to mark them?

**Comment by hcferguson** [comment]
Didn't realize that catalog was so big. I'll filtering it to just plot the sources in the field of view.

**Comment by pllim** [comment]
Please let me know if filtering fixes the issue. If not, we can investigate more. Thanks!

**Comment by pllim** [comment]
Thanks for the update! I'll see of `wcs.footprint_contains()` works in both FITS WCS and GWCS. If not, maybe doc update is the best we can do. Or throw an error when over 30k entries are attempted or something.

**Comment by larrybradley** [comment]
@hcferguson Regarding the notebook cell resizing, if you double click on the left of the cell output (i.e., in the whitespace left of Imviz), the cell output will go back to full size. I think Jupyter resized the cell output because of the long traceback.

**Comment by pllim** [comment]
I thought about this and I think limiting ourselves to doc update is the most flexible solution. That way, user can choose to filter if they want. There might be use cases where you would want to load a table even for positions not in current visible frame.

Furthermore, the API for FITS WCS and GWCS are indeed different:

* https://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS.footprint_contains
* https://gwcs.readthedocs.io/en/latest/api/gwcs.wcs.WCS.html#gwcs.wcs.WCS.in_image

And what if not all the loaded images have a valid WCS?

@hcferguson , would a specialized notebook under `notebooks/concepts/` folder be enough, or you want it worked into the official example somehow?

**Comment by pllim** [comment]
Does #1416 look good to you, @hcferguson ?

**Comment by hcferguson** [comment]
Looks good to me.
