### ISSUE TITLE
Remove unnecessary digits or have options for users for how they want plot numbers visualized (5e-7 vs .0000005)

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#142]

**Comment by Jenneh** [comment]
<img width="314" alt="Screen Shot 2020-06-08 at 10 18 17 AM" src="https://user-images.githubusercontent.com/2945880/84041075-66d73580-a971-11ea-861b-a0386fadb5d9.png">


Do not show unnecessary zeros
