### ISSUE TITLE
[FEAT] Imviz: Show the name of the dataset being used for the cursor readback (currently in Compass)

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1426]
### Description

Show the name of the dataset that is currently being used for the cursor readback (pixel coords & flux in the upper right). 

### Additional context

The cursor read back doesn't tell you which image it applies to. Nor does the Imviz viewer tell you which image is "on top" in the stack.

**Comment by kecnry** [comment]
There was an idea floated around to indicate the "top layer" in the data dropdown menu, which would at least expose this in a more "global" place than a seemingly-unrelated plugin.  We could also consider this when we add labels on the viewers themselves (e.g., "Imviz-0: top-layer-data-label").

**Comment by pllim** [comment]
> Imviz-0: top-layer-data-label

JWST label might be very long, then we have a problem with overcrowding of viewer tabs when multiple viewers are open. 🤷

**Comment by pllim** [comment]
> let the user toggle between sexagesimal or decimal in a plugin window, rather than showing both

@PatrickOgle wanted both shown, so he should comment.
