### ISSUE TITLE
Change hamburger menu icon to toolbar icon and then "X" when it is extended

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#143]

**Comment by Jenneh** [comment]
<img width="712" alt="Screen Shot 2020-06-08 at 10 16 04 AM" src="https://user-images.githubusercontent.com/2945880/84040809-165fd800-a971-11ea-80ac-4544bbb6bfe6.png">

**Comment by Jenneh** [comment]
<img width="435" alt="Screen Shot 2020-06-08 at 10 40 48 AM" src="https://user-images.githubusercontent.com/2945880/84045198-84f36480-a976-11ea-8092-5779ab299830.png">
