### ISSUE TITLE
[FEAT] Cubeviz: importing existing region files

### ISSUE THREAD

**Issue by ThomasSYLai** [spacetelescope/jdaviz#1432]
### Description

During the spectrum extraction process in cubeViz, it would be extremely useful to have the function to place pre-defined regions in the flux viewer so that spectra can be extracted directly. To my understanding, so far the only way to define regions is by manually selecting regions in the viewer. This makes spectrum extraction hard to reproduce results, particularly in the case of handling MIRI IFU observations of resolved sources, in which one needs to extract spectra from 12 channels with accurate centering and appropriate aperture size. 

### Additional context

[🐱](https://jira.stsci.edu/browse/JDAT-2544)

**Comment by pllim** [comment]
@ThomasSYLai , this is now possible with the dev version of Jdaviz and it will be released soon in v2.9. Please open new issue if you are still unable to load region files even with this new feature.
