### ISSUE TITLE
Update "select region" buttons

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#144]
Involves changing the design and also visually grouping the buttons. Also change dropdown slightly.

**Comment by Jenneh** [comment]
<img width="346" alt="Screen Shot 2020-06-08 at 10 13 50 AM" src="https://user-images.githubusercontent.com/2945880/84040572-c719a780-a970-11ea-8f55-402ef065ef12.png">

**Comment by rosteen** [comment]
Old, closing.
