### ISSUE TITLE
Update "plugin" bar

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#146]
Leave a label that shows what the bar does, in addition to an icon that shows the bar can be expanded and collapsed.

**Comment by Jenneh** [comment]
<img width="694" alt="Screen Shot 2020-06-08 at 10 09 00 AM" src="https://user-images.githubusercontent.com/2945880/84040043-1dd2b180-a970-11ea-8faa-ab4417bd551d.png">

**Comment by Jenneh** [comment]
We will be trying the material design icon - 'dip-switch' with hover text that says "Analysis"

<img width="117" alt="screen_shot_2020-06-24_at_8 52 46_pm" src="https://user-images.githubusercontent.com/2945880/85847889-3adff080-b776-11ea-9bf3-3e2862569954.png">
<img width="670" alt="screen_shot_2020-06-24_at_11 11 30_am" src="https://user-images.githubusercontent.com/2945880/85847920-46331c00-b776-11ea-98d5-b2d8f040753b.png">

**Comment by rosteen** [comment]
We ended up with a hamburger icon along with a "Data Analysis Plugins" hover tooltip, closing this as out-of-date.
