### ISSUE TITLE
[FEAT] Add ability to retrieve subset applied to specific spectrum

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1490]
Currently, when you use `get_spectra`, you get back a spectrum for each of the subsets that are defined. However, if there are multiple spectra, you still only get back one spectrum per subset, applied to (I believe) the most recent data added to the viewer (although there might not be any consistency here). We should update the relevant API methods so that there is a way through the API to retrieve a specific spectrum with a specific subset applied to it, rather than needing to get the mask from the subset spectrum returned to apply to another spectrum.

**Comment by pllim** [comment]
Also see: https://github.com/spacetelescope/jdaviz/discussions/1582

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JDAT-2594](https://jira.stsci.edu/browse/JDAT-2594)._

**Comment by stscijgbot-jwql** [comment]
_Comment by [Camilla Pacifici](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cpacifici) on [JIRA](https://jira.stsci.edu/browse/JDAT-2594?focusedCommentId=616526#comment-616526):_

The output of get_spectra seems wrong. See screenshot and output here:
{'jw02732-c1001_t004_miri_ch1-longmediumshort-_x1d': <Spectrum1D(flux=<Quantity [22.06800698, 21.67234675, 18.13024819, ..., 67.15146685,
            66.67507554, 66.62986612] MJy / sr>, spectral_axis=<SpectralAxis 
    (observer to target:
       radial_velocity=0.0 km / s
       redshift=0.0)
   [4.9005001 , 4.9015001 , 4.9025001 , ..., 7.64750023, 7.64850023,
    7.64950023] um>, uncertainty=StdDevUncertainty([6.66712587, 5.90540278, 5.63616389, ..., 5.74446156,
                    5.51737985, 5.41050451]))>,


 'jw02732-c1001_t004_miri_ch2-longmediumshort-_x1d': <Spectrum1D(flux=<Quantity [36.39466612, 36.53507052, 35.3381142 , ..., 53.61827448,
            53.18940731, 52.5410928 ] MJy / sr>, spectral_axis=<SpectralAxis 
    (observer to target:
       radial_velocity=0.0 km / s
       redshift=0.0)
   [ 7.51100023,  7.51300023,  7.51500023, ..., 11.70500043, 11.70700043,
    11.70900043] um>, uncertainty=StdDevUncertainty([2.99726213, 2.74131887, 2.58385531, ..., 2.75868379,
                    2.70428171, 2.76932534]))>,

 'Subset 1': <Spectrum1D(flux=<Quantity [36.39466612, 36.53507052, 35.3381142 , ..., 53.61827448,
            53.18940731, 52.5410928 ] MJy / sr>, spectral_axis=<SpectralAxis 
    (observer to target:
       radial_velocity=0.0 km / s
       redshift=0.0)
   [ 7.51100023,  7.51300023,  7.51500023, ..., 11.70500043, 11.70700043,
    11.70900043] um>, uncertainty=StdDevUncertainty([2.99726213, 2.74131887, 2.58385531, ..., 2.75868379,
                    2.70428171, 2.76932534]))>,

 'Subset 2': <Spectrum1D(flux=<Quantity [36.39466612, 36.53507052, 35.3381142 , ..., 53.61827448,
            53.18940731, 52.5410928 ] MJy / sr>, spectral_axis=<SpectralAxis 
    (observer to target:
       radial_velocity=0.0 km / s
       redshift=0.0)
   [ 7.51100023,  7.51300023,  7.51500023, ..., 11.70500043, 11.70700043,
    11.70900043] um>, uncertainty=StdDevUncertainty([2.99726213, 2.74131887, 2.58385531, ..., 2.75868379,
                    2.70428171, 2.76932534]))>,

 'Subset 3': <Spectrum1D(flux=<Quantity [36.39466612, 36.53507052, 35.3381142 , ..., 53.61827448,
            53.18940731, 52.5410928 ] MJy / sr>, spectral_axis=<SpectralAxis 
    (observer to target:
       radial_velocity=0.0 km / s
       redshift=0.0)
   [ 7.51100023,  7.51300023,  7.51500023, ..., 11.70500043, 11.70700043,
    11.70900043] um>, uncertainty=StdDevUncertainty([2.99726213, 2.74131887, 2.58385531, ..., 2.75868379,
                    2.70428171, 2.76932534]))>}
