### ISSUE TITLE
[BUG] Imviz: Layer names are sometimes garbled

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1496]
**Describe the bug**
The layer names are sometimes garbled when I load in an image using `imviz.load_data`. 

**To Reproduce**
See screenshot.

**Expected behavior**
I can understand that sometimes imviz might have to make up a reasonable name for a layer -- for example if it was just fed a numpy array. In this case, I fed it fits HDU's, so I would expect it to do something sensible based on the headers. 

**Screenshots**
<img width="1073" alt="Screen Shot 2022-07-15 at 2 12 33 PM" src="https://user-images.githubusercontent.com/2261329/179286053-75ad5ca4-9972-45d9-838f-83e7350f22e7.png">

**Desktop (please complete the following information):**
MacBook Pro 16" 2019 OS 10.15.7
Browser: safari 15.5
Python 3.10
Jupyter:
Selected Jupyter core packages...
IPython : 8.3.0
ipykernel : 6.13.0
ipywidgets : 7.7.0
jupyter_client : 7.3.1
jupyter_core : 4.10.0
jupyter_server : 1.17.0
jupyterlab : 3.4.2
nbclient : 0.5.13
nbconvert : 6.5.0
nbformat : 5.4.0
notebook : 6.4.11
qtconsole : 5.3.0
traitlets : 5.2.1.post0

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:43:32) [Clang 12.0.1 ]
Numpy 1.22.3
astropy 5.0.4
matplotlib 3.5.2
scipy 1.8.1
scikit-image 0.19.2
asdf 2.12.0
gwcs 0.18.1
regions 0.6
specutils 1.7.0
photutils 1.4.0
pyyaml 6.0
click 8.1.3
asteval 0.9.27
idna 3.3
traitlets 5.2.1.post0
bqplot 0.12.33
bqplot-image-gl 1.4.9
glue-core 1.5.0
glue-jupyter 0.12.0
glue-astronomy 0.4.0
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.2
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.3.5
vispy 0.10.0
sidecar 0.5.1
Jdaviz 2.7.2.dev1+g32e95fdb

**Additional context (e.g. data files)**

**Comment by kecnry** [comment]
you can pass custom labels to `load_data`, but I agree it would be nice if we could avoid have better human-readable defaults in cases like this (especially since I've seen these on the embedded version on mast)!

**Comment by pllim** [comment]
This is a feature, not a bug.

When you send in an object (like HDU), Imviz has no way to know how you want to name it. So, it assigns something random enough with low risk of name-clash when you load multiple objects. This behavior is inherited from the other viz already in Jdaviz when Imviz was designed.

https://github.com/spacetelescope/jdaviz/blob/d24f8239ac0e1571b4926f2afdb9abf188033951/jdaviz/configs/imviz/plugins/parsers.py#L60

If you want meaningful labels, you have to explicitly name them using `data_label` like this:

```python
imviz.load_data(hdu[1], data_label='my_first_hdu')
```
