### ISSUE TITLE
[BUG] Imviz: WCS's for JWST extensions in FITS files not picked up

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1497]
**Describe the bug**
Imviz isn't assigning the science-extension WCS to the other extensions in JWST FITS files when I feed the HDU's to `imviz.load_data`. (It does seem to be assigning the WCS when I give it the filename and extension, but then it is reading the FITS file three times presumably, instead of just once?).

**To Reproduce**
See screenshot

**Expected behavior**
I didn't expect to see the error message shown in the screenshot.

**Screenshots**
<img width="1078" alt="Screen Shot 2022-07-15 at 2 25 15 PM" src="https://user-images.githubusercontent.com/2261329/179288694-767fcffa-b809-4e73-ac9f-ec0b19f435a4.png">

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome 88, safari 22]
 - Jupyter: [run "jupyter --version"]

**Package versions (please complete the following information):**

**Additional context (e.g. data files)**
The FITS extensions in the JWST file, other than SCI, don't have a WCS. So this is likely why this is happening. I don't get the error message if I read from file and extensions 
```
imviz.load_data(file+'[SCI]')
imviz.load_data(file+'[ERR]')
imviz.load_data(file+'[DQ]')
```

[🐱](https://jira.stsci.edu/browse/JDAT-2598)

**Comment by pllim** [comment]
@hcferguson , what is the `set_stretch(viewer, layers=[0])`? That is not part of Jdaviz. Could that be what broke your workflow?

**Comment by hcferguson** [comment]
@pllim It's just a hack so I can set the stretch programmatically on selected layers when I load them. It's a time saver when I run a notebook repeatedly. There's probably a better way to do this...

```
# Imviz kludge for setting the stretch programmatically 
def set_stretch(viewer,layers,percentile='Custom',vmin=0.1,vmax=10,stretch='arcsinh'):
    if isinstance(layers,int):
        layers = [layers]
    layerlist = [viewer.state.layers[l] for l in layers]
    for v in layerlist:
        v.percentile = percentile
        v.v_min = vmin
        v.v_max = vmax
        v.stretch = stretch
```

**Comment by hcferguson** [comment]
Maybe migrate this ticket to a feature request for the jwst pipeline to put a WCS on the FITS extensions?

**Comment by pllim** [comment]
> feature request for the jwst pipeline to put a WCS on the FITS extensions?

It is already on FITS extension but only the SCI, as with HST data. Why do you need sky coordinates for ERR and DQ?

**Comment by pllim** [comment]
I still have to add a test to #1499 but it should fix the crashing. Can you please try that PR branch out and confirm with your data? Thanks!
