### ISSUE TITLE
[FEAT] Imviz: load_data should support jwst.datamodels.ImageModel

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#1500]
### Description

If you have already instantiated imviz and read in a JWST image into an `ImageModel`, via (e.g.) 
```
from jwst.datamodels import ImageModel
im = ImageModel(filename)
```

It would be nice not to have imviz re-read the file, but instead just pass it the data model: 
`imviz.load_data(im)`

### Additional context

This is probably not worth it if it makes the jwst package a hard (not optional) dependency for jdaviz.

**Comment by pllim** [comment]
To have to check for `isinstance(im, ImageModel)` but make the `ImageModel` import *optional* would overcomplicate things despite being possible. If you know of some sure-fire `hasattr` check that would sniff it out without importing it, then it would be easier to implement.

**Comment by hcferguson** [comment]
Agreed. Not sure how to implement it. Maybe a lightweight wrapper, so that `imviz = jdaviz.Imviz_jwst()` overloads the `load_data` method and does the import when it is instantiated?

**Comment by pllim** [comment]
> jdaviz.Imviz_jwst()

This opens a can of worms. Then do we need a wrapper for each telescope out there?

**Comment by hcferguson** [comment]
Only if they want to customize something. In this case the customization is having Imviz be able to load from in-memory data models. Another prominent example of a telescope with custom data models is LSST, so maybe thinking through how we might support their data models would help decide how/whether to implement something.

**Comment by pllim** [comment]
I am not sure if this would be top priority. It is more lines of code but you can already wrap array, unit, and WCS from ImageModel to NDData and pass that in instead and get a functional Imviz. We have more important features to implement first and many bugs to fix.

**Comment by hcferguson** [comment]
Yes, I completely agree. Not top priority.

**Comment by pllim** [comment]
@orifox said he has some code for this. So maybe we can add a concept notebook. Will that help?

**Comment by hcferguson** [comment]
Cool. Sounds useful.

**Comment by orifox** [comment]
Hi @hcferguson, didn't have time to read this whole thread. Does this help? One of our strengths is being able to deal with data models. BUT...you need code to do it, because we made a strong decision not to directly support datamodels because it requires a dependency on the jwst package. We have been petitioning for STScI to pull the datamodels out separately from jwst, and then we can directly support it. 
https://jdaviz.readthedocs.io/en/latest/imviz/import_data.html#jwst-datamodels

**Comment by hcferguson** [comment]
Thanks. That's a good addition to the docs. That's what I've been doing when I need to add  a WCS to the extensions of the JWST FITS files (which irritatingly only have the WCS for the SCI extension).
