### ISSUE TITLE
Option to sync image layers

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#151]
Add option in UI to sync the scaling / colormap, etc across all loaded images.  For example, to apply a logarithmic stretch with 95% percentile, takes 7 clicks initially per image viewer (5 to get there, 2 to close windows/drawers).  21 clicks to do all three viewers in cubeviz is a lot.

**Comment by pllim** [comment]
This might be naturally solved by having `astrowidgets` API in Imviz...?

**Comment by pllim** [comment]
Ops... I didn't see this one when I opened #750. You are not the only one who desires this feature, it seems. Since that ticket already has a JIRA ticket associated with it, I am closing this as duplicate. Sorry!
