### ISSUE TITLE
[BUG] Imviz: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by JosephKarpinski** [spacetelescope/jdaviz#1533]
**Describe the bug**

**To Reproduce**
<img width="1438" alt="Screen Shot 2022-07-31 at 4 34 42 PM" src="https://user-images.githubusercontent.com/37123616/182044673-fdec6d03-449c-4bde-a378-ede178570a1d.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS-11.6-x86_64-i386-64bit]
 - Browser: [e.g. chrome 88, safari 22]
 - Jupyter: [run "jupyter --version"]
 
<img width="776" alt="Screen Shot 2022-07-31 at 4 50 46 PM" src="https://user-images.githubusercontent.com/37123616/182044897-74955a10-9e1d-4051-bd2d-f3df70f3f362.png">

**Package versions (please complete the following information):**

<img width="776" alt="Screen Shot 2022-07-31 at 4 47 44 PM" src="https://user-images.githubusercontent.com/37123616/182044793-69671805-17b5-4ad0-84e4-a78fd5129104.png">

**Additional context (e.g. data files)**

**Comment by mariobuikhuizen** [comment]
Could you post the output of:
```python
import IPython

IPython.get_ipython().kernel.config['IPKernelApp']['connection_file']
```

**Comment by JosephKarpinski** [comment]
That fixed it!

Please close the issue.

Thank you!

Joseph Karpinski
