### ISSUE TITLE
[BUG] Imviz: imviz.show_in_sidecar() does not display under VSCode

### ISSUE THREAD

**Issue by JosephKarpinski** [spacetelescope/jdaviz#1545]
**Describe the bug**
 imviz.show_in_sidecar() does not display under VSCode

Works under Jupyter

**To Reproduce**
1. imviz = Imviz()
   imviz.show_in_sidecar()
2. imviz.load_data(file_090, data_label='F090W')
imviz.load_data(file_187, data_label='F187W')
imviz.load_data(file_356, data_label='F356W')
imviz.load_data(file_440, data_label='F440W')
imviz.load_data(file_770, data_label='F770W')
imviz.load_data(file_1130, data_label='F1130W')
imviz.load_data(file_1800, data_label='F1800W')

**Expected behavior**
GUI displays

**Screenshots**

<img width="1702" alt="Screen Shot 2022-08-05 at 10 26 14 AM" src="https://user-images.githubusercontent.com/37123616/183101733-cac0d5e7-b81e-410f-92ae-a3014bfbdb5c.png">

<img width="1193" alt="Screen Shot 2022-08-05 at 10 25 27 AM" src="https://user-images.githubusercontent.com/37123616/183101947-0b5611e1-55d0-42aa-b0b1-36369e6da2bd.png">

**Desktop (please complete the following information):**
 - 
<img width="591" alt="Screen Shot 2022-08-05 at 10 42 43 AM" src="https://user-images.githubusercontent.com/37123616/183101488-7c1f1ac2-17a5-4df0-949e-a561a14f95d0.png">

 - Browser: [safari 22]
 - Jupyter: [run "jupyter --version"]
 - IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : 0.5.13
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0

**Package versions (please complete the following information):**

macOS-11.6-x86_64-i386-64bit
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00) 
[Clang 13.0.1 ]
Numpy 1.23.1
astropy 5.1
matplotlib 3.5.2
scipy 1.9.0
scikit-image 0.19.3
asdf 2.12.0
gwcs 0.18.1
regions 0.6
specutils 1.7.0
photutils 1.5.0
pyyaml 6.0
click 8.1.3
asteval 0.9.27
idna 3.3
traitlets 5.3.0
bqplot 0.12.33
bqplot-image-gl 1.4.10
glue-core 1.5.0
glue-jupyter 0.12.1
glue-astronomy 0.4.0
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.2
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.3.6
vispy 0.11.0
sidecar 0.5.1
Jdaviz 2.8.0

**Additional context (e.g. data files)**

**Comment by pllim** [comment]
I don't think we ever promised Jdaviz would work under VSCode. It is a product meant to be used with Jupyter Notebook or Lab.

**Comment by duytnguyendtn** [comment]
`inline` displays DO work in VSCode, at least from my experience. @JosephKarpinski it looks like you're using an older version of `jdaviz`, as `show_in_sidecar` is currently in the process of being deprecated with `show(loc="sidecar").

To display jdaviz "inline", in the newest version, you can either call `viz.show(loc="inline")` or simply `viz.show()`
