### ISSUE TITLE
jdaviz install failure Ubuntu linux compilation error with synphot

### ISSUE THREAD

**Issue by cfbradshaw** [spacetelescope/jdaviz#1563]
When installing jdaviz, I get the following: Failed to build synphot casa-formats-io
ERROR: Could not build wheels for synphot, casa-formats-io, which is required to install pyproject.toml-based projects
fatal error: Python.h: No such file or directory
I'm working in a virtual environment with python 3.10.6 and pip 22.2.2

**Comment by pllim** [comment]
Jdaviz should not be pulling in `synphot` at all. How are you trying to install Jdaviz and in what env?

**Comment by pllim** [comment]
`Python.h: No such file or directory` -- Definitely tell me how your Python env is set up, please.

**Comment by cfbradshaw** [comment]
Using the instructions provided e.g., pip install jdaviz --upgrade

**Comment by pllim** [comment]
But how was your Python installed? What shows when you type `which pip`? What is your `pip freeze`?

**Comment by cfbradshaw** [comment]
As is said initially, python 3.10.6 and pip 22.2.2

**Comment by pllim** [comment]
What shows when you type `which pip`? What is your `pip freeze`? Thanks!

**Comment by cfbradshaw** [comment]
Sorry!  I'm not at my desktop and will need to get back to it Sunday evening.  I did not do a pip freeze.  Thanks!

**Comment by kecnry** [comment]
The Python.h error usually suggests that you don't have the development version of python installed which includes those headers and are likely needed to build C-extensions for some of the dependencies listed in the error statement.  I think conda environments automatically install the development version of python, but virtual environment may not.  You can install the development headers manually from your package manager (which on ubuntu can be done with `sudo apt-get install python3-dev`).

**Comment by cfbradshaw** [comment]
I will do that asap.  You are correct  that I did not install python3-dev?  However, does apt-get install python 3.10?  I had to use deadsnakes to go past python 3.8, which is the Ubuntu repo version.  The reason I updated to 3.10, was that I had issues with the notebooks in the jdavis repository.

**Comment by kecnry** [comment]
I am not familiar with using the deadsnakes ppa, but if you [instructions like these](https://gist.github.com/plembo/6bc141a150cff0369574ce0b0a92f5e7#installation-procedure), it looks like there is a corresponding development version available that will hopefully do the trick.

**Comment by pllim** [comment]
I know glue-astronomy (which Jdaviz depends on) pulls in casa-formats-io. But I am still very surprised that something is trying to install synphot. The latter definitely has C-extension.

If you cannot get this working on system Python, do consider Miniconda.

**Comment by cfbradshaw** [comment]
Will do! Thanks

**Comment by cfbradshaw** [comment]
> The Python.h error usually suggests that you don't have the development version of python installed which includes those headers and are likely needed to build C-extensions for some of the dependencies listed in the error statement. I think conda environments automatically install the development version of python, but virtual environment may not. You can install the development headers manually from your package manager (which on ubuntu can be done with `sudo apt-get install python3-dev`).

I've updated Ubuntu from 20.04 to 22.04, which gives me python 3.9.  I created a venv for jdaviz and tried to install the package with pip.  I got the following error: casa_formats_io/_casa_chunking.c:3:10: fatal error: Python.h: No such file or directory
          3 | #include <Python.h>
Still looking for the same include file, but for a different program.  
The pip freeze command shows: (jdaviz) charlie@charlie-Precision-3650-Tower:~/Documents/JWST_project/jdaviz$ pip freeze
packaging==21.3
pyparsing==3.0.9
setuptools-scm==7.0.5
tomli==2.0.1
typing_extensions==4.3.0

All is in the active jdaviz environment.

**Comment by cfbradshaw** [comment]
Finally got jdviz installed.  In the environment, the command sudo apt-get install python3.10 python-dev python3.10-dev build-essential worked.  I needed to specify the python version.  Sometimes I learn more than I forget.  Thanks all!

**Comment by cfbradshaw** [comment]
However, that result is from python3 -V and pip -V.
