### ISSUE TITLE
cubeviz.specviz.get_spectra() has cryptic warning

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1584]
```python 
>>> spectral_subsets = cubeviz.specviz.get_spectra()
jdaviz/jdaviz/configs/specviz/helper.py:63: UserWarning:
Applying the value from the redshift slider to the output spectra.
To avoid seeing this warning, explicitly set the apply_slider_redshift argument to True or False.
  warnings.warn("Applying the value from the redshift "
```

But setting this does not work:
```python
cubeviz.specviz.apply_slider_redshift = False
```

**Comment by kecnry** [comment]
It means as an argument to the method, but an attribute. But we should at least clarify that by saying "pass" instead of "set" and/or give an example.

**Comment by pllim** [comment]
Ahhh... but in my case, I didn't even touch the redshift slider. Redshift is probably zero. Does this warning even apply?

**Comment by pllim** [comment]
argument -> keyword option

**Comment by kecnry** [comment]
We could add another check to only trigger the warning if the slider redshift is different than the original `Spectrum1D` redshift (but I don't think a check on zero is general enough).

**Comment by pllim** [comment]
I opened #1588 to clarify the wording. I don't know all the gotchas in Specviz/Cubeviz/Mosviz enough to also check spectra redshift. That can be future work if real users bring it up, as opposed to just me.
