### ISSUE TITLE
cubeviz contour overlay notebook error "HTTPError: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by cfbradshaw** [spacetelescope/jdaviz#1590]
Loading data to view with the commands:
BoxPath='https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/cube_fitting/Q3D_20200407/'
fname='Q3D_NRS_491_s3d.fits'

gives an error "HTTPError: HTTP Error 403: Forbidden". Is the URL correct or are permissions required.  If the second, how do I get permissions.

**Comment by pllim** [comment]
Can you please explain exactly how you are trying to load?

**Comment by cfbradshaw** [comment]
I'm executing the notebook command.

BoxPath='
https://data.science.stsci.edu/JWST/jwst-data_analysis_tools/cube_fitting/Q3D_20200407/
'
fname='Q3D_NRS_491_s3d.fits'
filename=BoxPath+fname
hdul1=fits.open(filename)
hdul1.info()

with fits.open(filename, memmap=False) as hdulist:
    sci = hdulist["SCI"].data

**Comment by cfbradshaw** [comment]
When I follow the URL link, I get:

{"message":"Missing Authentication Token"}

**Comment by pllim** [comment]
Hello again. Where/who did you get this notebook from?

**Comment by cfbradshaw** [comment]
At this site: https://github.com/spacetelescope/jdaviz/blob/main/notebooks/concepts/cubeviz_contour_overlay.ipynb
I still have the issue, but other locations in other notebooks work fine.

**Comment by pllim** [comment]
Ah, the concept notebooks were created to prove a concept. They are not guaranteed to be up-to-date as the codebase moves forward. 

Looks like @PatrickOgle originally added it in #127 , so hopefully he could clarify.

**Comment by cfbradshaw** [comment]
I worked around the issue by downloading manga-7495-12704-LOGCUBE.fits and changing the location.  I never found out why the original error.  I do have a MAST token, but likely the link is OBE.  I think that this can be closed.

**Comment by cfbradshaw** [comment]
from the github site under notebooks/concepts
