### ISSUE TITLE
Have cubeviz (and  mosviz) use the specviz profile viewer

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#160]
Discussed in more detail in https://github.com/spacetelescope/jdaviz/pull/149#discussion_r439103887 - the gist is we agree the cubeviz/mosviz 1d spectrum panel should be the same.  #149 *may* end up just doing this, but a follow-on PR might be necessary if it's not easy to do in #149

**Comment by rosteen** [comment]
This is implemented, closing.
