### ISSUE TITLE
Remove vue_relayout if possible

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1720]
As brought up by @maartenbreddels in [this comment](https://github.com/spacetelescope/jdaviz/issues/1664#issuecomment-1274779034), our `vue_relayout` function is causing a ton of messages between the front end and back end, just changing the height to 99% to and back to 100% to trigger some bqplot update. It's likely that this was an old hacky workaround that is no longer needed - we need to investigate and see if we can safely remove this function.

[🐱](https://jira.stsci.edu/browse/JDAT-2839)

**Comment by rosteen** [comment]
I investigated this briefly today, and it seems that the `g-viewer-tab` element is the only one that really needs this. Removing the `relayout` call from that element led to the x-axes of the plots being cut off in the app. Removing it from the top-level `splitpanes` element and from the state callback in `app.py` didn't seem to negatively affect the app, but I did not test super extensively.

**Comment by maartenbreddels** [comment]
would https://github.com/bqplot/bqplot/pull/1531 also fix that last issue? could you test that? that would be an extra reason for merging that PR (or solving that issue in a different way)

**Comment by pllim** [comment]
#1777 is merged. Can we close this or is this also waiting for https://github.com/bqplot/bqplot/pull/1531 ?

**Comment by pllim** [comment]
The original issue is resolved. I opened #1782 to follow up with the bqplot stuff. Thanks!
