### ISSUE TITLE
SpecViz does not plot multiple spectra in the viewer

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#173]
SpecViz does not plot multiple spectra in the viewer even if multiple spectra are selected in the data drop down. I am unsure if this is still true if both spectra are using the same units.

**Comment by nmearl** [comment]
Data has to have their axes linked to be shown on the same plot. For example, doing a smoothing operation on a spectrum will display the new spectrum in the same plot because their axes are linked.

**Comment by rosteen** [comment]
Haven't seen anyone complain about this in the last year, I think it's working as expected. Closing.
