### ISSUE TITLE
Remove big GIFs from repo

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/jdaviz#1744]
In reviewing #1743, I noticed that our Zenodo ZIP archive weighs in at 179 MB. That's huge! 

Most of the bulk is coming from some GIFs that we include in the repo here:
```bash
$ du -hs docs/img/landing_gifs
170M	docs/img/landing_gifs

$ du -hs docs/img/landing_gifs/*
 20M	docs/img/landing_gifs/Cubeviz_landing.gif
 93M	docs/img/landing_gifs/Imviz_landing.gif
 36M	docs/img/landing_gifs/Mosviz_landing.gif
 22M	docs/img/landing_gifs/Specviz_landing.gif
```

Would anybody object to hosting these few files on Box? We could make a shared folder that all of the code owners have access to. If not, I'm happy to put a PR together.

**Comment by pllim** [comment]
We discussed this before and I think I even suggested converting these GIFs as proper videos, upload to YouTube, and embed those instead but I forgot what was the objections or why we kept the status quo.

Keep in mind that removing these now do not remove them from history, but hopefully at least would reduce the Zenodo size going forward.
