### ISSUE TITLE
Make methods to introspect the viewer (and subset?) names in an application

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#175]
This issue was initially prompted by https://github.com/spacetelescope/jdaviz/pull/159#discussion_r445825523 but is a bit broader so I'm making it a separate issue.

Basically, the issue here is that all of the convenient data accessors in `jdaviz.Application` depend on knowing the name of the viewers in the configuration file. This is not desirable because it's not really easily visible to the user, and we *do* want users to be able to use these APIs for accessing data.  So there needs to be a way for a user to ask "what are all the viewers in this app".

I think the most natural way to do this is to simply add a `get_viewer_names` method to `Application`?  It would then just return a list of all the relevant names that go into the various `get_<something>_from_viewer` references.

At the same time it probably makes sense to add a similar set of methods for *subset* names.  This is less critical since the user can by-eye see them in the UI, but it's useful for writing code that does something over all of the subsets (and would be applied in combination with the dicts that come out of #159 and #161).

**Comment by pllim** [comment]
Ops... Didn't see this until after I created #643. Since that one has a JIRA ticket attached to it, I am closing this as duplicate. Sorry!
