### ISSUE TITLE
[BUG] Imviz: Laggy performance of Contrast/Bias sliders

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#1775]
This is probably an upstream fix, but I posted it here since (1) Not sure where upstream the effort should be posted and (2) This issue was found in context of jdaviz

After investigating the contrast bias slider performance, very little of the runtime could be attributed to `jdaviz`. Good news for us, but it drastically elevates the difficulty of trying to fix it. My opinion is this task is sufficiently "in the weeds" to be sent to the SMEs

I've attached the profiling artifact from the following code snippet:

```
def test():
    for i in range(0,1):
        val = np.random.randint(0,100)
        imviz.plugins['Plot Options']._obj.image_bias_value = val/100
        imviz.plugins['Plot Options']._obj.image_contrast_value = (1.0 - val/100)*4
%prun -D set_contrast_bias_slider.prof test() 
```

NOTICE: The above code snippet sets the underlying bias and contrast values directly, as opposed to going through the plugin API to best simulate the user interacting with the UI. 

After the fix of https://github.com/glue-viz/glue-jupyter/pull/325, largely the performance can be traced down to `composite_array`. Based on the profiling, it looks like we aren't calling composite_array multiple times, just once per contrast/bias call

The following is a snakeviz visualization of the attached profiling artifact: https://stsci.box.com/s/fmvelp26ls23dx23z9sihf6fmgv2xfdm. One can produce this graph by running:

```
snakeviz set_contrast_bias_slider.prof
```

![image](https://user-images.githubusercontent.com/25206008/198098427-d35b8173-6d68-45b7-ac40-16e3e6786d18.png)

<details>

<summary> Old profiling before https://github.com/glue-viz/glue-jupyter/pull/325 </summary>

![image](https://user-images.githubusercontent.com/25206008/197806660-01da6b24-f9dc-4624-a17e-dd2cf5f20e77.png)

Very quickly after running the code, the execution time gets split between traitlets (99.44%) and ipywidgets (67.29%). I suspect there is some multithreading happening here (hence why the percentages don't add up to 100%?)

The actual logic to set the contrast/bias (boxed in red below) is actually only 25% of the total runtime. To be fair, calling the underlying glue `composite_array` is one of the most "inefficient" lines of code according to the profiler, but overall takes little time:

![image](https://user-images.githubusercontent.com/25206008/197806741-67c05931-09d2-450c-8fc7-6c151db1fdcc.png)

A reasonable conclusion may be to observe the many `notify_all` methods being called and conclude perhaps we are oversubscribing to a state change somewhere? After debugging in my IDE, I could not find a huge list of callables that needed to be notified; rather this appears to be a large cascade of linked notifications that are being broadcasted.

</details>

**Comment by duytnguyendtn** [comment]
As suggested by @kecnry, I reran these tests on glue-jupyter main to include https://github.com/glue-viz/glue-jupyter/pull/325. Good news is the messaging calls have indeed sped up tremendously, resulting in a 50% performance increase compared to when I last ran these tests:

![image](https://user-images.githubusercontent.com/25206008/198080175-bd9b0b76-46ec-40e6-8b43-3f36e67b86ce.png)

At this point, the limiting factor is the call to `composite_array`. For what it's worth, I'm getting one call to composite_array for each contrast/bias change.

**Comment by pllim** [comment]
Is 50% increase good enough? If it is, maybe we can stop digging in this rabbit hole and move on to something else.

**Comment by duytnguyendtn** [comment]
@pllim I believe @kecnry profiled other parts of jdaviz and found slowdowns in `composite_array` as well. Nominally, if it was just this isolated, I'd agree, but since there are already other points that are slowed down by `composite_array` we should probably see if anything could be done

**Comment by astrofrog** [comment]
@duytnguyendtn - just to check, how many images do you have open in imviz when doing the profiling?

**Comment by duytnguyendtn** [comment]
Hi @astrofrog ! I ran these benchmarks both against a single file; a few times against one data file from our ImvizDitheredExample notebook, as well against a 16k randomly generated numpy array, with similar results

**Comment by pllim** [comment]
> against a 16k randomly generated numpy array

You mean you loaded 16k images or just one image with 16k pixels?

**Comment by astrofrog** [comment]
@duytnguyendtn could you try out https://github.com/glue-viz/glue/pull/2343 along with the latest developer version of astropy to see if you get any performance improvements and whether anything is broken/doesn't look right?

It would be great if you could also test the case of opening multiple images in imviz to see if that is improved too.

**Comment by duytnguyendtn** [comment]
> 16k images

Definitely not 😅 

Fantastic Tom! I'll test soon!

**Comment by astrofrog** [comment]
@duytnguyendtn - does this still need work or is the current state of things good enough?

**Comment by pllim** [comment]
Hmm I think at some point we introduce some sort of delay or something and never heard complain since but other devs can confirm.
