### ISSUE TITLE
Consistent capitalization conventions for specviz/cubeviz/mosviz/jdaviz

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#178]
We should make the capitalization of the various tools consistent across `jdaviz`.  The following I *think* have been agreed on:

* Specviz/Mosviz/Cubeviz are all capitalized in prose, `Specviz`/`Mosviz`/`Cubeviz` as class names, and `specviz`/`mosviz`/`cubeviz` when used as attributes
* `jdaviz` as a package is lower case.
* In prose, JDAviz vs Jdaviz vs JDAViz still being debated...

We should go through and update any/all doc references for this topic, and also the helper classes will need to be re-named with the capitalization above.

cc @Jenneh @nmearl @dtn5ah @PatrickOgle @rosteen 

[🐱](https://jira.stsci.edu/browse/JDAT-1756)

**Comment by pllim** [comment]
> In prose, JDAviz vs Jdaviz vs JDAViz still being debated

How did this debate go? Which one won? I have been using "Jdaviz" myself since it is consistent with other viz spelling... 👀

**Comment by rosteen** [comment]
Pretty sure "Jdaviz" won.
