### ISSUE TITLE
[BUG] Show axes toggle only works once

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1804]
In testing to see if we can close an old issue I found that the `Show Axes` toggle only works properly the first time it is clicked (to hide the axes). That works to expand the image in an image viewer to take up the whole area, but if you then toggle the axes back on it does not resize the image in the viewer to show the axes again. You can force this to update by resizing the viewer. If you hide them again they will disappear, but this time the image will not expand to fill the whole area until you resize the viewer. 

**To Reproduce**
1. Go to Plot Options plugin in any config.
2. Toggle `Show Axes` to off. 
3. Toggle it back on, see that nothing happens.

**Comment by pllim** [comment]
If we have coordinates info panel for all the viewers, then maybe we can hide the axes for good and get rid of the toggle, then problems solved? 🤔

**Comment by javerbukh** [comment]
I was going to say this behavior sounds familiar 😂 You are closing some dinosaurs! I agree with @pllim , but I think I remember "publication ready plots" being a priority, so I'm not sure if they are removable. Toggle might be our best option, but switch the default to no axes.

**Comment by kecnry** [comment]
Related (if not a duplicate): #1671

**Comment by rosteen** [comment]
> Related (if not a duplicate): #1671

You're right, totally a duplicate. My search-fu failed me. I'll close this and copy a bit of detail over to that issue.
