### ISSUE TITLE
[BUG] Imviz: deprecation warning from glue-core v1.6

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/jdaviz#1818]
I'm testing the latest glue-core release for jdaviz. 

Running the simple Imviz example below:
```python
from astroquery.mast import Observations
from jdaviz import Imviz
import tempfile

data_dir = tempfile.gettempdir()
fn = "jw02727-o002_t062_nircam_clear-f090w_i2d.fits"
uri = f"mast:JWST/product/{fn}"
path = f"{data_dir}/{fn}"
result = Observations.download_file(uri, local_path=path, cache=True)

im = Imviz()

im.load_data(path)
```
produces the following warnings:
```
2022-11-03 10:55:38,690 - stpipe - WARNING - /Users/bmmorris/miniconda3/envs/jdaviz/lib/python3.9/site-packages/glue/viewers/common/viewer.py:186: UserWarning: Add large data set?
  warnings.warn(message)

2022-11-03 10:55:39,088 - stpipe - WARNING - /Users/bmmorris/miniconda3/envs/jdaviz/lib/python3.9/site-packages/glue/viewers/image/composite_array.py:72: UserWarning: Setting colormap using "color" key is deprecated, use "cmap" instead.
  warnings.warn('Setting colormap using "color" key is deprecated, use "cmap" instead.', UserWarning)

2022-11-03 10:55:39,091 - stpipe - WARNING - /Users/bmmorris/miniconda3/envs/jdaviz/lib/python3.9/site-packages/glue/viewers/image/composite_array.py:72: UserWarning: Setting colormap using "color" key is deprecated, use "cmap" instead.
  warnings.warn('Setting colormap using "color" key is deprecated, use "cmap" instead.', UserWarning)
```
It looks like the latter warning came from https://github.com/glue-viz/glue/pull/2343.

**Expected behavior**
Fewer warnings, if possible.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome v106
 - Jupyter:
```
IPython          : 8.5.0
ipykernel        : 6.15.3
ipywidgets       : 7.7.2
jupyter_client   : 7.3.5
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.7
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.5.0
notebook         : 6.4.12
qtconsole        : 5.3.2
traitlets        : 5.4.0
```

**Comment by pllim** [comment]
Why didn't we catch it in devdeps?

https://github.com/spacetelescope/jdaviz/blob/1a0c8461cd5466e25fd650e9dc9abcdeaa111038/tox.ini#L51

Why is the warning coming from `stpipe`? If you uninstall `stpipe`, does it go away?

**Comment by bmorris3** [comment]
Ah, after investigating a bit more, I found that the warning stems from glue-jupyter v0.14.1. Upgrading to glue-jupyter v0.14.2 resolves the warning. No issues here if you simultaneously upgrade glue-core and glue-jupyter. 😅

**Comment by pllim** [comment]
😌

**Comment by pllim** [comment]
A grep for `color` in Jdaviz still give many matches, so if you see this again in other places, please open a new issue!

**Comment by kecnry** [comment]
now that glue 1.6 is out, should we pin glue >= 1.6 and glue-jupyter >= 0.14.2 to ensure the composite array speedups and that this conflict can't happen?

**Comment by pllim** [comment]
Why do I have deja vu that we talked about this before? Ah yes, didn't you say you were going to open PR with those pins? 😆
