### ISSUE TITLE
[BUG] Cubeviz: Can't add new subsets after Model Fitting

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#1853]
To reproduce: fit a model using the Model Fitting plugin, then try to create a new subset in any of the viewers. It seems like you're locked out of creating new subsets. Specviz works fine, this seems to be Cubeviz specific.

**Comment by kecnry** [comment]
I'm not seeing that exactly, but am seeing some weird behavior (multiple subsets created simultaneously, highlighting not showing up, etc)... even after creating a Linear1D model to a single spectral subset.
