### ISSUE TITLE
MNT: Unpin setuptools when RTD can build without astropy.convolution error

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1863]
Revert https://github.com/spacetelescope/jdaviz/pull/1861 when we can.

Related issues:

* astropy/astropy#14025
* https://github.com/numpy/numpy/issues/22623
* https://github.com/pypa/setuptools/issues/3693

**Comment by pllim** [comment]
No, we have not.

https://github.com/spacetelescope/jdaviz/blob/bcc29e7ce5889637a79fccc8385f9b2b6d0ea9b1/setup.cfg#L59-L60

**Comment by ojustino** [comment]
Looks like I checked `main` on your fork instead of the real upstream. Sorry for the false alarm

**Comment by pllim** [comment]
Upstream might have been fixed though if you want to open a PR to unpin it. I just haven't gotten to it yet.
