### ISSUE TITLE
Upstream bug for py3.11: pin astroquery minversion?

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/jdaviz#1865]
In numpy dev for Python 3.11, they've deprecated [a specific use of `np.genfromtxt`](https://github.com/numpy/numpy/blob/v1.23.0/numpy/lib/npyio.py#L2285-L2291). Imviz's SDSS catalog search feature relies on astroquery, and the installed astroquery version on a particular GitHub Actions test node seems to have an old version of astroquery which calls `np.genfromtxt`. It's worth noting that the current astroquery repo [does not use genfromtxt anywhere](https://github.com/astropy/astroquery/search?q=genfromtxt), so this issue might go away if we pin a minversion for astroquery.

I ran into this in a devdeps test ([log](https://github.com/spacetelescope/jdaviz/actions/runs/3525766634/jobs/5912891114)) in #1834, where an Imviz test calls `SDSS.query_region` [here](https://github.com/spacetelescope/jdaviz/blob/main/jdaviz/configs/imviz/plugins/catalogs/catalogs.py#L133-L134).

Since [astroquery doesn't test against 3.11 yet](https://github.com/astropy/astroquery/blob/main/tox.ini#L3), this might be the first someone has seen the issue, so I'm sharing here.

**Comment by pllim** [comment]
If you seeing this in devdeps and it is already fixed in astroquery dev, then we can specify in tox.ini to install astroquery from source.

https://github.com/spacetelescope/jdaviz/blob/bcc29e7ce5889637a79fccc8385f9b2b6d0ea9b1/tox.ini#L42

**Comment by pllim** [comment]
I haven't come across this since this was reported, so I am closing this as won't fix.
