### ISSUE TITLE
Bump ASDF pin after latest release

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/jdaviz#1925]
`asdf-transform-schemas==0.2.2` has produced a reoccurring issue when opening ASDF files from `jwst`. For example, see discussion in: #1763. 

Rather than adding a new version dependency to curate to our `setup.cfg`, we can pin the next release of `asdf` after asdf-format/asdf#1278 gets merged, which will pin the appropriate minversion of `asdf-transform-schemas`. We already pin `asdf` here, we just need to update the number after release:

https://github.com/spacetelescope/jdaviz/blob/46f0ae26605c2844716e472ae5234adfb1ea3ffa/setup.cfg#L45

**Comment by pllim** [comment]
I haven't seen a new release upstream yet as of 2022-12-16.

**Comment by bmorris3** [comment]
Yep. The pre-release updates have been merged in asdf-format/asdf#1275, I believe @WilliamJamieson is on it.

**Comment by WilliamJamieson** [comment]
We ran into a snag in regression testing with JWST... Hopefully its fixed now, the regression tests are re-running now.
