### ISSUE TITLE
Jupyter kernel comm crashing when computer is left on sleep

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#1977]
**Describe the bug**
Python kernel comm is crashing when left active while computer goes into sleep/hibernate mode. This particular example happened when the computer was left plugged in with the screen closed overnight.

**To Reproduce**
1. Run jupyter-lab (might only be a lab bug)
2. Close the laptop
3. Leave it for a few hours
4. Return and see this:

**Screenshots**
<img width="1364" alt="Screen Shot 2023-01-24 at 9 42 47 AM" src="https://user-images.githubusercontent.com/7179333/214353409-9ac2639f-1c36-444e-8f6b-1da621ff905e.png">

<img width="1138" alt="Screen Shot 2023-01-24 at 9 43 52 AM" src="https://user-images.githubusercontent.com/7179333/214353451-49ef937a-1170-42f5-ac7e-920547778690.png">

**Expected behavior**
The expected behavior is that the kernel runs just the same as when you first start it up.

**Desktop (please complete the following information):**
 - OS: MacOS Montery 12.5.1
 - Browser: chrome
 - Jupyter: jupyter-lab

**Package versions (please complete the following information):**

macOS-10.16-x86_64-i386-64bit
Python 3.9.15 (main, Nov 24 2022, 08:29:02) 
[Clang 14.0.6 ]
Numpy 1.24.1
astropy 5.2.1
matplotlib 3.6.3
scipy 1.10.0
scikit-image 0.19.3
asdf 2.14.3
gwcs 0.18.3
regions 0.7
specutils 1.9.1
specreduce 1.3.0
photutils 1.6.0
astroquery 0.4.6
pyyaml 6.0
asteval 0.9.28
idna 3.4
traitlets 5.8.1
bqplot 0.12.36
bqplot-image-gl 1.4.11
glue-core 1.6.0
glue-jupyter 0.15.0
glue-astronomy 0.5.1
echo 0.8.0
ipyvue 1.8.0
ipyvuetify 1.8.4
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.3.6
vispy 0.12.1
sidecar 0.5.2
Jdaviz 3.2.dev232+gffd343e0

**Additional context (e.g. data files)**

**Comment by maartenbreddels** [comment]
This is fixed in https://github.com/jupyter-widgets/ipywidgets/pull/3687 and released with [ipywidgets 7.7.3](https://pypi.org/project/ipywidgets/7.7.3/)

**Comment by kecnry** [comment]
Should we update the pin or is this not crucial enough and should just close as-is?

**Comment by maartenbreddels** [comment]
I'm ok with both :)
I'd personally leave it as it, since it's so rare to happen.

**Comment by pllim** [comment]
@javerbukh should confirm first, no?

**Comment by javerbukh** [comment]
Confirmed that this is no longer an issue, thank you!
