### ISSUE TITLE
Model Fitting plugin should have option for disabling file save

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#198]
The Model Fitting plugin currently has an option for saving the model fit to a pickle file in the directory location of the Voila server / notebook.  For ASB this would save the file on a remote web server.  For web embeds of the application, these features need an option to disable the "File Save" functionality.  Alternatively, the save to file button could be a prompt to save the file on the users' local system.  

This is a good example highlighting the requirement that plugins containing file IO need to also have an option to disable this feature on the web, or convert it to a local file save prompt.

**Comment by rosteen** [comment]
We removed the save button in #485 , closing.
