### ISSUE TITLE
[BUG] Jupyter-lab viewer window does not open

### ISSUE THREAD

**Issue by oyk100** [spacetelescope/jdaviz#1990]
### Jdaviz component

Imviz

### Description

When I run the code listed below in my Jupyter-lab viewer window does not open. No errors were reported.  The same with Specviz.  

from jdaviz import Imviz
import matplotlib.pyplot as plt
import numpy as np

imviz = Imviz()
imviz.load_data("/Users/kargaltsev/Dropbox/Public/jw01478-o014_t003_nircam_clear-f277w_i2d.fits")

### How to Reproduce

I suspect you need my laptop to reproduce it. 

### Jupyter

❯ jupyter --version
Selected Jupyter core packages...
IPython          : 8.8.0
ipykernel        : 6.17.1
ipywidgets       : 7.7.2
jupyter_client   : 7.4.9
jupyter_core     : 5.1.3
jupyter_server   : 1.23.5
jupyterlab       : 3.5.2
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : 5.4.0
traitlets        : 5.8.1

❯ jupyter-lab --version
3.5.2

### Software versions

macOS-12.5.1-x86_64-i386-64bit
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37) 
[Clang 14.0.6 ]
Numpy 1.24.1
astropy 5.2.1
matplotlib 3.6.3
scipy 1.10.0
scikit-image 0.19.3
asdf 2.14.3
gwcs 0.18.3
regions 0.7
specutils 1.9.1
specreduce 1.3.0
photutils 1.6.0
astroquery 0.4.6
pyyaml 6.0
asteval 0.9.28
idna 3.4
traitlets 5.8.1
bqplot 0.12.36
bqplot-image-gl 1.4.11
glue-core 1.6.0
glue-jupyter 0.15.0
glue-astronomy 0.5.1
echo 0.8.0
ipyvue 1.8.0
ipyvuetify 1.8.4
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.3.6
vispy 0.12.1
sidecar 0.5.2
Jdaviz 3.2.0

**Comment by kecnry** [comment]
Can you try `imviz.show()` after `imviz.load_data(...)`?

**Comment by pllim** [comment]
@oyk100 , did the suggestion above solve your problem?

**Comment by oyk100** [comment]
The only output is

Application(config='imviz', events=['call_viewer_method',
'close_snackbar_message', 'data_item_remove', 'data_…

There is no window with the plot.

Oleg

**Comment by pllim** [comment]
If that still does not work , try a different browser (you did not say which browser you were using).

**Comment by oyk100** [comment]
I tried both Chrome (107.0.5304.121 (Official Build) (arm64)) and Firefox
(108.0.1 (64-bit)). The same outcome (see my previous e-mail).

My laptop is Mackbook Pro 2021, Apple M1 Pro, OS Monterey 12.5.1

Oleg

**Comment by pllim** [comment]
Some users might have seen this problem in the past but it went away when they created a fresh conda environment. Can you please try the following and see?

First, make sure you are back in `base` env. You might have to call it a few times (if you have stacked envs) until `conda env list` shows you are in `base`.
```
conda deactivate
```

Then create a fresh env.
```
conda create -n jdaviz20230207 python=3.9
```

Once that is done, go to the new env.
```
conda activate jdaviz20230207
```

Make sure your `pip` is tied to that env. When you run this command, the path should say something like `envs/jdaviz20230207/bin/pip`.
```
which pip
```

Now install the latest Jdaviz in this new env.
```
pip install jdaviz
```

Remember to quit any existing Jupyter server or Python session that is still running. Make sure you are still in this new env, then run Jdaviz. Is the problem gone?
