### ISSUE TITLE
Spectrum1D glue data translator needs to handle uncertainty and mask

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/jdaviz#200]
When implementing code to support plotting of errors and masks in specviz, we found that the glue data translator `Specutils1DHandler` doesn't handle any array attribute besides the flux array. 

It needs to handle at least the error array coming from the `uncertainty` attribute, and the mask array coming from the `mask` attribute (any need to handle more complex masks?)

This issue seems to affect other tickets currently in development in `daviz`.

**Comment by nmearl** [comment]
This is being handled in the PR to glue-astronomy: glue-viz/glue-astronomy#19.

**Comment by rosteen** [comment]
That PR is for fixing the returned mask attribute to match the convention that specutils expects, but does not currently do anything to address the need for the uncertainty attribute. I create a [follow-up issue](https://github.com/glue-viz/glue-astronomy/issues/20) in glue-astronomy about uncertainty and handling more complex masks.

**Comment by rosteen** [comment]
The glue-astronomy PR implementing this was merged, closing this issue.
