### ISSUE TITLE
Unable to install scikit-image when installing jdaviz in Python 3.11

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2016]
This is an upstream problem where stable scikit-image does not have wheel for Python 3.11. They have pre-release with Python 3.11 wheel. So to fix this problem you have to manually do this:

`pip install scikit-image --pre`

Then once that is installed successfully, you can try `pip install jdaviz` again.

Also see:

* https://github.com/scikit-image/scikit-image/issues/6517

**Comment by stefanv** [comment]
It's simply a matter of skimage not having had a 3.11 release yet. The pre-release is out now, and the main release should be out within the next week.

**Comment by pllim** [comment]
scikit-image 0.20.0 is released.
