### ISSUE TITLE
Catalogs: Use DR17 when upstream database is fixed

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2030]
Revert the DR17 -> DR16 change in #2021 when this issue below is resolved:

* https://github.com/astropy/astroquery/issues/2673

I think currently the DR17 database is unreachable.

**Comment by jobovy** [comment]
I also ran into a similar issue and reported this to SDSS. They then quickly fixed the database issue. If you notice this type of error in the future, it would probably be good to report it to SDSS at sciserver-helpdesk@jhu.edu or the general help address helpdesk@sdss.org.
