### ISSUE TITLE
Nice spectrum plot axis labels don't work in Cubeviz

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#204]
@javerbukh  implemented nice axis labels in `specviz` in [PR 191](https://github.com/spacetelescope/jdaviz/pull/191). Currently they do not work in the spectrum viewer in `cubeviz` (and presumably `mosviz`, although I haven't checked). We'd like this to be consistent throughout.

**Comment by javerbukh** [comment]
Plot axis labels appear as expected in cubeviz, closing this ticket.
