### ISSUE TITLE
Spectrum viewer data retrieval methods return different values

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#206]
@robelgeda and Tracy Beck (I can't find her github tag) noticed and were rightfully confused by the fact that currently `spectrum_viewer.data()` and `app.get_data_from_viewer("spectrum-viewer")` return different values. This is because `get_data_from_viewer()` is checking the viewer to see which statistic to use to collapse the data to a spectrum, while the `.data()` method is always using the default (mean, I believe). We should probably just change the `.data()` method to call `get_data_from_viewer()` on its own label to ensure that the values are always consistent.

**Comment by ibusko** [comment]
@rosteen what is `spectrum_viewer`? In other words, I need to have the context of the statement in your description of the bug. I understand the `app.get_data_from_viewer("spectrum-viewer")` construct since it refers to the `app` attribute explicitly. But I can't find an attribute named `spectrum_viewer`, at least not in specviz. Maybe it's a `cubeviz` attribute instead?

**Comment by rosteen** [comment]
Ah, sorry for the lack of clarity - `spectrum_viewer` here was the actual viewer object retrieved by using `app.get_viewer('spectrum-viewer')`.

**Comment by ibusko** [comment]
@rosteen apparently I am not able to reproduce the bug. I am using the manga cube under cubeviz in a notebook. I get identical spectra when using either method:

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/3577145/92478692-88360080-f1b0-11ea-8e20-3039bb62f4aa.png">

**Comment by ibusko** [comment]
was this bug detected in Tracy's notebook? Maybe I should try to use it instead.

**Comment by ibusko** [comment]
In exercising the collapse function in cubeviz, I often get it to crash with a sort of infinite loop where the spectrum window keeps flashing as I select the 'collapsed' data set for display. 

When it does work, though, the two methods are delivering the same result. When I succeed in changing the statistic in the collapse plugin and applying it, the two methods return the same values as each other. The values change as the statistic changes, as expected. So, yes, the bug doesn't seem to be present.

**Comment by rosteen** [comment]
This was resolved by #281, closing.
