### ISSUE TITLE
TST: test_register_model_with_uncertainty_weighting fails in astropy dev

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2086]
Look in the dev job:

```
FAILED jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py::
    test_register_model_with_uncertainty_weighting - assert False
 +  where False = <function allclose at ...>(0.0007063584243707317, 0.0003657, rtol=0.01)
 +    where <function allclose at ...> = np.allclose
```

@bmorris3 knows what caused this.

[🐱](https://jira.stsci.edu/browse/JDAT-3197)

**Comment by bmorris3** [comment]
This is caused by https://github.com/astropy/astropy/pull/14519. The fix is to update our expected best-fit parameter uncertainties to account for the measurement uncertainties.
