### ISSUE TITLE
axes limits do not update correctly when changing display unit

### ISSUE THREAD

**Issue by kecnry** [spacetelescope/jdaviz#2126]
When zooming in on a feature and then using https://github.com/spacetelescope/jdaviz/pull/2048 to convert x display units, the zoom limits do not react as expected.

Example to reproduce (using https://github.com/spacetelescope/jdaviz/pull/2048 and https://github.com/glue-viz/glue/pull/2379):

```
import astropy.units as u
import tempfile
from astroquery.mast import Observations
from glue.core.roi import XRangeROI
from jdaviz import Specviz

specviz = Specviz(verbosity='error', history_verbosity='debug')

data_dir = tempfile.gettempdir()
fn = "jw02732-o004_t004_miri_ch1-shortmediumlong_x1d.fits"
result = Observations.download_file(f"mast:JWST/product/{fn}", local_path=f'{data_dir}/{fn}')
specviz.load_spectrum(f'{data_dir}/{fn}', "myfile")

specviz.show()

sv = specviz.app.get_viewer('spectrum-viewer')
sv.state.x_min, sv.state.x_max = (7, 7.2)  # um
sv.state.x_display_unit = 'Angstrom'
print(sv.state.x_min, sv.state.x_max)  # expected: 7000, 7200
```

**Comment by astrofrog** [comment]
@kecnry - can you check if https://github.com/glue-viz/glue/pull/2394 fixes this?

**Comment by kecnry** [comment]
That does the trick, thanks!  I'll leave this issue open until that is in a glue release and pinned in #2127
