### ISSUE TITLE
Spectra of spatial subset always collapsed with "max"

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#214]
Currently, the spectrum corresponding to a spatial subset is always collapsed with the `max` statistic. Subsets should either use whatever statistic is selected for collapsing the parent data, or should be available in the `Viewer` tab data selection to change independently.

This would be a good opportunity to correct the label on the statistic selection as well (currently it says "x-axis").

**Comment by PatrickOgle** [comment]
Changing the collapse method in the viewer seems to change the method for both the spectrum and the subset.

**Comment by rosteen** [comment]
This ended up being my error/interpreting what I was seeing wrong, it's working fine.
