### ISSUE TITLE
specviz2d: plot spectrum in wavelength/frequency with non-linear axis

### ISSUE THREAD

**Issue by kecnry** [spacetelescope/jdaviz#2150]
#1514 forced the 1d spectrum to be plotted in pixel-space to maintain limit-syncing with the 2d spectrum until support for a non-linear x-axis on the 1d spectrum viewer could be supported.

Related: 

* #1616
* https://github.com/bqplot/bqplot/issues/1536
* https://github.com/spacetelescope/jdaviz/pull/1953#discussion_r1137560866

```[tasklist]
- [ ] bump bqplot minversion to 0.12.39
- [ ] https://github.com/glue-viz/glue/pull/2378
- [ ] https://github.com/glue-viz/glue-jupyter/pull/346
```

[:cat:](https://jira.stsci.edu/browse/JDAT-2628)

**Comment by astrofrog** [comment]
Just to check, where do we stand on this?

**Comment by kecnry** [comment]
I think we can probably consider this closed by https://github.com/spacetelescope/jdaviz/pull/2219 (abandoning the actual idea to plot with non-linear axis because of the consequences of needing to translate everything after the case)
