### ISSUE TITLE
Unexpected XOR region behavior

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#216]
This behavior seems unexpected:

1) Select region
2) Remove part of region using XOR
3) Delete subset
4) Unexpected behavior:  Subset is deleted, but new subset is created corresponding to the removed part of the region.

[🐱](https://jira.stsci.edu/browse/JDAT-835)

**Comment by PatrickOgle** [comment]
Is this reproducible?   Or is it a misunderstanding of how the tool works.

**Comment by pllim** [comment]
When I tested this a year later, a mystery subset is no longer created but it was still acting a little weird. Can you double check that glue-viz/glue-jupyter#266 completely fixes your use case? Thanks!
