### ISSUE TITLE
Supress echo warning at start of jdaviz

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#225]
Right now when jdaviz is started (either at the command line or notebook), the following warning appears:
```
/home/erik/miniconda3/envs/jdaviz-dev/lib/python3.8/site-packages/glue/external/echo/__init__.py:3: UserWarning: glue.external.echo is deprecated, import from echo directly instead
  warnings.warn('glue.external.echo is deprecated, import from echo directly instead')
```
this is coming from `glue` but looks to the user to be a `jdaviz` problem. We should either fix the issue upstream or suppress the warning in `jdaviz` if it's going to be hard to fix in the short-term.

**Comment by pllim** [comment]
+1 to suppress. Just saw this warning and it is a little annoying, especially for a new user.

**Comment by pllim** [comment]
I also see this warning in addition to the echo one:

```
.../setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools.
This usage is discouraged and may exhibit undesirable behaviors or errors.
Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
```

Not sure where it is coming from.

**Comment by pllim** [comment]
Is this still a problem?

**Comment by rosteen** [comment]
It seems to me to have been resolved, I'm going to close this. I often get an annoying amount of warnings still, but not this specific one.
