### ISSUE TITLE
TST: devdeps not picking up numpy 2.0.0.dev

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2259]
```
Package versions: 
Numpy: 1.25.0
Scipy: 1.12.0.dev0+1177.dbc2d3a
```

I think `bqplot` is being unreasonable: `bqplot 0.12.39 requires numpy<2.0.0,>=1.10.4, but you have numpy 2.0.0.dev0 which is incompatible.`

@maartenbreddels , is there any plans for bqplot 0.12.x branch to be compatible with numpy 2.0?

**Comment by maartenbreddels** [comment]
I will try to undo that pin, I think we (bqplot) should not pin this aggressively, only after we notice an incompatibility.
