### ISSUE TITLE
[BUG] Jupyter Notebooks Failing with 500 : Internal Server Error

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/jdaviz#2289]
### Jdaviz component

Other (explain in Description below)

### Description

When I tried to run https://github.com/spacetelescope/jdaviz/blob/main/notebooks/concepts/imviz_roman_asdf.ipynb in Jupyter Notebook 6.5.4, I get an error:

500 : Internal Server Error

The fix for this is to have nbconvert library 7.x or greater, but neither the notebook or jupyter notebooks pin that (they just had an install of 6.x). I do not know which needs the tag, but I figured I would start here. I learned the solution from:
https://github.com/jupyter/notebook/issues/6531

### How to Reproduce

1. Get package from 'https://github.com/spacetelescope/jdaviz/blob/main/notebooks/concepts/imviz_roman_asdf.ipynb ' and install jupyter notebook through anaconda navigator in a new conda environment.
2. Then run 'jupyter notebook in navigator' and open the downloaded notebook.
3. An error occurs.

### Expected behavior

The notebook to open and work.

### Browser

Chrome

### Jupyter

jupyter --version

>jupyter --version
Selected Jupyter core packages...

IPython          : 8.12.0
ipykernel        : 6.24.0
ipywidgets       : 8.0.7
jupyter_client   : 7.4.1
jupyter_core     : 5.3.0
jupyter_server   : 1.24.0
jupyterlab       : 3.6.5
nbclient         : 0.5.13
nbconvert        : 7.6.0
nbformat         : 5.7.0
notebook         : 6.5.4
qtconsole        : 5.4.3
traitlets        : 5.7.1

### Software versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("Numpy", numpy.__version__)
import astropy; print("astropy", astropy.__version__)
import matplotlib; print("matplotlib", matplotlib.__version__)
import scipy; print("scipy", scipy.__version__)
import skimage; print("scikit-image", skimage.__version__)
import asdf; print("asdf", asdf.__version__)
import stdatamodels; print("stdatamodels", stdatamodels.__version__)
import gwcs; print("gwcs", gwcs.__version__)
import regions; print("regions", regions.__version__)
import specutils; print("specutils", specutils.__version__)
import specreduce; print("specreduce", specreduce.__version__)
import photutils; print("photutils", photutils.__version__)
import astroquery; print("astroquery", astroquery.__version__)
import yaml; print("pyyaml", yaml.__version__)
import asteval; print("asteval", asteval.__version__)
import idna; print("idna", idna.__version__)
import traitlets; print("traitlets", traitlets.__version__)
import bqplot; print("bqplot", bqplot.__version__)
import bqplot_image_gl; print("bqplot-image-gl", bqplot_image_gl.__version__)
import glue; print("glue-core", glue.__version__)
import glue_jupyter; print("glue-jupyter", glue_jupyter.__version__)
import glue_astronomy; print("glue-astronomy", glue_astronomy.__version__)
import echo; print("echo", echo.__version__)
import ipyvue; print("ipyvue", ipyvue.__version__)
import ipyvuetify; print("ipyvuetify", ipyvuetify.__version__)
import ipysplitpanes; print("ipysplitpanes", ipysplitpanes.__version__)
import ipygoldenlayout; print("ipygoldenlayout", ipygoldenlayout.__version__)
import jinja2; print("Jinja2", jinja2.__version__)
import voila; print("voila", voila.__version__)
import vispy; print("vispy", vispy.__version__)
import sidecar; print("sidecar", sidecar.__version__)
import jdaviz; print("Jdaviz", jdaviz.__version__)

[🐱](https://jira.stsci.edu/browse/JDAT-3585)

**Comment by PaulHuwe** [comment]
Sure - hopefully this will go away soon with future jupyter updates.

**Comment by pllim** [comment]
@PaulHuwe , is this still a problem for you?

**Comment by PaulHuwe** [comment]
Seeing different errors now. I will close this issue and make a new one for those.

**Comment by PaulHuwe** [comment]
Sorry, just made it: #3344
