### ISSUE TITLE
'Mosviz' object has no attribute 'load_niriss_data'

### ISSUE THREAD

**Issue by xnaxe29** [spacetelescope/jdaviz#2300]
### Jdaviz component

Mosviz

### Description

Hi,

I am running the Mosviz tutorial from JWebbinar - 
https://www.youtube.com/watch?v=RCt8Kcc21_s&list=PLTOSd8OgUP5p4pRLTiVFY0kIRSw04xDP6&index=10
https://github.com/spacetelescope/jwebbinar_prep/blob/webbinar2/jdat_session/MosvizJwebbinarDemo-solutions.ipynb

This line - 
"# Load extracted data into Mosviz
mosviz.load_niriss_data(niriss_folder)"

gives the error - 'Mosviz' object has no attribute 'load_niriss_data'

Please help. Thanks.
Adarsh

### How to Reproduce

In python - 

from jdaviz import Mosviz
mosviz = Mosviz()
mosviz.app

# Download file
from astropy.utils.data import download_file
data_archive_path = download_file("https://stsci.box.com/shared/static/bij29ciuxxpb2sdhnh4j2q3np1lq9yxr.zip")
# Unzip file
import tempfile
niriss_folder = tempfile.mkdtemp()
print(niriss_folder)
from zipfile import ZipFile
with ZipFile(data_archive_path, 'r') as data_archive:
    data_archive.extractall(niriss_folder)

# Load extracted data into Mosviz
mosviz.load_niriss_data(niriss_folder)

### Expected behavior

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 # Load extracted data into Mosviz
----> 2 mosviz.load_niriss_data(niriss_folder)

AttributeError: 'Mosviz' object has no attribute 'load_niriss_data'

### Jupyter

jupyter --version 6.5.4

Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]

### Software versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("Numpy", numpy.__version__)
import astropy; print("astropy", astropy.__version__)
import matplotlib; print("matplotlib", matplotlib.__version__)
import scipy; print("scipy", scipy.__version__)
import skimage; print("scikit-image", skimage.__version__)
import asdf; print("asdf", asdf.__version__)
import stdatamodels; print("stdatamodels", stdatamodels.__version__)
import gwcs; print("gwcs", gwcs.__version__)
import regions; print("regions", regions.__version__)
import specutils; print("specutils", specutils.__version__)
import specreduce; print("specreduce", specreduce.__version__)
import photutils; print("photutils", photutils.__version__)
import astroquery; print("astroquery", astroquery.__version__)
import yaml; print("pyyaml", yaml.__version__)
import asteval; print("asteval", asteval.__version__)
import idna; print("idna", idna.__version__)
import traitlets; print("traitlets", traitlets.__version__)
import bqplot; print("bqplot", bqplot.__version__)
import bqplot_image_gl; print("bqplot-image-gl", bqplot_image_gl.__version__)
import glue; print("glue-core", glue.__version__)
import glue_jupyter; print("glue-jupyter", glue_jupyter.__version__)
import glue_astronomy; print("glue-astronomy", glue_astronomy.__version__)
import echo; print("echo", echo.__version__)
import ipyvue; print("ipyvue", ipyvue.__version__)
import ipyvuetify; print("ipyvuetify", ipyvuetify.__version__)
import ipysplitpanes; print("ipysplitpanes", ipysplitpanes.__version__)
import ipygoldenlayout; print("ipygoldenlayout", ipygoldenlayout.__version__)
import jinja2; print("Jinja2", jinja2.__version__)
import voila; print("voila", voila.__version__)
import vispy; print("vispy", vispy.__version__)
import sidecar; print("sidecar", sidecar.__version__)
import jdaviz; print("Jdaviz", jdaviz.__version__)

**Comment by pllim** [comment]
I think you are working off really old materials. Try the notebooks in the `main` branch instead. https://github.com/spacetelescope/jwebbinar_prep/tree/main

**Comment by pllim** [comment]
This API no longer exists as we refactored it some time ago. We apologize for any inconvenience caused. Thanks!
