### ISSUE TITLE
Hide x-axis labels and ticks in mosviz 2d spectrum view

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#239]
The `mosviz` view in #209 is showing some odd behavior where the 2d spectrum has odd x-axis labels.  This is due to our "tricking" of glue into thinking the 2d spectrum is a "cube".  Since the eventual goal is to transition to specutils objects, it's probably not worth a ton of effort fixing it per se.  But the temporary (or permanent?) fix (for 1.0) is to just hide the x-axis labels and ticks.  As long as the 2d and 1d spectra are linked together, it's ok to hide the x-axis since it's already present in the 1d spectrum).

**Comment by javerbukh** [comment]
Fixed by #272
