### ISSUE TITLE
Access fitting plugin model parameter maps from cubeviz helper

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#241]
This is a follow-on from #187 .  That provides a very nice plugin to fit models across a whole cube.  But what it does *not* provide is a way to easily access the resulting cube maps from the notebook (or other plugins) for further analysis by the user.

Proposed solution: add an accessor in the `Cubeviz` helper class that the #187 plugin writes into.  This could take several forms - just a raw attribute in the helper, a dictionary mapping the data name that the *original* cube was to its derived parameter maps, or some more glue-integrated approach (a la #240 ?) where the accessor is a property that uses that mechanism, etc.

**Comment by javerbukh** [comment]
@eteq Did Ivo's PR address this ticket?
