### ISSUE TITLE
[BUG] Selecting a different subset tool is broken

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#2427]
### Jdaviz component

Imviz

### Description

At least in Imviz, when I right click the circle subset select tool to select a rectangular subset instead, I get this traceback:

```
ValueError                                Traceback (most recent call last)
File ~/opt/anaconda3/envs/viz_dev/lib/python3.11/site-packages/ipyvue/VueTemplateWidget.py:60, in Events._handle_event(self, _, content, buffers)
     58     getattr(self, "vue_" + event)(data, buffers)
     59 else:
---> 60     getattr(self, "vue_" + event)(data)

File ~/projects/jdaviz/jdaviz/components/toolbar_nested.py:186, in NestedJupyterToolbar.vue_select_primary(self, args)
    184         break
    185 else:
--> 186     raise ValueError("could not find previous selection")
    188 if isinstance(self.tools[tool_id], CheckableTool):
    189     # only switch to primary if its actually checkable, otherwise
    190     # just activate once
    191     self.tools_data = {
    192         **self.tools_data,
    193         prev_id: {
   (...)
    200         }
    201     }

ValueError: could not find previous selection
```

This in on the latest `main`, I swear it was working recently but haven't rolled back yet to see when it broke.

### How to Reproduce

Select a circular subset, then try to switch to rectangular selection.

### Software versions

macOS-10.16-x86_64-i386-64bit
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
Numpy 1.25.2
astropy 5.3.2
matplotlib 3.7.2
scipy 1.11.2
scikit-image 0.21.0
asdf 2.15.1
stdatamodels 1.7.2
gwcs 0.18.3
regions 0.7
specutils 1.11.0
specreduce 1.3.0
photutils 1.9.0
astroquery 0.4.6
pyyaml 6.0.1
asteval 0.9.31
idna 3.4
traitlets 5.9.0
bqplot 0.12.40
bqplot-image-gl 1.4.11
glue-core 1.13.1
glue-jupyter 0.17.0
glue-astronomy 0.10.0
echo 0.8.0
ipyvue 1.10.0
ipyvuetify 1.8.10
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.4.3
vispy 0.13.0
sidecar 0.7.0
Jdaviz 3.6.1.dev71+gc017adb3

**Comment by rosteen** [comment]
Actually, this happens for any toolbar tool with multiple options if you try to select anything other than the default tool.

**Comment by rosteen** [comment]
Further info: In a fresh install (with Notebook 7), switching tools just fails silently without raising a traceback, which is even worse. Pip list from this env:

macOS-10.16-x86_64-i386-64bit
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
Numpy 1.25.2
astropy 5.3.2
matplotlib 3.7.2
scipy 1.11.2
scikit-image 0.21.0
asdf 2.15.1
stdatamodels 1.8.0
gwcs 0.18.3
regions 0.7
specutils 1.11.0
specreduce 1.3.0
photutils 1.9.0
astroquery 0.4.6
pyyaml 6.0.1
asteval 0.9.31
idna 3.4
traitlets 5.9.0
bqplot 0.12.40
bqplot-image-gl 1.4.11
glue-core 1.13.1
glue-jupyter 0.17.0
glue-astronomy 0.10.0
echo 0.8.0
ipyvue 1.10.0
ipyvuetify 1.8.10
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
Jinja2 3.1.2
voila 0.4.3
vispy 0.13.0
sidecar 0.7.0
Jdaviz 3.6.1.dev71+gc017adb3.d20230905

**Comment by rosteen** [comment]
I don't know why this changed but the args getting passed to `vue_select_primary` in toolbar_nested.py are messed up/no longer match what's in the tools dictionary. Casting the input `menu_ind` to an int gets past the first error, but then in the `isinstance` check below the input tool_id is something like '1' while the keys on the dict are:

```
dict_keys(['jdaviz:homezoom', 'jdaviz:prevzoom', 'jdaviz:boxzoommatch', 'jdaviz:boxzoom', 'jdaviz:panzoommatch', 'jdaviz:imagepanzoom', 'bqplot:circle', 'bqplot:rectangle', 'bqplot:ellipse', 'bqplot:circannulus', 'jdaviz:singlepixelregion', 'jdaviz:blinkonce', 'jdaviz:contrastbias', 'jdaviz:sidebar_plot', 'jdaviz:sidebar_export', 'jdaviz:sidebar_compass'])
```

I'm out of time to work on this today and have training all day tomorrow/Thursday, I can get back to it Friday if no one else has fixed it.

**Comment by pllim** [comment]
I cannot reproduce this failure but I also happen to have glue-jupyter dev installed.

```
bqplot                    0.12.40                  pypi_0    pypi
bqplot-gl                 0.0.0                    pypi_0    pypi
bqplot-image-gl           1.4.11                   pypi_0    pypi
...
glue-astronomy            0.10.0                   pypi_0    pypi
glue-core                 1.13.1                   pypi_0    pypi
glue-jupyter              0.17.1.dev100+gc98cb9d.d20230828          pypi_0    pypi
glue-qt                   0.2.0                    pypi_0    pypi
glue-vispy-viewers        1.0.7                    pypi_0    pypi
```

If the error go away when you install glue-jupyter dev, then it is time to ask upstream for a release.

**Comment by rosteen** [comment]
FWIW the new glue-jupyter release did not fix this for me.

**Comment by pllim** [comment]
Could this be a OS-dependent bug? 🤯

**Comment by pllim** [comment]
I tried creating a completely new env and also update to notebook 7 in existing env in WSL2. I just cannot reproduce this problem. And looks like Clare and Patrick might be encountering something similar but with different symptoms. Clare said the button is not responsive but no traceback. Patrick's symptoms documented in Slack.

**Comment by cshanahan1** [comment]
I am seeing the same issue but with all tools in both toolbars. https://github.com/spacetelescope/jdaviz/issues/2435 I opened a new issue since it is more general than this

**Comment by cshanahan1** [comment]
If I revert to 3.6.1 the issue goes away

**Comment by rosteen** [comment]
I'm not sure exactly what package was causing this, but installing fresh in a clean env fixed it, so I'm closing.
