### ISSUE TITLE
[FEAT] Plot Options redesign 

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#2491]
### Jdaviz component

Imviz

### What is the problem this feature will solve?

In order to implement the RGB plugin as described in tickets, a few things would need to be improved with user experience in mind. Currently, it is possible to set custom colors, opacities, etc. for each layer, but the amount of clicking and scrolling to accomplish that is excessive. This redesign seeks to prioritize features that improve UX while also addressing some tech debt. Some of these tasks could be:

1. Data renaming
2. Layer reordering (the zorder of layers matters when visualizing them as a whole)
3. Keyboard shortcuts (for changing the selected layer/viewer in a plugin using key buttons)

### Data renaming (and subset renaming) 
These have long been nice-to-haves but I think it is time to prioritize this work. There are many places in jdaviz where `data.label` is used and that will only get harder to change as we add more features.

### Layer reodering
To show that zorder matters:
zorders = [1, 2, 3, 4, 5, 6]
Red on bottom, green middle,  blue on top
![image](https://github.com/spacetelescope/jdaviz/assets/7179333/680eed07-2358-4e5b-a236-62bebe3a9d0d)

zorders = [6, 5, 4, 3, 2, 1]
Blue on bottom, green middle, red on top
![image](https://github.com/spacetelescope/jdaviz/assets/7179333/d7a6d8e1-a08c-4a17-a7f4-60474795ce98)

### Keyboard shortcuts
Being able to change the selected layer with a key press means that users can adjust layer settings without constantly having to scroll up and down in the plot options plugin. @kecnry mentioned this problem could be fixed by having the layer dropdown stick to the top even when scrolling, which could be a great solution on its own and in addition to using keyboard shortcuts.

### Sketch of redesign

I spent some time in paint trying to sketch a potential redesign of the plot options plugin that allows more intuitive layer customization. With this implementation, a user can see all layers, colors, zorder, layer names (the textbox with an "X" could be anything, including the data name), and selected layer (as shown by the blue circle).

![plot_options_redesign](https://github.com/spacetelescope/jdaviz/assets/7179333/a801bf84-d975-4e13-8399-90cb99c0cb80)

### Stretch goals

Some ideas that have been brought up include:

1. Automatically ordering and coloring layers based on the `intrument.filter` in the layer's metadata
2. Export the created image
3. Export + load color/opacity/contrast/bias values for each layer
4. Change how the `Stretch` section is laid out to incorporate some of the changes suggested to the histogram viewer

I think it's important to mention one more time that allowing time to address technical debt is crucial for implementing a design similar to what is described here. Also, we need to consider how this could work with multiselect, or if that option would be disabled. Also, we should consider how this implementation could conflict with the data dropdown. Any feedback on the points brought up here would be appreciated!

**Comment by kecnry** [comment]
I think this is a neat idea for a dedicated RGB plugin and definitely looks clean for the workflow where you're assigning colors to multiple layers simultaneously.  But I am worried about a lot of the concerns you mentioned if we were to build this directly in plot options (this essentially ignores the layer selection but only for this particular section of the plugin - although maybe that is what the blue dot indicates? - and could be a nightmare for traitlets and API design with everything else in plot options).  

Alternatively maybe this could be integrated directly into either the data menu or the legend with drag and drop reordering 🤔 but then we _really_ need to think about where renaming support might be implemented and make sure we don't corner ourselves.

The fact that ordering matters concerns me that anything we do towards RGB support won't really appease the photoshop-like experience without significant upstream improvements for multiple options to combine layers [:cat:](https://jira.stsci.edu/browse/JDAT-3590).

**Comment by pllim** [comment]
Can you please clarify again what "ordering matters" mean? Let's say we start with this:

| label | color |
| --- | --- |
| A | red |
| B | green |
| C | blue |

Are you talking about reordering like this?

| label | color |
| --- | --- |
| A | blue |
| B | green |
| C | red |

Or like this?

| label | color |
| --- | --- |
| C | blue |
| B | green |
| A | red |

**Comment by pllim** [comment]
> I spent some time in paint

MS Paint? I applaud you, sir. 👏 👏 👏

**Comment by javerbukh** [comment]
@kecnry At this point, my preference is a separate plugin from plot options that is dedicated to image layering. I think that makes the most sense for this workflow while also keeping this functionality contained to Imviz, which I know @camipacifici was concerned about as well.

@pllim The reordering I'm describing is like the latter, C -> blue, B -> green, A -> red.

Thank you 😄

**Comment by javerbukh** [comment]
I actually had fun doing it! I like planning the design of some of these tools and thinking of how they could be improved. Especially if Imviz will be used for more intensive use cases in the future.

From looking around online it does actually seem right that the order of layers and their colors matters for the final image, although a confirmation from @astrofrog would be appreciated.
