### ISSUE TITLE
Cubeviz cube viewer colormap printed out

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#254]
When I change the colormap in the Cubeviz cube viewer-->Layer-->colormap,
the colormap name is printed in the cell output:

![Cube_viewer_colormap](https://user-images.githubusercontent.com/44263689/91202017-3630ad80-e6cf-11ea-8a01-47a0372c6bd7.png)

**Comment by javerbukh** [comment]
Looks like this line was left in glue-jupyter: https://github.com/glue-viz/glue-jupyter/blob/e8295331154589e04aa40f1f278ccc61626c92c4/glue_jupyter/common/state_widgets/layer_image.py#L50

**Comment by rosteen** [comment]
This was fixed, closing.
