### ISSUE TITLE
Cubeviz: Data tabs (e.g. moment maps) can't be unlinked in uncertainty viewer[BUG]; Can't get rainbow colormap to show.

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#2602]
### Jdaviz component

Cubeviz

### Description

When  I create a moment map of a MIRI MRS cube and display it in uncertainty viewer, it shows, but gets linked to other data sets. It also doesn't show the Rainbow colormap when I select it. When try to hide the unwanted data with the eye icon, it makes both data sets disappear.  There is a traceback below the cell.

### How to Reproduce

1. Load MIRI MRS data cube
2. Select spatial and spectral subsets
3. Create Moment 1 map in plugin using spectral subset, rename data 'moment1' and display in uncertainty viewer
4.  It shows up there in greyscale with default plot options.
5. Go to plot options (opens to unc cube (tab B), not moment1 (tab E)
6. Select tab E (moment1 map)--eyball is crossed out there even though the data is shown in the viewer in greyscale
7. At this point there is no way to change the colormap to rainbow without clicking the eyeball
8. Clicking the eyeball links tab E to tab B and now shows the colormap selection.
9. Select Rainbow color map, but nothing changes for the moment1 map still shown in unc viewer.
10.  There are four similar tracebacks reported in the cell during the above process, which all look similar to the last one:
------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/science/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:773, in Widget._handle_msg(self, msg)
    771         if 'buffer_paths' in data:
    772             _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 773         self.set_state(state)
    775 # Handle a state request.
    776 elif method == 'request_state':

File ~/miniconda3/envs/science/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:650, in Widget.set_state(self, sync_data)
    645         self._send(msg, buffers=echo_buffers)
    647 # The order of these context managers is important. Properties must
    648 # be locked when the hold_trait_notification context manager is
    649 # released and notifications are fired.
--> 650 with self._lock_property(**sync_data), self.hold_trait_notifications():
    651     for name in sync_data:
    652         if name in self.keys:

File ~/miniconda3/envs/science/lib/python3.10/contextlib.py:142, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    140 if typ is None:
    141     try:
--> 142         next(self.gen)
    143     except StopIteration:
    144         return False

File ~/miniconda3/envs/science/lib/python3.10/site-packages/traitlets/traitlets.py:1371, in HasTraits.hold_trait_notifications(self)
   1369 for changes in cache.values():
   1370     for change in changes:
-> 1371         self.notify_change(change)

File ~/miniconda3/envs/science/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:701, in Widget.notify_change(self, change)
    698     if name in self.keys and self._should_send_property(name, getattr(self, name)):
    699         # Send new state to front-end
    700         self.send_state(key=name)
--> 701 super().notify_change(change)

File ~/miniconda3/envs/science/lib/python3.10/site-packages/traitlets/traitlets.py:1386, in HasTraits.notify_change(self, change)
   1384 def notify_change(self, change):
   1385     """Notify observers of a change event"""
-> 1386     return self._notify_observers(change)

File ~/miniconda3/envs/science/lib/python3.10/site-packages/traitlets/traitlets.py:1431, in HasTraits._notify_observers(self, event)
   1428 elif isinstance(c, EventHandler) and c.name is not None:
   1429     c = getattr(self, c.name)
-> 1431 c(event)

File ~/miniconda3/envs/science/lib/python3.10/site-packages/jdaviz/core/template_mixin.py:261, in skip_if_no_updates_since_last_active.<locals>.decorator.<locals>.wrapper(self, msg)
    259 if meth.__name__ not in self._methods_skip_since_last_active:
    260     self._methods_skip_since_last_active.append(meth.__name__)
--> 261 ret_ = meth(self, msg)
    262 if ret_ is False:
    263     self._methods_skip_since_last_active.remove(meth.__name__)

File ~/miniconda3/envs/science/lib/python3.10/site-packages/jdaviz/configs/default/plugins/plot_options/plot_options.py:862, in PlotOptions._update_stretch_curve(self, msg)
    860 data = interval(x)
    861 data = contrast_bias(data, out=data)
--> 862 data = stretch(data, out=data)
    864 if color_mode == 'Colormaps':
    865     cmap = colormaps[self.image_colormap.text]

TypeError: LinearStretch.__init__() got an unexpected keyword argument 'out'

### Expected behavior

Allow me to select rainbow colormap for moment1 in uncertainty viewer without linking to the uncertainty cube.

### Browser

Firefox 120.0.1 

### Jupyter

jupyter --version

Selected Jupyter core packages...
IPython          : 8.5.0
ipykernel        : 6.22.0
ipywidgets       : 8.0.7
jupyter_client   : 7.3.5
jupyter_core     : 5.3.0
jupyter_server   : 1.19.1
jupyterlab       : 3.4.7
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.6.1
notebook         : 6.4.12
qtconsole        : 5.3.2
traitlets        : 5.4.0

### Software versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("Numpy", numpy.__version__)
import astropy; print("astropy", astropy.__version__)
import matplotlib; print("matplotlib", matplotlib.__version__)
import scipy; print("scipy", scipy.__version__)
import skimage; print("scikit-image", skimage.__version__)
import asdf; print("asdf", asdf.__version__)
import stdatamodels; print("stdatamodels", stdatamodels.__version__)
import gwcs; print("gwcs", gwcs.__version__)
import regions; print("regions", regions.__version__)
import specutils; print("specutils", specutils.__version__)
import specreduce; print("specreduce", specreduce.__version__)
import photutils; print("photutils", photutils.__version__)
import astroquery; print("astroquery", astroquery.__version__)
import yaml; print("pyyaml", yaml.__version__)
import asteval; print("asteval", asteval.__version__)
import idna; print("idna", idna.__version__)
import traitlets; print("traitlets", traitlets.__version__)
import bqplot; print("bqplot", bqplot.__version__)
import bqplot_image_gl; print("bqplot-image-gl", bqplot_image_gl.__version__)
import glue; print("glue-core", glue.__version__)
import glue_jupyter; print("glue-jupyter", glue_jupyter.__version__)
import glue_astronomy; print("glue-astronomy", glue_astronomy.__version__)
import echo; print("echo", echo.__version__)
import ipyvue; print("ipyvue", ipyvue.__version__)
import ipyvuetify; print("ipyvuetify", ipyvuetify.__version__)
import ipysplitpanes; print("ipysplitpanes", ipysplitpanes.__version__)
import ipygoldenlayout; print("ipygoldenlayout", ipygoldenlayout.__version__)
import ipypopout; print("ipypopout", ipypopout.__version__)
import jinja2; print("Jinja2", jinja2.__version__)
import voila; print("voila", voila.__version__)
import vispy; print("vispy", vispy.__version__)
import sidecar; print("sidecar", sidecar.__version__)
import jdaviz; print("Jdaviz", jdaviz.__version__)

macOS-13.6.1-x86_64-i386-64bit
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:54) [Clang 13.0.1 ]
Numpy 1.24.4
astropy 5.2.1
matplotlib 3.6.0
scipy 1.9.1
scikit-image 0.19.3
asdf 2.14.3
stdatamodels 1.7.2
gwcs 0.18.3
regions 0.6
specutils 1.9.1
specreduce 1.3.0
photutils 1.9.0
astroquery 0.4.7.dev8738
pyyaml 6.0
asteval 0.9.28
idna 3.4
traitlets 5.4.0
bqplot 0.12.40
bqplot-image-gl 1.4.11
glue-core 1.17.1
glue-jupyter 0.19.0
glue-astronomy 0.10.0
echo 0.7
ipyvue 1.8.0
ipyvuetify 1.8.4
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
ipypopout 1.0.0
Jinja2 3.1.2
voila 0.4.0
vispy 0.11.0
sidecar 0.5.2
Jdaviz 3.8.1.dev1+gc9daae85

**Comment by javerbukh** [comment]
After installing jdaviz in a new environment, I checked my software versions and got something much different than you. Can you please pull the latest dev version and dependencies?
```
Windows-10-10.0.19045-SP0
Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
Numpy 1.26.2
astropy 6.0.0
matplotlib 3.8.2
scipy 1.11.4
scikit-image 0.22.0
asdf 3.0.1
stdatamodels 1.8.4
gwcs 0.20.0
regions 0.8
specutils 1.12.0
specreduce 1.3.0
photutils 1.10.0
astroquery 0.4.6
pyyaml 6.0.1
asteval 0.9.31
idna 3.6
traitlets 5.14.0
bqplot 0.12.42
bqplot-image-gl 1.4.11
glue-core 1.17.1
glue-jupyter 0.20.0
glue-astronomy 0.10.0
echo 0.8.0
ipyvue 1.10.1
ipyvuetify 1.8.10
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
ipypopout 1.2.0
Jinja2 3.1.2
voila 0.4.3
vispy 0.14.1
sidecar 0.7.0
Jdaviz 3.8.1.dev3+g90a7f612.d20231208
```

**Comment by PatrickOgle** [comment]
The clean install fixes the error message, but still does not allow me to set the rainbow color map. There are also weird issues with the data tabs in Plot options. Switching tabs doesn't change to the proper data item/subset right away. I had to cycle through the tabs to eventually see them take.

**Comment by PatrickOgle** [comment]
The bug appears to be fixed in dev.  The wrong tab seems to come up, so I have to select it first. Otherwise, everything  looks good.

This can be closed.
