### ISSUE TITLE
Remove deprecated Canvas Rotation plugin

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#2672]
It is deprecated in Jdaviz 3.9 as part of:

* #2179 

Should be removed some time after. Is Jdaviz 4.0 too soon?

[🐱](https://jira.stsci.edu/browse/JDAT-4145)

**Comment by kecnry** [comment]
I think usually we've been doing (at least) 2 minor releases.  So 3.11 at the earliest?

**Comment by pllim** [comment]
Hmm when will we decide to upgrade to 4.0 ?

Given we're not following strict semver, maybe 3.11 is okay.
