### ISSUE TITLE
Cubeviz Collapse and Moment Maps Plugins: Spectral bounds do not match Region selection

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#268]
When spectral region is selected in Collapse Plugin, the upper and lower spectral bounds
should change to match those of the region, but do not.  It is not clear in this case which
bounds are being used to compute the collapse.

**Comment by PatrickOgle** [comment]
The same bug exists in the Moment Maps Plugin.

**Comment by rosteen** [comment]
It works for me. Could you post a screenshot of the behavior you're seeing?

![Screen Shot 2020-09-08 at 8 43 15 AM](https://user-images.githubusercontent.com/39831871/92478118-b6ffa700-f1af-11ea-96ae-885a8b866b32.png)

**Comment by PatrickOgle** [comment]
Hmm... It is working now.  Maybe I got into an error state from something else and didn't realize it.

**Comment by PatrickOgle** [comment]
A different bug--If I try to do a second collapse with the same region, but with resized bounds: change to Region=None, resize the region, then reselect Region 1, the region bounds are correct.
However, if I apply Collapse again, it errors out and the image viewer that contained the intial collapse goes blank.
Is collapse trying to overwrite the same output product name?

The error message is very long and repetitive, but starts and ends with:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_json(self, json, widget)
    149         self._block_on_state_change = True
    150         try:
--> 151             update_state_from_dict(state, json)
    152         finally:
    153             self._block_on_state_change = False

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_dict(state, changes)
     49                         update_state_from_dict(callback_list[i], changes[name][i])
     50                     else:
---> 51                         if (changes[name][i] != MAGIC_IGNORE and
     52                                 callback_list[i] != changes[name][i]):
     53                             callback_list[i] = changes[name][i]

IndexError: list index out of range

.....

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_json(self, json, widget)
    149         self._block_on_state_change = True
    150         try:
--> 151             update_state_from_dict(state, json)
    152         finally:
    153             self._block_on_state_change = False

~/miniconda3/envs/jdaviz19/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_dict(state, changes)
     49                         update_state_from_dict(callback_list[i], changes[name][i])
     50                     else:
---> 51                         if (changes[name][i] != MAGIC_IGNORE and
     52                                 callback_list[i] != changes[name][i]):
     53                             callback_list[i] = changes[name][i]

IndexError: list index out of range

**Comment by rosteen** [comment]
Ah, it is using the same label for subsequent collapses - if desired I can update it to iterate an integer and have the labels be something like `Collapsed 1`. `Collapsed 2`, etc. 

That `MAGIC_IGNORE` error has showed up in a few different contexts and seems to be related to either `traitlets`, the "data loaded" snackbar messages, or a combination of the two. If there's not already an issue to look into that, there should be (although there's a good chance it's a `glue-jupyter` bug).

**Comment by mariobuikhuizen** [comment]
Yes, and possibly https://github.com/glue-viz/glue-jupyter/pull/211 is also needed.

**Comment by rosteen** [comment]
This has been resolved - both the original issue, and collapsing again with the same label, which now makes clear that you'll be overwriting unless you change the label.
