### ISSUE TITLE
Specviz Unit Conversion with subset selected

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#280]
Trying to convert units with a subset selected in the spectrum viewer gives this output and 
error messages, but works when there is no subset selected :

![unit_conversion_with_subset](https://user-images.githubusercontent.com/44263689/92627490-6fede080-f299-11ea-95f4-c4b53e127537.png)

---------------------------------------------------------------------------
IncompatibleAttribute                     Traceback (most recent call last)
~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_mask(self, subset_state, view)
   1384         try:
-> 1385             return subset_state.to_mask(self, view=view)
   1386         except IncompatibleAttribute:

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/subset.py in to_mask(self, data, view)
    727     def to_mask(self, data, view=None):
--> 728         x = data[self.att, view]
    729         result = (x >= self.lo) & (x <= self.hi)

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in __getitem__(self, key)
    570 
--> 571         return self.get_data(key, view=view)
    572 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_data(self, cid, view)
   1360         else:
-> 1361             raise IncompatibleAttribute(cid)
   1362 

IncompatibleAttribute: World 0

During handling of the above exception, another exception occurred:

IncompatibleAttribute                     Traceback (most recent call last)
~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

~/Desktop/jdat/jdaviz/jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py in vue_unit_conversion(self, *args, **kwargs)
    170 
    171             #TODO: Fix bug that sends AddDataMessage into a loop
--> 172             self.app.add_data_to_viewer("spectrum-viewer", selected_data_label)
    173 
    174         else:

~/Desktop/jdat/jdaviz/jdaviz/app.py in add_data_to_viewer(self, viewer_reference, data_label, clear_other_data)
    576         if data_id is not None:
    577             data_ids.append(data_id)
--> 578             self._update_selected_data_items(viewer_item['id'], data_ids)
    579         else:
    580             raise ValueError(

~/Desktop/jdat/jdaviz/jdaviz/app.py in _update_selected_data_items(self, viewer_id, selected_items)
    863                                               viewer_id=viewer_id,
    864                                               sender=self)
--> 865             self.hub.broadcast(add_data_message)
    866 
    867         # Remove any deselected data objects from viewer

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/hub.py in broadcast(self, message)
    213             logging.getLogger(__name__).info("Broadcasting %s", message)
    214             for subscriber, handler in self._find_handlers(message):
--> 215                 handler(message)
    216 
    217     def __getstate__(self):

~/Desktop/jdat/jdaviz/jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py in _on_viewer_data_changed(self, msg)
     73         viewer = self.app.get_viewer('spectrum-viewer')
     74 
---> 75         self._viewer_data = self.app.get_data_from_viewer('spectrum-viewer')
     76 
     77         self.dc_items = [layer_state.layer.label

~/Desktop/jdat/jdaviz/jdaviz/app.py in get_data_from_viewer(self, viewer_reference, data_label, cls, include_subsets)
    401                     if cls is not None:
    402                         handler, _ = data_translator.get_handler_for(cls)
--> 403                         layer_data = handler.to_object(layer_data,
    404                                                        statistic=statistic)
    405 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue_astronomy/translators/spectrum1d.py in to_object(self, data_or_subset, attribute, statistic)
    142             return data_kwargs
    143 
--> 144         data_kwargs = parse_attributes(
    145             [attribute] if not hasattr(attribute, '__len__') else attribute)
    146 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue_astronomy/translators/spectrum1d.py in parse_attributes(attributes)
    109                     mask = None
    110                 else:
--> 111                     mask = data.get_mask(subset_state=subset_state)
    112                     mask = ~mask
    113 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_mask(self, subset_state, view)
   1385             return subset_state.to_mask(self, view=view)
   1386         except IncompatibleAttribute:
-> 1387             return get_mask_with_key_joins(self, self._key_joins, subset_state, view=view)
   1388 
   1389     def __setitem__(self, key, value):

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/joins.py in get_mask_with_key_joins(data, key_joins, subset_state, view)
    103                             "contain a single component.")
    104 
--> 105     raise IncompatibleAttribute

IncompatibleAttribute:

**Comment by PatrickOgle** [comment]
Here's what a successful conversion looks like when no subset is selected:
![unit_conversion_nosubset](https://user-images.githubusercontent.com/44263689/92627828-ebe82880-f299-11ea-8e7c-d89d70bde51a.png)

**Comment by PatrickOgle** [comment]
Warning, the bug doesn't always occur when a subset is selected, but may happen when successive 
conversions are applied.

**Comment by javerbukh** [comment]
When units are converted, the current implementation removes the currently selected data (if it is data that already has its units converted) and adds the newly converted spectrum with updated units. When this data is removed, I believe that this causes problems with subsets since subsets seem to be connected to the data that they were created for. The aim is for this to be solved in the unit conversion refactor.
