### ISSUE TITLE
Make jdaviz unit converter more robust to different data types

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#2811]
- [ ] Revert https://github.com/spacetelescope/jdaviz/pull/2809 (since it is not upstream bug after all)
- [ ] Make sure #2805 is no longer issue in the PR to fix this.

The issue highlighted in https://github.com/spacetelescope/jdaviz/issues/2805 was identified as being due to the new glue-core v1.19.0 release. In fact, there is no bug in glue v1.19.0 as such, but there are now more cases where the unit conversion machinery is called. However, the unit converter in jdaviz is not sufficiently robust, and the following fails if the data is a 2D image with no spectral component:

https://github.com/spacetelescope/jdaviz/blob/620ccfed55b1209b737377a272111c343eb2b2e5/jdaviz/app.py#L91-L98

To work with glue-core v1.19.0, the unit converter will need to be made a little more robust and not assume that any dataset that has a flux also has a spectral axis.

There is a separate issue here that 0-d WCSes should not emit errors deep in astropy.wcs but that is another matter (https://github.com/astropy/astropy/issues/16298)

[🐱](https://jira.stsci.edu/browse/JDAT-4411)

**Comment by pllim** [comment]
I am not satisfied with https://github.com/spacetelescope/jdaviz/pull/2812 but not sure how to proceed.
