### ISSUE TITLE
Collapse Plugin spectral bounds don't match selected region

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#283]
Here is an example--spectral bounds are off by 0.2e-7 in the plugin compared to the spectrum viewer:
![spectral_bounds_mismatch](https://user-images.githubusercontent.com/44263689/92735304-4c816f00-f347-11ea-9847-3ed8cb9c52e3.png)

**Comment by rosteen** [comment]
As explained in #501, this was fixed by a bugfix in `specutils`. We also don't display the bounds in the plugin anymore, so it's a bit moot in that regard as well. Closing.
