### ISSUE TITLE
Run bandit and integrate it into the CI

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#289]
Bandit is a now I think fairly standard tool for auditing Python packages for known security issues. We should try running that on jdaviz to see what it gives.  I suspect it's possible it'll yield a bunch of issues given that in some sense the Jupyter platform is intentionally designed to enable some amount of arbitrary code execution... But I'm not sure whether Bandit checks for that vs more lower-level things.

If it passes or reveals some security issues that really *are* reasonable to fix, we may want to set it up to run on new PRs as part of the CI. (There's a pretty much ready-to-go github action for this it looks like, at least based on what I see @pllim implemented in https://github.com/spacetelescope/synphot_refactor).

**Comment by pllim** [comment]
See my comments on astropy/specutils#716 😅
