### ISSUE TITLE
jdaviz pip install fails at vispy

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#305]
When trying to do pip install of jdaviz1.0.0 in a clean conda environment, with python 3.8,
it fails at vispy:

conda create -n jdaviz1.0.0 python=3.8
conda activate jdaviz1.0.0
pip install jdaviz --no-cache-dir

Top of error message:
Collecting vispy>=0.6
  Downloading vispy-0.6.4.tar.gz (13.3 MB)
     |████████████████████████████████| 13.3 MB 4.5 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pogle/miniconda3/envs/jdaviz1.0.0/bin/python3.8 /Users/pogle/miniconda3/envs/jdaviz1.0.0/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/cw/tytqv5y91qd3j4_stwnc03c80001ww/T/pip-build-env-d6q3r24b/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools>=30.3.0' setuptools_scm setuptools_scm_git_archive 'Cython>=0.29.2' 'numpy; python_version=='"'"'2.7'"'"'' 'numpy==1.13.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"''
       cwd: None
  Complete output (2864 lines):

Full output
[jdaviz_install_errors.txt](https://github.com/spacetelescope/jdaviz/files/5263153/jdaviz_install_errors.txt)

**Comment by PatrickOgle** [comment]
It does work with python=3.7

**Comment by eteq** [comment]
If I do the following (in an Ubuntu 18.04 distro under WSL2):
```
% conda create -n jdaviz-test-pip python=3.8 pip wheel
% conda activate jdaviz-test-pip
% pip install jdaviz
```
I get a successful build.  So it's at least not python 3.8 per se that's the problem.  Maybe it's the conda package of vispy?

**Comment by eteq** [comment]
Oh, no, it can't be that because it looks like you're getting the pip build of vispy.  Hmm, mysterious.  @PatrickOgle, can you specify which OS version you're seeing this on (since vispy might be hitting an OS-specific compiler issue)?

**Comment by PatrickOgle** [comment]
HighSierra 10.13.6

**Comment by eteq** [comment]
Looking more closely at the error message it's definitely due to numpy failing to build in the process of `vispy` building.  I think this is probably at its core a problem with how `vispy` is being packaged.  But @PatrickOgle, to test some work arounds, can you see if either
```
% conda create -n jdaviz1.0.0 python=3.8 numpy
% conda activate jdaviz1.0.0
% pip install jdaviz --no-cache-dir
```
or
```
% conda create -n jdaviz1.0.0 python=3.8
% conda activate jdaviz1.0.0
% pip install numpy
% pip install jdaviz --no-cache-dir
```
change the resulting error message at all?

**Comment by astrofrog** [comment]
Looks like this was fixed in https://github.com/vispy/vispy/commit/f6c84efc3f423ab35e2bd72cfc51594398566b8c but hasn't been a vispy release since. Maybe worth pinging them?

**Comment by astrofrog** [comment]
A fix for now is to first pip install the developer version of vispy then pip install jdaviz

**Comment by astrofrog** [comment]
See https://github.com/vispy/vispy/issues/1902 for an existing issue in vispy

**Comment by astrofrog** [comment]
Actually this can also be solved by installing the vispy wheels - I'm not sure why it's trying to install from source but @PatrickOgle can you try:

```
conda create -n jdaviz1.0.0 python=3.8
conda activate jdaviz1.0.0
pip install wheel
pip install jdaviz --no-cache-dir
```

**Comment by PatrickOgle** [comment]
@astrofrog This recipe fails in the same way.  (And pip install wheel wasn't necessary.)

**Comment by camipacifici** [comment]
Same for me.
I will try the others suggested above.

**Comment by camipacifici** [comment]
`% conda create -n jdaviz1.0.0 python=3.8 numpy`
`% conda activate jdaviz1.0.0`
`% pip install jdaviz --no-cache-dir`

This fails too.

**Comment by camipacifici** [comment]
`% conda create -n jdaviz1.0.0 python=3.8`
`% conda activate jdaviz1.0.0`
`% pip install numpy --no-cache-dir`
`% pip install jdaviz --no-cache-dir`

And this fails too.

The only one that works for me is:
`conda create -n jdaviz1.0.0 python=3.7`
`conda activate jdaviz1.0.0`
`pip install jdaviz --no-cache-dir`

**Comment by camipacifici** [comment]
One last thing, as @astrofrog suggested, this works too:
`conda create -n jdaviz1.0.0 python=3.8`
`conda activate jdaviz1.0.0`
`pip install git+https://github.com/vispy/vispy.git`
`pip install jdaviz --no-cache-dir`

**Comment by eteq** [comment]
OK, assuming https://github.com/spacetelescope/jdaviz/issues/305#issuecomment-697543882 works for @PatrickOgle too, then I think we should document this as a "known issue" until there's a vispy release, and then set the minimum version to the new release assuming that fixes it (and we leave this issue open until then).

**Comment by astrofrog** [comment]
Of course one option would be to recommend python 3.7 by default, since it’s a new environment anyway. This might be cleaner?

**Comment by eteq** [comment]
it looks like vispy just did a 0.6.5 on pypi 30 min ago.  @PatrickOgle or @camipacifici, can you check that this solves it. I think to make sure it's the latest one, it should be:

```
% conda create -n jdaviz-test python=3.8
% conda activate jdaviz-test
% pip install vispy>0.6.5
% pip install jdaviz
```

**Comment by PatrickOgle** [comment]
I verify that these installation instructions do work on High Sierra.

**Comment by eteq** [comment]
Ok, great.  I think that means as long as you don't *already* have an old version of vispy that might get in the way things are good for new installs.  I'll make a PR to bump the required version number, though, and that combined with an update to the note in #307 should resolve this.
