### ISSUE TITLE
Standardize/fix list coercion in Mosviz parsers

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#314]
Currently the Mosviz data parsers each attempt to check that the input is a list, and put the input into a single item list if it's not. But the checks look like they're different for each parser, and the metadata parser doesn't work at all for string input since it's checking for a `__len__` attribute, and strings also have a length. The parsers need a pass to make sure they are all working, and doing the list coercion in the same way. This could/should probably be broken out into its own function.

**Comment by pllim** [comment]
No JIRA associated with this we can close?

**Comment by rosteen** [comment]
I already closed it.
