### ISSUE TITLE
BUG: Filter out impossible SB <> SB and Flux <> Flux conversions in unit conversion plugin

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#3183]
This was #2876 by @cshanahan1 that got accidentally deleted.

If you load a MJy / sr cube, in the unit conversion plugin there are some units listed as available that you can't actually convert to (e.g MJy / sr to bol / sr, or erg / cm**2 sr). The unit conversion (which, from what I understand, only applies to the displayed data, not updating data in the data collection?) appears to happen, the display label is changed, but the flux disappears from the spectrum viewer because the conversion wasn't successful. This has implications for other plugins as well that use the flux / sb unit (like moment maps).

I'm not sure if this issue is limited to SB <> SB, i imagine it exists as well for flux <> flux.

### How to Reproduce

1. Load cubeviz example notebook, which has data in MJy / sr
2. Use unit conversion plugin to convert to one of the available units that is invalid, like bol / sr

### Expected behavior

These invalid options shouldn't be listed as possibilities.

**Comment by kecnry** [comment]
Was this (fully) addressed by #3139 or is there still work to do?

**Comment by cshanahan1** [comment]
I think this can be closed

**Comment by kecnry** [comment]
Thanks!  Feel free to re-open if necessary (I know there likely will be a similar case wrt /pixel**2, but that probably isn't covered by this initial issue)!
