### ISSUE TITLE
Cubeviz only loading FLUX extension on "Desktop App" mode

### ISSUE THREAD

**Issue by dtn5ah** [spacetelescope/jdaviz#322]
Discovered this after rebasing on master. Installed jdaviz master on commit bc710794ac730bfed635a2f2ccd73bc2a30b6bab.  When I run cubeviz with [our manga dataset](https://stsci.box.com/shared/static/28a88k1qfipo4yxc4p4d40v4axtlal8y), it only loads the flux:
<img width="1537" alt="Screen Shot 2020-10-02 at 3 18 15 PM" src="https://user-images.githubusercontent.com/25206008/94961392-9121a580-04c2-11eb-9c6d-6939d37b960a.png">

as opposed to the jupyter notebook interface that loads the full cube:

<img width="935" alt="Screen Shot 2020-10-02 at 3 26 34 PM" src="https://user-images.githubusercontent.com/25206008/94961962-acd97b80-04c3-11eb-8a19-7565c16b3236.png">

Verified on both Windows and macOS

**Comment by dtn5ah** [comment]
Okay, so I tracked it down to the following check in the cubeviz parser, under `_parse_hdu()`:
```
        # If the data type is some kind of integer, assume it's the mask/dq
        if hdu.data.dtype in (np.int, np.uint, np.uint32) or \
                any(x in hdu.name.lower() for x in EXT_TYPES['mask']):
            app.add_data_to_viewer('mask-viewer', data_label)

        if 'errtype' in [x.lower() for x in hdu.header.keys()] or \
                any(x in hdu.name.lower() for x in EXT_TYPES['uncert']):
            app.add_data_to_viewer('uncert-viewer', data_label)

        if any(x in hdu.name.lower() for x in EXT_TYPES['flux']):
            app.add_data_to_viewer('flux-viewer', data_label)
            app.add_data_to_viewer('spectrum-viewer', data_label)
```
For whatever reason, only the flux check is triggering, and I am too unfamiliar to this parser to provide any insight into this... :(

**Comment by dtn5ah** [comment]
@javerbukh @PatrickOgle I'm willing to bet that this isn't the case, but on the astronomically slim chance you were planning on using the desktop app for your cubeviz demos.... don't 😅

**Comment by nmearl** [comment]
Hmm. I'm on latest master, and I see all three for the manga cube:

<img width="1120" alt="Screen Shot 2020-10-03 at 2 18 10 PM" src="https://user-images.githubusercontent.com/4141126/95000086-62b7cf00-0583-11eb-9b87-3d514ebd38f3.png">


Just to check, does `which jdaviz` point to the correct environment installation?

**Comment by havok2063** [comment]
I've also noticed this behavior when running in the notebook mode.  However it's been sporadic on its occurrences, so I've never actively captured the scenario which produced the issue.  If I notice it again, I'll try to capture what I did.

**Comment by havok2063** [comment]
Here's a shot of it not loading a test JWST file in the notebook, using [this fork](https://github.com/havok2063/jdaviz/tree/data), which is up-to-date with master.

<img width="1159" alt="Screen Shot 2020-10-16 at 10 11 43 AM" src="https://user-images.githubusercontent.com/1836302/96269310-38f5a380-0f98-11eb-8d94-240aab3a7a0e.png">

compared to the web

<img width="1660" alt="mast_jdaviz_3d" src="https://user-images.githubusercontent.com/1836302/96269379-4b6fdd00-0f98-11eb-8000-b96f94ddc2ac.png">

**Comment by havok2063** [comment]
After rebasing jdaviz to the latest, the web display of the cube now also no longer displays the error and mask extensions.

**Comment by havok2063** [comment]
Bumping this.  This issue now occurs consistently in both my notebooks and in the web display.

**Comment by havok2063** [comment]
@dtn5ah I think this error is due to an issue extracting the WCS from `SpectralCube`.  In particular, this code in `_parse_hdu`
```
    wcs = None

    for hdu in hdulist:
        if hdu.data is None:
            continue

        try:
            sc = SpectralCube.read(hdulist, format='fits')
            wcs = sc.wcs
        except (ValueError, FITSReadError):
            continue
```
fails to extract a WCS.  When it gets to the second loop, this code fails at both `try` blocks and the `continue` causes the loop to skip over the error and mask extensions, and they never get added to the viewer or `data_collection`
```
        try:
            sc = SpectralCube.read(hdu, format='fits')
        except (ValueError, OSError):
            # This will fail if the parsing of the wcs does not provide
            # proper celestial axes
            try:
                hdu.header.update(wcs.to_header())
                sc = SpectralCube.read(hdu)
            except (ValueError, AttributeError) as e:
                logging.warn(e)
                continue
        except FITSReadError as e:
            logging.warn(e)
            continue
```
If you print the error produced by `sc = SpectralCube.read(hdulist, format='fits')` for every extension you get
`No data found in HDU 0. You can try using the hdu= keyword argument to read data from another HDU.`
