### ISSUE TITLE
Show scientific notation of numbers if tick formatting does not show full number

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#328]
So instead of the tick showing `0.00` which is meant to represent `0.00000005`, we prefer to have something like 5e-8. This can be done by setting the tick_format in `specviz.app.get_viewer("spectrum-viewer").figure.axes[1].tick_format='0.2f'` to `0.2e`.

**Comment by gkanarek** [comment]
I will note that that formatting _always_ gives scientific notation, it doesn't adapt if the data doesn't need it.
