### ISSUE TITLE
Specviz: axes get autoscaled at every operation

### ISSUE THREAD

**Issue by camipacifici** [spacetelescope/jdaviz#335]
Whether the axis limits have been set with the zoom features or with commands, they reset at every operation. This happens in the notebook, with jdaviz 1.0.3.

EDIT - blocked by:

* glue-viz/glue-jupyter#247
* glue-viz/glue#2223 [🐱](https://jira.stsci.edu/browse/JDAT-1745)

**Comment by rosteen** [comment]
Note that users were frustrated by this in the practice JWebbinar, specifically that they created a subset and the spectrum autoscaled away from their zoom.

**Comment by pllim** [comment]
I do notice this behavior in Imviz that the zoom resets when linking happens. I wonder if it is the same thing.

If it is, then perhaps the bug is deep in glue-core.

**Comment by pllim** [comment]
@astrofrog narrowed the broken Home issue to glue-viz/glue#2223 , I think. I added it as blocker to this issue above in the original post.
