### ISSUE TITLE
Redshift/spectralcoord slider that auto-updates the linelist

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#336]
Currently, while `Spectrum1D` has lots of options for interacting with the redshift of a spectrum's redshift, none of that is really exposed or meaningful in specviz.  So this issue is about the minimal interaction I know I need because I was just trying to do it with a COS spectrum last week.

Specifically, this is about a redshift "slider". This would be a scrubber along the lines of the slice scrubber in cubeviz, but it would be for setting the redshift in the spectrum. The following are mandatory behaviors:

## Probably not-too-controversial features

* Should be both a slider and a "type a number in this box" style interface (like cubeviz, but floating point)
* The `Spectrum1D` that comes out from the helper should have the redshift set to whatever the slider is at.  Note that this potentially has a lot of complex interactions with the `SpectralCoord` machinery in `specutils`/`astropy`, but that should all be carefully hidden in the `Spectrum1D.redshift` and `Spectrum1D.radial_velocity` properties.
* Any redshift/radial velocity the user already has set (which is implicitly in the `spectral_coord`) should be shown as the value of the slider 
* (closely related) - there should be a way to set the redshift from the notebook that uses the `Spectrum1D` machinery - best case this is as simple as ``specviz.get_spectra()['whatever'].redshift = 0.123``, although a setter as a compromise might be OK if the above doesn't work.
* There should be a way to specify the redshift either as redshift *or* as radial velocity (this should have as little "smarts" as possible because `Spectrum1D`/`SpectralCoord` already has a `redshift` and `radial_velocity` interface that can be used directly by specviz, and we want that to be consistent with the slider)
* (bonus) the internal representation glue sees should actually have the right redshift
* When line lists are shown, they should slide left-to-right as the user moves the scrubber

## Not yet specified/opinions may be needed

* should this be baked into the `specviz` configuration, or should this be a plugin?  I think the former because it'd be really annoying to have to go between the line list and redshift plugins, and the `redshift` really *is* an intrinsic part of a `Spectrum1D`, not an "additional" feature like the analysis plugins.  But opinons may very
* Should the scrubber actually override the "redshift" value the user provided if they added a custom redshift in the line list table, or should it just "mask" whatever's in the table? (I tend towards the first one, but not a particularly strong opinion)
* when *multiple* spectra are shown, which is used as "the" redshift?  The easiest thing is that it should take whatever the "first" one shown (this is the idiom I described in my specviz concept notebook).  This doesn't work with some workflows, but I think that's better dealt with as a follow-on issue because it ties with syncing up the x-axes.

## Out-of-scope/should be in a follow-on issue

* having a "rest" x-axis - this, again, would ideally come straight from the `SpectralCoord` machinery because there's a lot of technical subtleties in how that's defined.  But the idea would be the "top" axis would slide as the scrubber is moved. Presumably this would be optional or maybe only appear if the redshift is non-0.
* any more complicated interface into `SpectralCoord` beyond "redshift"/"radial velocity"
* computing of redshift based on identified lines or similar workflows

**Comment by hcferguson** [comment]
I agree this sounds like a very useful feature. I'm a bit confused about the concept in the sense of whether it is the axis or the spectrum that slides. I see uses for both cases:

- Axis slides: 
  - You get to keep your spectrum and cursor centered on the feature of interest and read off redshifted wavelengths. Having the rest wavelength at the top would be very useful. 
  - Applies to all the spectra, not just the "first" one. 

- Spectrum slides: 
  - Trying to eyeball lining up a template spectrum with another spectrum.
  - In this case you want to apply to just the one spectrum

As an aside, a related feature would be to be able to read off the velocity shift of a spectral line relative to the redshifted reference for that spectral line.
