### ISSUE TITLE
[BUG] Spectrum-at-spaxel tool raises JSON warnings in uncertainy viewer

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#3362]
### Jdaviz component

Cubeviz

### Description

I was doing some testing with the updated MaNGA cube (https://stsci.box.com/shared/static/gts87zqt5265msuwi4w5u003b6typ6h0.gz) and noticed that when using the spectrum-at-spaxel tool in the uncertainty viewer, every mouse move resulted in a warning:

```
/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.12/site-packages/jupyter_client/session.py:721: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant: inf
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)
```

We should figure out how to handle this case better - there are infs in the uncertainty because we convert a 0 inverse variance to inf stddev, but it's all in masked locations.

### How to Reproduce

Load linked file in Cubeviz, use the tool.

[🐱](https://jira.stsci.edu/browse/JDAT-5044)

**Comment by pllim** [comment]
I bet it is here:

https://github.com/spacetelescope/jdaviz/blob/629fa623b841cd6564000de3605a5aa74520743b/jdaviz/core/template_mixin.py#L4668

But how do you want to serialize a NaN to JSON? `None`, "nan", or ...?

**Comment by kecnry** [comment]
That's to add to a table, the bug mentioned above is for mouseover which shouldn't go through table.... but we likely need a generalized solution that works for both since the same issue would likely occur if using the markers plugin.
