### ISSUE TITLE
Software Engineering - Going Forward

### ISSUE THREAD

**Issue by brechmos** [spacetelescope/jdaviz#34]
We had a short discussion among the dev team to get on the same page for the visualization tools, what needs to get done and priorities. The discussion was based on notes from https://innerspace.stsci.edu/display/~crjones/JDAViz+Next+Steps. 

![20190627_113840](https://user-images.githubusercontent.com/887675/60295371-8c4e6900-98f1-11e9-9907-16c676e70322.jpg)

Please add your discussion items below.  I'll add some more details from the discussion here, as I understood them.

@robelgeda @javerbukh @astrofrog @SaOgaz @nmearl @ibusko

**Comment by nmearl** [comment]
Major decisions have been discussed and implemented. Closing for now.
