### ISSUE TITLE
Traitlets 5.0 release broke all tests

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#345]
I noticed that one of my docs PRs was failing a ton of tests unexpectedly, after some experimenting it turns out the culprit is Traitlets, specifically their 5.0 release. It looks like something that was previously getting returned as an empty list is now getting returned as None, which breaks a set comparison when the app is initialized. I pinned the dependency to the old version in #344 while we figure out/implement changes for compatibility.

This might be of particular interest to @eteq @javerbukh @dtn5ah and, for old times' sake griping about Traitlet problems, @nmearl

**Comment by mariobuikhuizen** [comment]
This should be fixed in ipyvue 1.4.1. See https://github.com/mariobuikhuizen/ipyvue/issues/18
