### ISSUE TITLE
Make sure everything at the top-level of `jdaviz` is in the API

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#354]
While working on #352 I realized it doesn't seem like the docstrings for the helper classes are in the API anywhere.  While they could get a custom section, it raises alarm bells because the easiest API in code generally should be the easiest API to find in the docs.  And `jdaviz.SpecViz`/`jdaviz.CubeViz` don't seem to be there.  Is there something missing in how we're grabbing what ends up in the API section?

**Comment by pllim** [comment]
I think this has been addressed.
