### ISSUE TITLE
get_spectral_regions does not work when subset has multiple borders

### ISSUE THREAD

**Issue by camipacifici** [spacetelescope/jdaviz#356]
I select a subset that is not continuous:
<img width="1404" alt="Screen Shot 2020-11-03 at 2 38 29 PM" src="https://user-images.githubusercontent.com/19998720/98032613-40171100-1de2-11eb-944a-136ce10d2754.png">

then I run
`viz.get_spectral_regions()`

and I hit a bug

AttributeError                            Traceback (most recent call last)
<ipython-input-10-6d3b67f9b159> in <module>
----> 1 viz.get_spectral_regions()

~/miniconda3/envs/jdaviz1.0.3/lib/python3.8/site-packages/jdaviz/configs/specviz/helper.py in get_spectral_regions(self)
     37             as `specutils.SpectralRegion` objects.
     38         """
---> 39         regions = self.app.get_subsets_from_viewer("spectrum-viewer")
     40 
     41         spec_regs = {}

~/miniconda3/envs/jdaviz1.0.3/lib/python3.8/site-packages/jdaviz/app.py in get_subsets_from_viewer(self, viewer_reference, data_label)
    471                     #  the glue component objects
    472                     unit = value.data.coords.spectral_axis.unit
--> 473                     hi, lo = value.subset_state.hi, value.subset_state.lo
    474                     xcen = 0.5 * (lo + hi)
    475                     width = hi - lo

AttributeError: 'AndState' object has no attribute 'hi'

The call to `get_spectral_regions` works if the subset is a single selection with no holes.

**Comment by camipacifici** [comment]
This bug still lives in 2.0.0.

**Comment by pllim** [comment]
I don't think the existing code ever is made to support such a thing. Refactoring is needed. So, do you want like 3 different regions returned or something else?

https://github.com/spacetelescope/jdaviz/blob/86fce7bc773e79339de4f5f45a1f5f67ce21ede2/jdaviz/app.py#L550-L565
