### ISSUE TITLE
Split out top-level "Common Functionality" section

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#358]
Currently, some sections in the Cubeviz and Mosviz docs point to Specviz sections for things that aren't really Specviz-specific, for example panning and zooming or viewer display options. I think we should split out a section at the same level as the tool headings to contain information that is common to all configs, rather than implying that Specviz is somehow primary by referring to its docs so much.

**Comment by pllim** [comment]
@orifox has re-org the docs.
