### ISSUE TITLE
loading correct data after exception does not properly load in mosviz

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#364]
Loading the correct data after an previous attempt that throws an exception does not properly load the data.  I would expect all data containers to cleanse and purge if an exception was thrown during initial data loading.   Instead I need to reinitialize the application.  In the example below it generates the same traceback as indicated in #363. 

```
m = MosViz()
m.app

# initial incorrect data loading
m.load_data(spectra_1d=w1d, spectra_2d=w2d, images=[])

# get a traceback error

# correct data loading
m.load_data(spectra_1d=w1d, spectra_2d=w2d, images=cutouts)

# throws same traceback error
```

**Comment by pllim** [comment]
@havok2063 , is there a way for people to reproduce this for debugging?

**Comment by havok2063** [comment]
@pllim I haven't looked at this in a while but the code above is roughly the code needed to reproduce it.  I think I verified it again below with a slightly different syntax.  In the below code `w1d` and `w2d` are each lists of equal length containing a list of 1d and 2d spectra to load.  I haven't tested if this is generally true of any exception thrown during data loading of Mosviz.  

```
m = MosViz()
m.app

# initial incorrect data loading ; by passing images as an empty list
m.load_data(spectra_1d=w1d, spectra_2d=w2d, images=[])

# get a traceback error 

# correct data loading; should load spectra without images
m.load_data(spectra_1d=w1d, spectra_2d=w2d, images=None)

# throws same previous traceback error
```

**Comment by pllim** [comment]
Ah, okay. I thought this was happening for specific dataset but I can reproduce it with the example notebook data. Thanks!

**Comment by pllim** [comment]
I think #830 should fix your use case, please review. Thanks!
