### ISSUE TITLE
Request: An easy way to check jdaviz version number

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#378]
We should have an easy way for the user to check what version of jdaviz they're using. This is going to be super important going into supporting our userbase! Currently, the way I'd think of doing it is `jdaviz --version`, the same assumption another user made, but that doesn't return anything. 

Furthermore, we have notebooks that rely on specific commits, rather than tagged version numbers. If we're going to have live documentation/resources that use specific commits, I would consider having THAT identifier be returned as well. Although @camipacifici did mention to me the notebooks will be updated once they move from baseline to advance, the point still stands we have live notebooks now that users are using as a guide for their work.

**Comment by dtn5ah** [comment]
Just to clarify, @camipacifici reminded me you can do this from within python or a notebook by doing `import jdaviz; jdaviz.__version__`. This is specifically for the desktop interface
