### ISSUE TITLE
Layout Configuration and Application Engine discussion

### ISSUE THREAD

**Issue by brechmos** [spacetelescope/jdaviz#38]
The question is how to create a "Cubeviz" Application (for example) based on some layout format (let's say a default 3 3D slicers and 1 1D viewer). And the final application "thing" will also have to contain the Glue-Jupyter data manager (gj_app). 

@eteq and I talked for a bit today and there are a few ways this could go.  For example...

### Configuration

We probably need a configuration class that represents a default or initial state of an application, for example a CubeViz Application.  

```
class Configuration:
     def __init__(self, ...):
        self._configuration_dict = {}
```
The `configuration_dict` would be some dictionary representation of a default layout of the component widgets, possibly including some way to specify how to load data, and maybe some look-and-feel configuration for the application or the component widgets.  It might be nice to be able to specify an instance of a `Configuration` object in the `self._configuration_dict` too so then you could nest them (more on that in a minute).  

The format of the self._configuration_dict` is not worked out yet and may be dependent on vuetify, golden ratio layout or other things.  But at a really simple level:
```
cubeviz_configuration_dict = {
    'layout': [['v3d1', 'v3d2', 'v3d3'], ['v1d']],
    'v3d1': {
        'default_data': 'https://some_manga/data.fits',
        'look_and_feel': {'background': 'neon_blue'}
    }
}
```
The above dict could represent information about how things are laid out, the data loaded and things to do with look-and-feel. The look-and-feel dict could be passed directly to the 3Dslicer viewer and make it interpret the key-value pairs.

The other thing one could maybe do is create an electron view of the configuration dict:
```
cubeviz_electron_configuration_dict = {
   'layout': [['menu_bar'], [cubeviz_configuration_dict]],
    'menu_bar': [things in the menu bar]
}
```
Then, this way, we could nest the configuration definitions so that the first one could be used in a notebook and then the second could be used in electron. But the inside look and feel is all the same.  Just an idea.

### Application

The application class that once instantiated, would actually be the CubeViz object (for example) could be based on:

```
class Application:
    def __init__(self, configuraiton, gj_app = None):
        if not gj_app:
            gj_app = create gj_app
        self._data_manager = gj_app

        initial_configuration = configuration
```
where `configuration` in the `__init()` is an instance of the Configuration class from above.

### Questions and Thoughts

* This is only one way to do this and is based on a discussion between myself and @eteq 
* Should the `Application` class actually subclass Glue-Jupyter app rather than have a reference to it?
* Is it ok to mix string class and python objects in the Configuration class?
* How do we deal with a multi-meaning of application in all these things?

@eteq Please clarify (or even edit) the above so that it best represents our discussion.

@astrofrog We would really like your thoughts on this.  The initial idea is to do a first pass implementation in jdaviz but with the plan to move it to Glue Jupyter when "ready".

Cc @javerbukh @nmearl @camipacifici @hcferguson

**Comment by eteq** [comment]
I encountered this while look at something else but I think this was done in #40 and subsequent work
