### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: browser-open.html

### ISSUE THREAD

**Issue by AlexSokokoliuk** [spacetelescope/jdaviz#393]
When I'm trying to analyse SDSS spectra and typing `jdaviz /media/alex/50996581-0148-4e86-b233-a40a9e7215b2/spec-1715-54212-0404.fits --layout=specviz` appearing error `jinja2.exceptions.TemplateNotFound: browser-open.html`

**Comment by rosteen** [comment]
Closing this, jinja2 errors were generally due to Voila, which we no longer use.
