### ISSUE TITLE
install_requires very daunting: Do we really, really need all these deps?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#399]
https://github.com/spacetelescope/jdaviz/blob/9ce9b1f5f78392650afb62e7bc2d7e02ea66ee97/setup.cfg#L20-L39

From the dev doc, it says this package can be used in 3 ways:

1. Notebook
2. Standalone app (that is really just a dumbed down notebook)
3. MAST website

Can we split the dependencies clearly into these 3 categories? 99% of the users will probably not try to deploy their own MAST website, so they don't need whatever MAST website is using that is just exclusive to it. Similarly, if I were an exclusive notebook user and have no interest in the standalone app interface, I also don't need all the extra dependencies just to make it standalone. In the same vein, if I only want ImViz without spectroscopy viz (or vice versa), I don't need the domain specific dependencies. Otherwise, installing this package in its current state might lead to a "bloatware" situation.

p.s. Not to mention all these deps that RTD has to pull in just to build the docs.

**Comment by havok2063** [comment]
MAST has no explicit dependencies listed here in the install_requires list.  The dependencies we use to embed jdaviz into a website are elsewhere, with `jdaviz` one of them.  As for the other two cases, I believe the only package that is needed for the desktop application mode is `voila`, and perhaps `click`, but I could be wrong on that.  If those are the only two, then it might make sense just to keep the list as is.  

I believe most of the dependencies are needed for defining the layout and interface.  If we really wanted to split this up, one option could be to do it around those packages needed for minimal display versus those needed for various plugin functionality.
