### ISSUE TITLE
data-flow diagram initial attempt

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdaviz#41]
To get started on trying to document the data flow, I've created an editable  draw.io chart. 
https://drive.google.com/file/d/1IOIZ8MZswztJ564PzmCgvVL3zhUSu7cw/view?usp=sharing

My thinking is to first pick off a simple case of setting an ROI on a 1D spectrum plot in the jadaviz version of specviz. I've written down the various actions and the various packages that might need to react to this event. 

I think it would be useful to draw arrows for the data flow between the packages, but I'm not sure of the sequence, or even whether they are all involved.

It would probably also be useful to identify internal name of the event handler or callback in each package for this type of event.

Maybe also add a notation to indicate which packages are maintaining a record of this ROI? For this example, I'm pretty certain glue and specutils and the 1D plot widget and bqplot (or plotly) all probably have their own internal representation of the ROI. Not sure if specviz would have this independent of the widget or if any of the other packages would have it.

**Comment by hcferguson** [comment]
At a discussion this AM it was suggested that a "cubeviz" example, selecting a spatial ROI and plotting the corresponding 1D spectrum would be a better use case to illustrate the data flow, since it involves more interaction between tools.  So I've created a new draw.io diagram for that https://drive.google.com/file/d/1rqJkm3b5CPxWxm0RDV6sA1wUJ_xDXq3Q/view?usp=sharing.

**Comment by pllim** [comment]
I think we have moved beyond this stage.
