### ISSUE TITLE
Modifying Redshift Slider breaks Autoscale along the spectral axis

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#412]
The title sounds SUPER similar to what @rosteen found in #404, but I think it's different. With the redshift applied, autoscale seems to set the bounds to the wrong values.

Reproducibility steps:

1. Load spectra
2. Set Redshift Slider
3. `specviz.autoscale_x()`

![image](https://user-images.githubusercontent.com/25206008/106058965-f9bf0e80-60bf-11eb-8c1b-f634f315dfed.png)

**Comment by duytnguyendtn** [comment]
I think this is because autoscale simply sets the bounds to the `max()` and `min()` values of the spectra. It makes sense to me that the values might be changed if a redshift is applied to them

**Comment by rosteen** [comment]
Can you reproduce this on the #404 branch? The redshift slider doesn't change the underlying data, so min/max shouldn't change.
