### ISSUE TITLE
Unclear when Mosviz is "Ready"

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#414]
Mosviz loads provided data by type (that is all images first, then all 2d spectra, then finally all1d spectra). If it takes a while for the data to load, the user could foreseeably (there's nothing stopping the user) click on the table when only a subset of the above data has only been loaded yet (for example, image and 2d spectra, but not 1d spectra). This understandably creates issues. 

My opinion is that data should be loaded "target wise", that being identify each target, their associated files, and load the three together (and block until all three are successfully loaded). That way a user can theoretically begin interacting with the data immediately as they appear in the table, as opposed to seeing the table in a "half loaded" state

**Comment by rosteen** [comment]
Was this concern addressed by Mario's PR to "gray out" the app while data is loading?

**Comment by pllim** [comment]
Now that Mosviz loading performance has been significantly improved, is this still a problem?

**Comment by rosteen** [comment]
I think that between the improved performance, the graying-out of the app while data is loading, and the fact that data is now loaded automatically in the viewers, we can close this.
