### ISSUE TITLE
Incompatible idna version

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#423]
Not our fault, but something to be aware of if you're demoing jdaviz.

As of 2021-02-03, doing a `pip install` on main results in the following error:
` ERROR: requests 2.25.1 has requirement idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.`

`jdaviz` runs into errors because of this. My current workaround is to:
```
pip uninstall idna
pip install idna<3
```

**Comment by pllim** [comment]
Already pinned:

https://github.com/spacetelescope/jdaviz/blob/ef1b27987d6029c058dbf2702b1d00e97982daf8/setup.cfg#L40
