### ISSUE TITLE
Revert to requiring specutils release version

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#424]
#422  pinned the requirements to a dev version of specutils to enable a few of our PRs to move forward. We should change back to requiring release specutils once specutils 1.2 is released, and definitely before doing a release ourselves.

**Comment by pllim** [comment]
Already done:

https://github.com/spacetelescope/jdaviz/blob/ef1b27987d6029c058dbf2702b1d00e97982daf8/setup.cfg#L34
