### ISSUE TITLE
NIRISS Parser: Improve speed of data loading

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#430]
Once #394 is merged, this ticket will address the long time it takes to load NIRISS data into mosviz, especially when there are 10+ sources.

**Comment by pllim** [comment]
xref https://github.com/spacetelescope/jdaviz/pull/394#issuecomment-782113672

**Comment by rosteen** [comment]
Found the culprit, it's `_link_new_data` in `app.py`. Commenting out that line in the `_on_data_added` method of `app.py` results in the NIRISS data loading in 3.7 seconds (I'm testing with the head_canucs* data). I believe the linking code is intended to enable plotting multiple spectra on the same viewer, which I don't think is even needed for the Mosviz use case? I'll poke around and see what I can cook up, I think this might be a quick fix.

**Comment by rosteen** [comment]
#435 greatly improves the parser performance, but per offline discussion with @astrofrog it sounds like the better/final solution to this should be adding some code that can disable the automatic data linking in `app.py` in favor of doing a batch link of all the data at once in the parser itself, for cases where a large amount of data is being loaded together.
