### ISSUE TITLE
NIRISS Parser: Improve performance when zooming and panning

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#432]
This ticket will track the problems with Pan/Zoom functionality once #394 is merged. In the words of @camipacifici, "When zooming and panning on the 1D spectrum, the spectrum first goes back to the original setting and then slowly moves to the requested zoom level while the snackbar about panning too far from the limit of the spectrum keeps appearing and disappearing."

**Comment by camipacifici** [comment]
This is not a problem anymore.
