### ISSUE TITLE
Improve readability of custom line lists

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#437]
<img width="269" alt="Screen Shot 2021-02-23 at 11 35 01 AM" src="https://user-images.githubusercontent.com/7179333/108875595-5af8d580-75cb-11eb-9d04-aa79f8f17c76.png">

On a smaller screen, the input to set a custom line - Line Name, Rest Value, and Unit - only show the first letter of each word. Way may want to have these on separate lines to improve readability without having to rescale the plugin bar.

**Comment by kecnry** [comment]
Closed by #1008
