### ISSUE TITLE
Button to reset scale of viewer

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#439]
A button in the UI to reset the scale of a viewer to the original was brought up in the February 22, 2021 hack hour.

**Comment by rosteen** [comment]
This has been added in glue-jupyter for all viewers (the "home" button in the screenshot below). Closing.

![Screen Shot 2021-06-28 at 11 40 12 AM](https://user-images.githubusercontent.com/39831871/123664763-a46d6180-d805-11eb-8d06-edb33287beff.png)
