### ISSUE TITLE
NIRISS Parser: Cutout/Zoom in image viewer

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#452]
NIRISS data comes with one image but each spectrum is matched with a certain cutout of that main image. The expected functionality is that when a row is clicked, the image viewer should either show the specified cutout of the image (using RA and Dec) or it should automatically zoom into the image (this will look similar to the cutout).

**Comment by duytnguyendtn** [comment]
Shouldn't this have been closed in #779?
