### ISSUE TITLE
Applying slider redshift to output spectra changes spectral axis values

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#454]
This is the intended behavior for updating the redshift value on a `specutils.Spectrum1D` object, but I think it's not what we want to happen when the Specviz `get_spectra` helper class is used. My understanding of what we really want is to just set the redshift parameter in the output `Spectrum1D` but leave the spectral axis unchanged, so the user could potentially use that redshift to e.g. calculate rest values if desired. 

I think the specutils treatments is actually, even worse, the direct opposite of what we want here: specutils is treating the original wavelengths as the rest values and converting to what they would be at the set redshift, but in our case the original values are redshifted and we would want to convert them back to rest.

I include a demonstration of the difference below.

Current behavior:
```
>>> flux = [1,2,3]* u.Jy
>>> sa = [300, 310, 320] * u.AA
>>> spec = Spectrum1D(flux=flux, spectral_axis=sa)
>>> spec
<Spectrum1D(flux=<Quantity [1., 2., 3.] Jy>, spectral_axis=<SpectralAxis [300., 310., 320.] Angstrom>)>
>>> spec.redshift
<Quantity 0.>
>>>
>>> spec.redshift = 0.56
>>> spec
<Spectrum1D(flux=<Quantity [1., 2., 3.] Jy>, spectral_axis=<SpectralAxis
   (observer to target:
      radial_velocity=125169.63763653308 km / s
      redshift=0.56)
  [468. , 483.6, 499.2] Angstrom>)>
```
What I think we want:
```
>>> spec2 = Spectrum1D(flux = spec.flux, spectral_axis = sa, redshift = 0.56)
>>> spec2
<Spectrum1D(flux=<Quantity [1., 2., 3.] Jy>, spectral_axis=<SpectralAxis
   (observer to target:
      radial_velocity=125169.63763653308 km / s
      redshift=0.56)
  [300., 310., 320.] Angstrom>)>
```

@eteq @camipacifici @PatrickOgle let me know your thoughts, this is a quick fix I just need to know to go ahead and do it.

**Comment by camipacifici** [comment]
I agree with you. The wavelength should not change when setting the redshift of the spectrum. We discussed the option to create functions to bring spectra from observer to rest frame, but this should not happen automatically, and surely not in the wrong direction as seems to be the default behavior now.
Thank you for fixing this!
