### ISSUE TITLE
Model fitting does not provide feedback for successful fits

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#455]
In Specviz:
1. Create Model
2. Click "Fit"
3. Only see warning in traceback: `WARNING: The fit may be unsuccessful`
4. Click "Add to Viewer"
No feedback if it was successful.

**Comment by javerbukh** [comment]
Same thing needs to be done for the Gaussian Smooth plugin.

**Comment by rosteen** [comment]
This was addressed somewhere along the line, there is now a success snackbar message.
