### ISSUE TITLE
Slider redshift not applied to preset line list loaded from notebook

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#475]
Exactly what it says - if you load a preset line list from the notebook, the current redshift from the slider won't be applied to the preset lines on load. They'll still be updated if the slider is moved after they're loaded, but we should fix the initial application to match with the behavior of the other methods of adding/loading lines.

**Comment by pllim** [comment]
I think this has been fixed after all the improvements done by @kecnry . Can you confirm?

**Comment by rosteen** [comment]
I agree, the redshift slider is now greyed out and unusable before loading a list. And if you use it and then load a second list, the redshift is properly applied to the new lines.
