### ISSUE TITLE
Scroll events not passed down to app level in Notebook context in macOS (zoom is broken)

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#486]
Confirmed by @camipacifici @rosteen and myself. When selecting any of the scroll tools in specviz (horizontal, vertical, 2D), using a mouse to try and scroll causes the entire jupyter notebook window to scroll rather than actually zooming in. This behavior was replicated on macOS on Chrome 89.0.4389.90 (Official Build) (x86_64). Interestingly enough, the Windows build of the same Google Chrome build is still functioning as expected.

**Comment by maartenbreddels** [comment]
Managed to reproduce this, and reported upstream: https://github.com/bqplot/bqplot/issues/1304

**Comment by Installka** [comment]
I think the problem still occurs. I have next setup:
Jupyter Lab 3.0.16 running on Windows 7 with bqplot 0.12.27. I tried to use it with:
- Edge 91.0.864.37 (Official build) (64-bit) from Win 7 PC and remotely from Win 10 and macOS 11.4;
- Chrome 91.0.4472.77 (Official Build) (64-bit) from Win 7 PC;
- Safari 14.1.1 (16611.2.7.1.4) remotely from macOS 11.4.

When I run code cell for the first time, everything works fine. But when I use any button under the plot, notebook starts scrolling when zooming plot.
![Web capture_3-6-2021_165211_frolov-sv ec-leasing ru](https://user-images.githubusercontent.com/26421878/120657761-75c1cc80-c48d-11eb-90e7-53f2c71e7846.jpeg)
