### ISSUE TITLE
Issue with scikit-image on installation

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/jdaviz#490]
Not sure what the cause of the issue is but it is known to happen on Mac OS. @PatrickOgle can you link the version of your conda environment and what version number of `scikit-image` that does not work on installation and then the version that does work after running the fix?

Solution for this issue (to be documented in readthedocs):
```
pip uninstall scikit-image
conda install scikit-image
```

**Comment by javerbukh** [comment]
Duplicate of #388 , however closing that issue since this one includes a solution.

**Comment by pllim** [comment]
What is the error exactly? Could be due to some missing non-Python library that `conda` provides but not `pip`.

**Comment by pllim** [comment]
Addressed by #491
