### ISSUE TITLE
spectral_cube warnings on loading JWST s3d data cubes

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#497]
This may be solved when we stop using spectral_cube and start using specutils to load cubes.

WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.
WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.
WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.
WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.
WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.
WARNING: No spectral axis found; header may be non-compliant. [spectral_cube.cube_utils]
WARNING:astropy:No spectral axis found; header may be non-compliant.

**Comment by pllim** [comment]
@PatrickOgle , can you please re-check with the current dev version and see if this is still an issue? Thanks!

**Comment by pllim** [comment]
No longer can issue.
