### ISSUE TITLE
JDAT-1390: Load common image formats (FITS, ASDF), including JWST

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#510]
1. Make sure Imviz can load most common FITS image formats (with WCS and/or ASDF, see 3)
2. Make sure it can load all JWST image formats.
3. Be able to read gwcs or fitswcs (prefer gwcs for JWST)

https://jira.stsci.edu/browse/JDAT-1390

**Comment by astrofrog** [comment]
Here is the documentation on writing custom data loaders: http://docs.glueviz.org/en/stable/customizing_guide/customization.html#custom-data-loaders

GWCS should be usable directly as a glue Data.coords object as it is APE-14 compliant.

**Comment by pllim** [comment]
Note to self:

* Reading ASDF: https://asdf.readthedocs.io/en/stable/asdf/overview.html#reading-files
* Check if it is ASDF-in-FITS: `'ASDF' in hdulist`
