### ISSUE TITLE
JDAT-1397: Remove unused tools

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#529]
There are 3 unused tools that should be removed from `jdaviz` applications:

1. 🗑️ 
2. `X^2`
3. Box with arrow coming out of it.

https://jira.stsci.edu/browse/JDAT-1397

**Comment by astrofrog** [comment]
I don't see these in imviz - can you provide a screenshot?

**Comment by pllim** [comment]
@PatrickOgle opened the original JIRA ticket. I just copied stuff over, so maybe he can clarify.

**Comment by pllim** [comment]
Already fixed in #366
