### ISSUE TITLE
specviz2d fails to load miri s2d file

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#532]
Attempting to load a MIRI s2d file into Specviz2d fails with a missing header keyword error.  It looks like the 2d viewer successfully populates but during the extraction of a 1d spectrum, it fails with `KeyError: "Keyword 'WAVEND' not found."`

This file is from pipeline version `0.16.1` and it may be the case that this is outdated, and/or it's not quite a level 3 science product supported by jdaviz.  But one question I have is if jdaviz is expected to work with intermediate JWST data products, i.e. calibration level 2x and below?

I have the download link for the file in question.

To reproduce:
```
file='/Users/bcherinka/Downloads/jw00623-c1019_t015_miri_clear_s2d.fits'
s = Specviz2d()
s.load_data(spectrum_2d=file)
```
Full traceback
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-fb42f9f6889b> in <module>
----> 1 s.load_data(spectrum_2d='/Users/bcherinka/Downloads/jw00623-c1019_t015_miri_clear_s2d.fits')

~/Work/git/havok2063/jdaviz/jdaviz/configs/specviz2d/helper.py in load_data(self, spectrum_2d, spectrum_1d, spectrum_1d_label, spectrum_2d_label, show_in_viewer)
    131             # Collapse the 2D spectrum to 1D if no 1D spectrum provided
    132             if spectrum_1d is None:
--> 133                 self.app.load_data(spectrum_2d,
    134                                    parser_reference="spec2d-1d-parser",
    135                                    data_label=spectrum_1d_label,

~/Work/git/havok2063/jdaviz/jdaviz/app.py in load_data(self, file_obj, parser_reference, **kwargs)
    312                 # If the parser returns something other than known, assume it's
    313                 #  a message we want to make the user aware of.
--> 314                 msg = parser(self, file_obj, **kwargs)
    315 
    316                 if msg is not None:

~/Work/git/havok2063/jdaviz/jdaviz/configs/specviz2d/plugins/parsers.py in spec2d_1d_parser(app, data_obj, data_label, show_in_viewer)
     47         except ValueError:
     48             flux = u.Quantity(np.sum(data, header['DISPAXIS']-1))
---> 49         step = (header["WAVEND"] - header["WAVSTART"])/len(flux)
     50         spectral_axis = np.arange(header["WAVSTART"], header["WAVEND"],
     51                                   step) * u.Unit("m")

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/header.py in __getitem__(self, key)
    154             keyword = key
    155 
--> 156         card = self._cards[self._cardindex(key)]
    157 
    158         if card.field_specifier is not None and keyword == card.rawkeyword:

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
   1714 
   1715         if not indices:
-> 1716             raise KeyError(f"Keyword {keyword!r} not found.")
   1717 
   1718         try:
```

**Comment by havok2063** [comment]
Also experienced with `jw00623-c1020_t015_miri_p750l_s2d.fits` in pipeline version `0.18.3`.  @rosteen any scope to look into this or shall we push it into the next sprint?

**Comment by havok2063** [comment]
After checking with JWST folks, it seems MIRI fixed slit exposures do not have the `WAVSTART` and `WAVEND` header keywords.  So I think that means its an issue with `Specviz2d`.   Attached is an example provided to me of extracting the default wavelength range, but perhaps there are other mechanisms for extracting it that don't rely on calibration reference files?  
```
For example, if you load a MIRI LRS slit 2D cal product into a data model, you can access the wcs info to give you the sky coords (including lambda) of any pixel:
 
from jwst import datamodels
cal = datamodels.open(‘my_lrs_cal.fits’)
 
ra, dec, wmax = cal.meta.wcs(330, 10)
ra, dec, wmin = cal.meta.wcs(330, 390)
 
Of course that requires you to know (or figure out) ahead of time that the min/max wavelength occurs at pixels 330x390 and 330x10, respectively. So a more general method would be to compute the coords for all pixels and find the min/max wavelength:
 
from gwcs.wcstools import grid_from_bounding_box
x, y = grid_from_bounding_box(cal.meta.wcs.bounding_box)
ra, dec, lam = cal.meta.wcs(x, y)
wmin = np.nanmin(lam)
wmax = np.nanmax(lam)
 
Note the use of “nanmin” and “nanmax”, because pixels for which the WCS isn’t defined will have coords that are NaN.

```

**Comment by havok2063** [comment]
It was also suggested that for the time being `WAVSTART` and `WAVEND` will only be in NIRSPEC fixed slit exposures, but that it's possible down the line they will include a pipeline patch to compute and provide these keywords for other instrument modes.   So one option could be to first check for these keywords, use them if found, otherwise fall back to a more general computation.

**Comment by drlaw1558** [comment]
Indeed, we don't define those keywords in the MIRI assign_wcs code, although for fixed slit it's easy to add it.  That would be harder for intermediate-stage MRS data though, as each file contains two different wavelength ranges with a big gap in between.  Perhaps that doesn't matter though, as I think jdaviz tools at present only work with MRS data once it gets to the cube stage.
