### ISSUE TITLE
MNT: Stop relying on dev glue-jupyter

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#533]
Once glue-viz/glue-jupyter#213 is in a release, we can change the version pin here:

https://github.com/spacetelescope/jdaviz/blob/28557a06654783883729fd5f69ec4ce1dee0d368/setup.cfg#L25

This is a follow-up of #429

**Comment by astrofrog** [comment]
The v0.3 release of glue-jupyter is now in progress, should hopefully be done in a few minutes.

@pllim - once it is on PyPI, would you be happy to check that it works fine and update the dependency list?

**Comment by pllim** [comment]
Yes, that is easy to check via a PR update to `setup.cfg` once it is out. Thanks!
