### ISSUE TITLE
BUG: Imviz panning

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#534]
Follow up of #429: *There is a bug with the panning which I am investigating.* -- @astrofrog

**Comment by astrofrog** [comment]
I think the root cause is https://github.com/bqplot/bqplot/issues/1333

**Comment by pllim** [comment]
Thanks for investigating! Should I re-assign to Maarten?

**Comment by astrofrog** [comment]
Yes please!

**Comment by pllim** [comment]
I cannot seem to do it officially, so pinging @maartenbreddels here instead.

**Comment by astrofrog** [comment]
Looks like @maartenbreddels fixed this in https://github.com/bqplot/bqplot/pull/1339 - I will double check now that this resolves the jdaviz issues.

**Comment by astrofrog** [comment]
Fixed in bqplot 0.12.26
