### ISSUE TITLE
ENH: Imviz "maneuvers"

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#536]
Follow-up of #429: *I don't actually expect users to have to do the maneuvers with changing the reference data in the second viewer etc - we can make this easier and automatic, but this needs more discussion for now as to how we would like it to behave.* -- @astrofrog 

Note from @pllim : I am not sure what this means. I think this will naturally be solved when we try to implement the UI/UX requirements anyway, but since this was explicitly stated in #429, I opened an issue...

**Comment by astrofrog** [comment]
I *think* this has now been fixed as in #429 I made it so all this is automatic. So we should be able to close.
