### ISSUE TITLE
Determine how to programmatically show collapsed/modified versions of data in UI

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#54]
One of the requirements for the cubeviz prototype is the ability to do e.g. smoothing or collapsing of spectra or spectral cubes and showing it in the cubeviz UI. So this issue is to figure out what the programmatic API looks like for doing any kind of analysis that involves collapsing or modifying data. For example, if we are working with a spectral cube in glue, do we get the ``SpectralCube`` object out, use the collapse methods on ``SpectralCube``, then add the result back to glue?

One of the subtleties here will be that if we want this modified data to be linked with the original one, we will likely have to auto-infer links between the data when the collapsed/modified version is added back. I can try and help with this since I've worked on auto-linking in the Qt UI before.

**Comment by nmearl** [comment]
What do you mean by "auto-linking"? Making the data a component of the read-in data object, or just a way to associate it with the data object?

**Comment by astrofrog** [comment]
Sorry for not replying before - by linking I mean making glue aware of the relation between the datasets. If two datasets are linked by their WCS, it means we can overplot datasets - so if we link a collapsed dataset, e.g. a moment map, with its parent dataset, it means that we can then overplot the moment map on top of the original cube. Does this make sense?

**Comment by eteq** [comment]
From an out-of-band discussion with @astrofrog and @nmearl : We ended up concluding we think the best approach is to not implement too much "general" auto-linking magic, but rather to say that the `load_data` method of application objects should do the relevant auto-linking.

E.g., when a cube is loaded via `cubevizapp.load_data('...')`, the spatial axes and spectral axes of all the cube elements should be automatically linked.  If the user wants to go and do something manually with the links afterwards they can, but the default is to just stick with the links that they already made.

**Comment by nmearl** [comment]
@astrofrog would this just involve doing

```python
links = find_possible_links(self.data_collection)
self.data_collection.add_link(links['Some link reference string'])
```

whenever a data set is loaded?

**Comment by duytnguyendtn** [comment]
We certainly have developed our Collapse plugin, and any new data generated (like Unit Conversion) creates a new dataset and adds it to the data drop down. This is probably addressed
