### ISSUE TITLE
BUG: Blank image in Linux Chromium

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#540]
https://get.webgl.org shows a spinning cube on the browser, but I don't see anything when I run the demo notebook from @astrofrog from #429 on RHEL 7 Chromium browser. No error message.

![Screenshot 2021-04-16 171724](https://user-images.githubusercontent.com/2090236/115085001-b4002e00-9ed7-11eb-968b-f223538821bd.jpg)

Red Hat Enterprise Linux Server release 7.9 (Maipo)
Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)

cc @maartenbreddels

**Comment by astrofrog** [comment]
Just to check, did you add the data to the viewer? (A manual interactive step)

**Comment by pllim** [comment]
I was using `jdaviz --layout=imviz ...`, which should have added it automatically? Anyways, I have to remember to check your notebook without #541 and make sure it is not a bug I introduced.

**Comment by astrofrog** [comment]
I don't think the CLI version currently adds the data automatically but I'll check

**Comment by pllim** [comment]
OMG, you are right... I need to click on the hammer icon and then check a checkbox. Both in the notebook and "standalone" version. I had to re-watch your demo video to see what you meant. Not intuitive but also not a bug.
