### ISSUE TITLE
BUG: Extra print out when changing colormap

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#548]
![Screenshot 2021-04-20 155427](https://user-images.githubusercontent.com/2090236/115456508-3b5be300-a1f1-11eb-8c53-4d05188d9807.jpg)

**Comment by pllim** [comment]
@astrofrog , please see glue-viz/glue-jupyter#216

**Comment by astrofrog** [comment]
Merged, so closing this - thanks!

**Comment by pllim** [comment]
I guess it is too soon to have another release? 💭
