### ISSUE TITLE
unable to launch specviz from command line

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jdaviz#552]
I have an extracted JWST pipeline output spectrum from MIRI LRS. In python, I can read it into a Spectrum1D object directly -so the file should be readable by specviz. However when I do 

`jdaviz --layout specviz miri_lrs_slit_pt_nod2_v2_x1d.fits`

on the command line, the browser window launches but shows only the following:

![image](https://user-images.githubusercontent.com/225201/115574585-c55a8900-a28f-11eb-899c-fcb3b951ceb8.png)

**Comment by pllim** [comment]
On my machine (Linux), I sometimes have to minimize it and then show it again for it to finish loading. Not sure if that will also fix your problem. Which browser is this? Try a different browser too by providing `--browser` option.

**Comment by skendrew** [comment]
I'm using Safari. Minimizing did nothing. Tried Firefox and was the same.

**Comment by pllim** [comment]
What about Chrome? Didn't work on Firefox for me either and I don't use Safari but worked on Chrome on Linux.

**Comment by skendrew** [comment]
Tried Chrome and still the same! I'm on a Mac, 10.15.7 (Catalina)

**Comment by pllim** [comment]
Thanks for checking! 😿

**Comment by duytnguyendtn** [comment]
Out of curiosity, if you try to load Specviz without data, does it come up at all?

**Comment by skendrew** [comment]
it does not load, it complains about the lack of a file:

(miricle) sarahkloaner:b77-e2e skendrew$ jdaviz --layout specviz --browser chrome 
Usage: jdaviz [OPTIONS] FILENAME
Try 'jdaviz --help' for help.

Error: Missing argument 'FILENAME'.
(miricle) sarahkloaner:b77-e2e skendrew$

**Comment by skendrew** [comment]
(it does work in a notebook, fwiw. but somewhat buggy.)

**Comment by havok2063** [comment]
I've also experienced the same thing.  Loading jdaviz in desktop mode results in perpetually executing notebook display.  I think I've tried Cubeviz and Specviz in Chrome.

**Comment by pllim** [comment]
`jdaviz --layout=specviz --browser=/path/to/your/chrome-executable-name filename`

Example on Linux:

`jdaviz --layout=specviz --browser=/usr/bin/chromium-browser myfits.fits`

**Comment by havok2063** [comment]
I just tested it again with `jdaviz --layout=specviz filename` and it works for me.

**Comment by skendrew** [comment]
no, sorry, none of them working. it does open the correct browser and a new tab, but always shows the same screen as I put in my original message.

**Comment by havok2063** [comment]
If you open up the browser console (right click, go to Inspect or Developer Tools, click Console tab) and reload the page, do you see any errors or output?

**Comment by skendrew** [comment]
this is from the developer console in Chrome:

Executing cell 1 of 1
:8866/voila/files/favicon.ico:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
voila.js:455 Uncaught (in promise) TypeError: Cannot read property 'kernelChanged' of undefined
    at new so (voila.js:455)
    at new Ys (voila.js:469)
    at getWidgetManager ((index):376)
    at window.init ((index):409)
DevTools failed to load SourceMap: Could not load content for http://localhost:8866/voila/static/voila.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by havok2063** [comment]
what version of Voila do you have installed?  check if it's `voila==0.2.8`.  If so, try downgrading to `0.2.7` with `pip install voila==0.2.7`.  I've had some issues with the recent release of Voila, and this error looks similar to those.

**Comment by skendrew** [comment]
had 0.2.9, downgraded to 0.2.7 and still same.

**Comment by havok2063** [comment]
hmm.  And do you see the same error as before in the developer console?

**Comment by skendrew** [comment]
yes same error

**Comment by havok2063** [comment]
Hi @skendrew we've merged a potential fix for this.  It's not in a release yet, so you'll need to use the latest `main` branch of jdaviz.  Can you pull the latest changes, and upgrade `voila` to the latest `0.2.10`, and try again?  If you still get an error, can you paste the content from the Voila terminal window as well as the browser developer console?

**Comment by skendrew** [comment]
Hi @havok2063 I pip uninstalled jdaviz and then pulled the code from GitHub & installed from there. With Safari I now get a blank screen with 500: Internaal Server Error.

**Comment by skendrew** [comment]
I am trying to use a different browser but this doesn't work anymore in the same way that I did before. If I put ``--browser=chrome`` (the exact same command as I mention in the comments above), the terminal tells me ``69:77: execution error: Can’t get application "chrome". (-1728)`` and no browser opens. I've tried with the full path to the application (/Applications/Google Chrome.app) with same result.

**Comment by pllim** [comment]
I think you need to call the binary executable: https://stackoverflow.com/questions/31083901/how-to-find-the-executable-file-for-open-command-in-mac

**Comment by havok2063** [comment]
@skendrew Hmm.. it looks like it could be an issue where Voila cannot find the correct template to use when rendering the notebook as html.  Are you working in a clean conda environment?   I've had similar issues with this `index.html.j2` for Voila in my conda envs where it was looking in the wrong place.  To resolve it I reinstalled voila in that environment, then deactivated and reactivated the conda env, to clear the conda cache.  Can you try the following :
- run `which voila` and verify that it is pointing to your correct conda environment
- check that you're using `nbconvert` > 6 and `traitlets` > 5
- run `hash -r` in the terminal shell to clear your PATH cache
- or deactivate and reactivate the conda environment   

Could there be a conflicting voila configuration?  You can also try running in the terminal, in the conda env, `voila --Voila.show_config=True` to see if that returns anything odd.  It would return a printout of any custom config parameters.  If it returns nothing, that means the default Voila configuration is being used. 

I just tried creating a clean python 3.8 environment, installing the latest jdaviz git repo, and it worked for me.  It took a moment to start up but the spectrum loaded.
```
conda create -n jtest python=3.8 ipython
conda activate jtest

cd ~/path/to/git/checkout/jdaviz
git pull
pip install -e .

jdaviz --layout specviz ~/Work/jwst/1.1/jw00212-o035_t007_miri_ch2-medium_x1d.fits

[Voila] Using /var/folders/js/s2zfzbv16019vjh0dft_l_w0000263/T to store connection files
[Voila] Storing connection files in /var/folders/js/s2zfzbv16019vjh0dft_l_w0000263/T/voila_5qtawz1c.
[Voila] Serving static files from /Users/bcherinka/anaconda3/envs/jtest/lib/python3.8/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] WARNING | Notebook notebook.ipynb is not trusted
[Voila] Kernel started: 8a320fd6-2966-4ce1-a084-3effee9c9e5c
WARNING:tornado.general:403 GET /voila/files/favicon.ico (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/favicon.ico (::1) 1.47ms
```
I also tried `jdaviz --layout specviz --browser=chrome ~/Work/jwst/1.1/jw00212-o035_t007_miri_ch2-medium_x1d.fits` and that worked as well.

**Comment by skendrew** [comment]
I didn't try all of that but I created the clean condo environment and then it did work with safari. I haven't got time to sort out the different browser options right now, but it looks like the basic issue of not launching is fixed!

**Comment by havok2063** [comment]
Ok, great!  I'm glad it's working now.  When in doubt burn it down and start again!
