### ISSUE TITLE
Examining spectra

### ISSUE THREAD

**Issue by aaastorrs** [spacetelescope/jdaviz#567]
Is there a way in SpecViz to read out the mouse x and y positions, preferably in units being used to display the spectra? An added bonus would be to record the position when the mouse is clicked, perhaps in a user-designated file.

Thanks!

Alex Storrs
`astorrs[at]towson.edu`

[🐱](https://jira.stsci.edu/browse/JDAT-1430)

**Comment by pllim** [comment]
> record the position when the mouse is clicked

Just thinking aloud and mostly a question for other devs: What do you think about a single-wavelength region (equivalent to single-pixel region in Imviz but for XRange) on special click (or alt+click) events? Then to "record the positions," we can simply use existing API for export regions.

**Comment by kecnry** [comment]
@pllim - I like that idea in general, but would like to see it as a dedicated plugin that logs the mouseover information to a table (which can then be pulled into the notebook or written to a file), rather than "abusing/overloading" subsets [:cat:](https://jira.stsci.edu/browse/JDAT-2873)

**Comment by pllim** [comment]
@aaastorrs , in the upcoming v3.2, Specviz should display the values under cursor position (not necessary the spectrum but rather where your actual cursor is). We will work on improving that in the future and also will think about the "record" part of your request. Thank you for your patience!

**Comment by pllim** [comment]
We also have Markers plugin now, so I think this issue is resolved. Thanks!
