### ISSUE TITLE
[BUG] Cubeviz: Custom Contour Scientific Notation Entry Autocorrection

### ISSUE THREAD

**Issue by PatrickOgle** [spacetelescope/jdaviz#574]
**Describe the bug**
When trying to enter custom contours in scientific notation in the layer tab, the string
'1e+1'  autocorrects to 10.

**To Reproduce**
1. Go to cube viewer
2. Click on Tools: Gear: Layer
3. Turn on Contours
4. Click wrench icon for custom contour entry
5. Type '1e+1' or '1e+14'
6. These autocorrect to '10' and '104' respectively
7.  Workaround: type nonsense character at beginning of string, like '#1e+14' then delete the '#'

**Expected behavior**
Don't autocorrect scientific notation

**Screenshots**
![CustomContour_scientificnotation](https://user-images.githubusercontent.com/44263689/116268692-8d4dbd00-a74b-11eb-95ff-13be1bd995b8.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Safari
 - Jupyter: 
 - jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : 5.0.3
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5

**Package versions (please complete the following information):**

glue-jupyter 0.2.2
glue-astronomy 0.1
echo 0.5
ipyvue 1.5.0
ipyvuetify 1.6.2
ipysplitpanes 0.1.0
ipygoldenlayout 0.3.0
voila 0.2.7
vispy 0.6.6
Jdaviz 1.1

**Additional context (e.g. data files)**

**Comment by maartenbreddels** [comment]
https://github.com/glue-viz/glue-jupyter/pull/233 should fix this.
