### ISSUE TITLE
[FEAT] Imviz: Default percentile/constrast/bias should better show image details

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#577]
### Description

Right now, the default percentile is "min/max," which does not show details on astronomical images well. Maybe the default should be 95% ?

Currently, this is what you see when `jbt7a3020_drz.fits` (some HST Drizzled product) loads:

![Screenshot 2021-04-29 111235](https://user-images.githubusercontent.com/2090236/116574738-04b25680-a8dc-11eb-9f8d-be6db1a8a486.jpg)

Would be nice if it shows something like this without me having to adjust percentile (though individual preferences might differ):

![Screenshot 2021-04-29 111315](https://user-images.githubusercontent.com/2090236/116574884-257aac00-a8dc-11eb-8346-41fb49664c18.jpg)

[🐱](https://jira.stsci.edu/browse/JDAT-2512)

**Comment by pllim** [comment]
Or maybe constrast/bias has a role to play in this too.

**Comment by astrofrog** [comment]
Yes we could set a default percentile of 99.5 or 99%?

**Comment by pllim** [comment]
We could, though making that decision is probably done by a Product Owner?

**Comment by pllim** [comment]
This came up again recently. User was frustrated by the min/max default and asked for zscale.
