### ISSUE TITLE
Dependency incompatibility: Decorator

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#595]
I got the following error when installing Jdaviz from a clean environment:
```
ERROR: networkx 2.5.1 has requirement decorator<5,>=4.3, but you'll have decorator 5.0.7 which is incompatible.
```
I had to specify this in [my Mosviz jwebbinar requirements file](https://github.com/spacetelescope/jwebbinar_prep/blob/main/jdat_session/requirements.txt) for reproducibility's sake. This is similar to #423. We solved that by introducing a dependency line for `idna` in our `setup.cfg`, but I don't really like that. What happens if the dependency changes? What if it's not needed anymore? Will we remember to back and check?

It seems like this is an issue that's happening in our dependencies. Is there something we can do to better mitigate this, or better yet protect ourselves from it? In both of these situations, installing the appropriate version that meets the spec works, and I'm not aware of any packages we depend on that have an contradictory requirement on either `idna` or `decorator`. I wonder how larger python projects manage issues like this.

On another note, @pllim I think adding a generic "Jdaviz Framework" issue template would help us capture issues that aren't tool specific, like this one

**Comment by duytnguyendtn** [comment]
For the Jdaviz bug template, I see your point. I imagine most feature requests, even if it ends up being useful cross-tool, would be proposed within the context of an existing tool from the user side. That being said, I could also see difficulty handling requests from users who want to develop their own tools and have some infrastructure requests? (i.e. #82?)

From what I understand, the pip resolver doesn't actually use the requirements file to install from PyPI, right? I haven't been able to upload just a requirements file, and have it "just install" (either via `pip install .` or `pip install X` from PyPI). I've always had to include a setup.py, setup.cfg, or something else (pipenv, poetry, etc.) in order to get it to work. As much as I would love to ask users to always install fresh, in reality, even I'm at fault for this (though getting better!), so I'd like to try to make `Jdaviz` as resilient as possible 🤷

**Comment by pllim** [comment]
> pip resolver doesn't actually use the requirements file to install from PyPI, right?

Depends on how you call it, though even if you specify `-r`, I vaguely remember a problem about how the different conflicting pins might not be resolved in the same order every time, resulting in different results for different people (maybe they fixed it but I don't know). If you are using `conda` anyway, the `conda` env file might be a more "reliable" way to go (YMMV).

> resilient

Would be nice but given the heavy development across the stack, probably too early for that.

> template

This is probably a separate issue. Or if you already have something in mind, a PR is even better. 😸

**Comment by duytnguyendtn** [comment]
> a PR is even better. 😸
Point taken 😉

**Comment by pllim** [comment]
Is this still a problem?

**Comment by pllim** [comment]
I am just going to close this since we haven't seen it in a while.
