### ISSUE TITLE
Increase subset default thickness

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/jdaviz#610]
In a number of different places, users have mentioned not being able to see the subset selection. We should increase the subset highlight thickness to make it more apparent

**Comment by rosteen** [comment]
It should probably be "whatever the main data line width is" or that +1, since the problem has mostly been that I increase the data width in a demo but forget to do so for the subset.

**Comment by duytnguyendtn** [comment]
Closed by #994
