### ISSUE TITLE
MNT: Unpin jwst when their fix is released

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#638]
This is a follow up of #637 (shown as not merged but it was merged in 31155596df335f3e8e41ef582cd928a4885f2563).

@jdavies-st or @eslavich will inform us when this release is out.

https://github.com/spacetelescope/jdaviz/blob/31155596df335f3e8e41ef582cd928a4885f2563/setup.cfg#L53

**Comment by pllim** [comment]
@jdavies-st -- any update?

**Comment by jdavies-st** [comment]
`jwst 1.2.1` with the fix was released this morning.  👍
