### ISSUE TITLE
plots do not appear in jupyter lab

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#661]
On the latest `main`, if I make a fresh install by making a new venv and then doing `pip install -e .` in the source directory, jdaviz loads just fine and yields in `jupyter notebook` *or* `voila`, yields:
![image](https://user-images.githubusercontent.com/346587/121071354-d3139180-c79d-11eb-97fb-5087bc8a782e.png)
whiche is just what it should.  However, in the same environment, jupyter lab yields:
![image](https://user-images.githubusercontent.com/346587/121071779-651b9a00-c79e-11eb-894f-7603d9dfae5b.png)

which is missing the plot...

**Comment by eteq** [comment]
Oh, this is informative - the following appears in my browser javascript console: 

``Uncaught (in promise) Error: Module bqplot, semver range ^0.5.29 is not registered as a widget module``

so it's probably an issue with the bqplot extension

**Comment by eteq** [comment]
(also, definitely related to #327)

**Comment by pllim** [comment]
Did you try all the magics mentioned in bqplot/bqplot#884 ?

**Comment by eteq** [comment]
I just tried the dev version of `bqplot` with no luck.  But @maartenbreddels mentioned out-of-band there was a bqplot release issue that's being resolved there with a post-release

**Comment by eteq** [comment]
Aha, it's fixed if I do `pip install bqplot==0.12.27`, confirming that's the underlying problem.  Probably not worth pinning since it should also be fixed in  bqplot 0.12.28post1, but if anyone needs it *right now* the above is the fix.

**Comment by pllim** [comment]
Neither `bqplot` 0.12.27 nor 0.12.29 work for me. I get `Error displaying widget: model not found`.
