### ISSUE TITLE
[BUG] Imviz tiling bug: Tile closing roulette

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#663]
**To Reproduce**

1. Start up Imviz app.
2. Load some data.
3. Create a new sub-window or several.
4. Move them around.
5. Pick a lucky sub-window, click "x" to close it.
6. See a random number of sub-windows also closed.

**Expected behavior**

Only the sub-window being closed is closed.

**Additional context (e.g. data files)**

This is a follow-up of #521 .

[🐱](https://jira.stsci.edu/browse/JDAT-1541)

### TODO

- [x] Have other devs confirm this bug.
- [x] Ask SME how to fix.

**Comment by javerbukh** [comment]
Can confirm that I see the same behavior.

**Comment by astrofrog** [comment]
It looks like the tab name is set in container.vue:

```
    <gl-component
      v-for="(viewer, index) in stack.viewers"
      :key="index"
      title="Test"
      :tab-id="viewer.id"
      @resize="$emit('resize')"
      @destroy="$emit('destroy', viewer.id)"
```

We should probably have viewers have a name or label property in the Python code we can ensure is unique and then see if that helps.

However the issue might also be related to the ``@destroy`` above - maybe somehow the ID is the same for all viewers? (should check)

**Comment by pllim** [comment]
Where is the Python code that actually connects to `viewer` here, @javerbukh ?

https://github.com/spacetelescope/jdaviz/blob/1aa0dce1dd2d22657e9550735e55dcd2aee0025e/jdaviz/container.vue#L19

**Comment by javerbukh** [comment]
Maybe [here](https://github.com/spacetelescope/jdaviz/blob/2dfb48775db9b957b6dc0c1b52fe0d7b6a6786bd/jdaviz/app.py#L835)? I'm not entirely sure though.

**Comment by astrofrog** [comment]
I'm on my phone so can't check but on line 848 of that file you linked to @javerbukh items are being removed from the list during iteration over it which is likely to cause issues and might be the root cause here. You should add [:] at the end of line 848 to make sure the list is copied for the purposes of iteration.

**Comment by astrofrog** [comment]
Same for line 847 - basically you need to be careful when removing items from a list you are iterating over.

**Comment by pllim** [comment]
OK I'll look into it. Thanks!

**Comment by pllim** [comment]
`[:]` does not fix the problem. But if the *idea* is to loop through a copy, see #673 and please tell me how to fix it properly. I have no idea how this app thing works.

**Comment by pllim** [comment]
To answer an earlier question, the IDs are different but they are indeed called twice as mentioned in

https://github.com/spacetelescope/jdaviz/blob/e0efb4f2f7703b869437bd03feb9701b85a93a0b/jdaviz/app.py#L868

```
cid 67b9e287-5bc9-40b0-b318-8ebafda2e2b8
cid 67b9e287-5bc9-40b0-b318-8ebafda2e2b8
```
```
cid bc87d4ae-c1cf-4cfb-9554-ae2fa60374f9
cid bc87d4ae-c1cf-4cfb-9554-ae2fa60374f9
```
```
cid 09dc786b-4ea3-4c2f-8de0-edd113245b5d
cid 09dc786b-4ea3-4c2f-8de0-edd113245b5d
```

**Comment by pllim** [comment]
Turns out it was the over-eagerness in deleting "empty" stack items. Has nothing to do with lack of copying.
