### ISSUE TITLE
Extraneaous white padding

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#666]
When using jdaviz in voila, it looks like there is some extraneous padding on the right:

![Screenshot_2021-06-08_16-24-28](https://user-images.githubusercontent.com/314716/121213671-599ba200-c876-11eb-9129-57da9bc6e781.png)

It actually looks like there is some extra padding inside each tab which could be removed, as well as to the right of the app.

cc @mariobuikhuizen

**Comment by mariobuikhuizen** [comment]
The padding around the images looks to be in bqplot:
<img width="990" alt="Screenshot 2021-06-08 at 21 05 30" src="https://user-images.githubusercontent.com/46192475/121249947-76030300-c8a5-11eb-9d6f-51adf17c7716.png">

Tweaking top, width, height and translation in devTools removes the padding:
<img width="996" alt="Screenshot 2021-06-08 at 21 10 03" src="https://user-images.githubusercontent.com/46192475/121249769-3b996600-c8a5-11eb-9467-6da3339d79a6.png">

Maybe @maartenbreddels knows how to change this in bqplot.

**Comment by pllim** [comment]
Fixed in #671
