### ISSUE TITLE
MNT: Unpin glue-jupyter maxversion 0.5 when region handling is fixed upstream

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#677]
This is a follow-up of #675 . Once fixed, we can revisit a patch similar to #664 .

https://github.com/spacetelescope/jdaviz/blob/e0efb4f2f7703b869437bd03feb9701b85a93a0b/setup.cfg#L26

**Comment by pllim** [comment]
Steps to reproduce:

1. Install `glue-jupyter` 0.6 and dev version of `jdaviz`.
2. Fire up a viewer (say, Imviz).
3. Load an image.
4. Draw a region.
5. See how the region disappears instead of turning from grey to red.

**Comment by astrofrog** [comment]
Ah yes I can reproduce - working on it!

**Comment by astrofrog** [comment]
This should hopefully be fixed in glue-jupyter v0.6.1
