### ISSUE TITLE
voila version of jdaviz does not work on WSL2

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#702]
To reproduce:

1. Fire up WSL2 on Windows 10.
2. Set up your env there, etc.
3. Run `jdaviz --layout=imviz <filename>`.
4. See error similar to https://github.com/voila-dashboards/voila/issues/773#issuecomment-868593863 .

There is no problem running on Jupyter notebook or lab outside of `voila`.

**Comment by rosteen** [comment]
We switched from using Voila to Solara, so I'm closing this.
