### ISSUE TITLE
Circular selection plugin not picked up

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#73]
When I try the latest developer version of jdaviz I see the following in the web console:

```
Error: "Could not process update msg for model id: edb3a595a5764d80aae093c1e246bb4f"
    _ utils.js:119
utils.js:119
Class BrushEllipseSelectorModel not found in module bqplot-image-gl@^0.2.0
```

I don't see this when using plain notebooks, just when using jdaviz.

cc @maartenbreddels @nmearl

**Comment by nmearl** [comment]
@astrofrog is this fixed in the latest version? I'm not seeing the issue on my end.

**Comment by maartenbreddels** [comment]
I think it requires version 0.4, 0.2 is too old for sure. Cheers, Maarten

(from mobile phone)

**Comment by rosteen** [comment]
Pretty sure this has been resolved for a while, closing.
