### ISSUE TITLE
[FEAT] Mosviz: have mosviz zoom in on and center the view on the slit when the image is selected

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#739]
When a table row is selected, instead of just showing the image fully as it is, mosviz should use the wcs in the image to center on the slit and re-scale the view to match the range of the 2d spectrum.  Something like this should extract the boundaries of the 2d spectrum:

```
spcu = mosviz.app.get_viewer('whichever is the 2d viewer').data()[0]
spcu.wcs.calc_footprint() 
# the above is supposed to yield a len-4 skycoord.  When I tested it right now, it didn't work, but that might change when we migrate from spectral-cube?  at any event, an alternative is:
corner1 = spcu.wcs.pixel_to_world(0,0,0)
corner2 = spcu.wcs.pixel_to_world(n,0,0)
corner3 = spcu.wcs.pixel_to_world(0,m,0)
corner4 = spcu.wcs.pixel_to_world(n,m,0)
```
then use those corners to create a bounding "box" for the slit, and convert that to a square-by lengthening the short axis to match the long one.  Then zoom the image into that box using its wcs.

If the image *has no* wcs, the current behavior of just showing the image makes sense (the implicit assumption then is that its a sensible cutout)

**Comment by pllim** [comment]
Also see #754
