### ISSUE TITLE
The specviz documentation does not sufficiently explain how to zoom

### ISSUE THREAD

**Issue by janerigby** [spacetelescope/jdaviz#745]
The specviz documentation here: https://jdaviz.readthedocs.io/en/latest/specviz/displaying.html
explains how to zoom using a scroll wheel.  It does *not* explain how to zoom if you don't have a scroll wheel, because you're on a laptop for example.  Nor does it explain how to use the zoom-in-x-only, zoom-in-y-only buttons.  I'm pressing them, I'm trying different click and drag combos, and different mouse buttons, and nothing works.  

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Firefox
 - Jupyter: 
 - jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.0
ipython          : 7.19.0
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

**Package versions (please complete the following information):**

Darwin-19.6.0-x86_64-i386-64bit
Python 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55) 
[Clang 11.0.0 ]
Numpy 1.20.3
astropy 4.2.1
specutils 1.3
spectral-cube 0.5.0
pyyaml 5.3.1
click 8.0.1
asteval 0.9.25
idna 2.10
traitlets 5.0.5
bqplot 0.12.30
bqplot-image-gl 1.4.3
glue-core 1.0.1
glue-jupyter 0.7
glue-astronomy 0.1
echo 0.5
ipyvue 1.5.0
ipyvuetify 1.8.0
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.2.10
vispy 0.7.3
Jdaviz 1.1

**Additional context (e.g. data files)**

**Comment by pllim** [comment]
Hello! It is my understanding that some discussions have happened offline.

For future reference: "We are working on the zoom feature and the best way if someone encounters problems with it is to zoom programmatically..."

**Comment by pllim** [comment]
I think @orifox has clarified this in recent doc updates.
