### ISSUE TITLE
Add a context/vision/high-level intro section in the jdaviz docs

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#75]
Just what it says on the tin... There needs to be words at the top that say *what* jdaviz is about, how it relates to the older viz tools, glue etc.

**Comment by eteq** [comment]
Also possibly tied with this (or *could* be broken out as a separate issue?): basic install instructions

**Comment by eteq** [comment]
#79 did the basic install instructions and a single-sentence, but I think this needs just a bit more context/vision to be considered closed.

**Comment by rosteen** [comment]
@eteq Would you consider this issue addressed by the current state of the docs?

**Comment by eteq** [comment]
Yeah, I think this is fine.  It doesn't exactly have the glue connection but I'm not sure that it needs to now that I think about it.
