### ISSUE TITLE
Clarify docstring for share_image in Mosviz

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#772]
This is a post-hoc review suggestion from #757 - basically 
https://github.com/spacetelescope/jdaviz/pull/757/files#r683624094 .  This is a relatively minor thing because it's basically a developer-only function, but leaving an issue so we don't forget: it could be clearer what the difference is between e.g.  `share_image=1` and `share_image=2` in the `mos_image_parser` function.

cc @rosteen

**Comment by pllim** [comment]
I think I finally understand it... I'll submit a quick PR.
