### ISSUE TITLE
[BUG] Imviz: Contrast/bias mouse control misbehaves if layer options open

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#791]
**Describe the bug**
In testing #775 I noticed that if I opened the viewer layer options (I wanted to see the bias/contrast sliders move while I was using the mouse tool), the mous click and drag functionality started misbehaving. Almost like it was laggy, or there was a feedback loop happening between the clicking and dragging on the viewer and the sliders in the layer options. I suspect that this was an existing issue, not directly related to #775, so I opened this issue separately from that PR. 

EDIT: Blocked by

* glue-viz/glue-jupyter#255

**To Reproduce**
1. Run the ImvizExample notebook to get data in the viewer
2. Open the viewer tools and click the contrast/bias click-and-drag tool
3. Open the Layer options (make sure the displayed layer is selected
4. Click and drag on the image and see that the contrast.bias bounce around instead of changing smoothly 

**Expected behavior**
I think the simplest solution might be to disable the tool if the layer options are opened - this is what happens in the other direction, if you have the Layer options open and click on the tool, the layer options close.

**Desktop (please complete the following information):**
 - Mac
 - Browser: Firefox
 - 
**Package versions (please complete the following information):**
Numpy 1.20.3
astropy 4.2.1
specutils 1.3.dev121+gf0686ed0
glue-core 1.0.1.dev81+g5978a927
glue-jupyter 0.7
glue-astronomy 0.2

[🐱](https://jira.stsci.edu/browse/JDAT-1674)

**Comment by pllim** [comment]
You labeled this as Mosviz bug. Was that a mistake?

**Comment by pllim** [comment]
A more general fix is to have Layers disable all the tools when it is opened. I think Layers are actually from `glue-jupyter`, so I am marking this as needing upstream fixes.

**Comment by rosteen** [comment]
Whoops, it was indeed a mistake.
