### ISSUE TITLE
[FEAT] Cubeviz: add a way to apply the model-fitting plugin to part of a cube

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#799]
Right now the "apply to cube" button on the model-fitting plugin operates on the whole cube.  In some out-of-band discussion with @orifox and @rosteen the idea came out to have a way to "cut" the cube before doing the "apply" step.  My thinking is that the easiest way to do this might be a dropdown that is either "no cut" or any of the subsets. Then that subset is used just for it's left and right bounds to cut the spectrum before applying the model.

This is mainly thinking about use cases like line-fitting where the model is nonesense far from the line.

**Comment by pllim** [comment]
Ops, sorry. The close button was right behind the Slack call button. 😆

**Comment by rosteen** [comment]
This seems to be about selecting a spectral subset, which one can now do for cube fitting. Can this be closed?
