### ISSUE TITLE
[BUG] Mosviz: 1D/2D spectrum viewer x-axis links are buggy

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#802]
### Description
The Mosviz helper class has methods that update the x-axis of the 1D spectrum viewer when the 2D viewer is updated (via panning or zooming) and vice-versa. This mostly works at the moment, but the warning I put in to tell the user not to pan too far away from the data is getting too easily triggered for some reason, to the point that it sometimes ends up constantly flashing on the screen while using Mosviz. I suspect that it may be due to the axis-syncing triggering too aggressively when a new row is clicked and trying to sync unrelated data. There is also a small chance that this is a cause of the 2D data sometimes not loading/displaying correctly in the 2D spectrum viewer. This issue is to improve the spectral axis syncing code to ensure that the warning does not display when not needed, and to ensure that this isn't interfering with other functionality in the app. 

Reproducing the bug should be as simple as running the MosvizNIRISSExample notebook and clicking on a couple rows of data. 

A screenshot of the over-eager warning is attached:
![Screen Shot 2021-08-24 at 10 56 43 AM](https://user-images.githubusercontent.com/39831871/130640910-bbed010b-dfb1-43db-bb9e-d4ce1f02453f.png)

### Additional context

[🐱](https://jira.stsci.edu/browse/JDAT-1680)

**Comment by pllim** [comment]
Are these related?

* astropy/specutils#852
* #801

**Comment by pllim** [comment]
@astrofrog said something about how the 2D spectrum viewer only needs to find out which pixels correspond to the 1D spectrum viewer wavelength limit and set it accordingly in pixel space.

**Comment by ojustino** [comment]
I'll note that this is an equal-opportunity bug: I see the same with `MosvizExample.ipynb` and another NIRSpec notebook Patrick made for a Mosviz hack hour.
