### ISSUE TITLE
[BUG] Mosviz: Region selection in the spectrum viewer is broken

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#810]
**Describe the bug**
Selecting a spectral region in the 1D spectrum viewer results in no region apparently being applied in the viewer. However, if you then click on the Subset menu (the one that is "create new" by default), you can see that not just one but multiple subsets have been created there. See the screenshot below for an example - in that screenshot I had made one spatial subset in the image viewer, which worked, then attempted to make a spectral subset and then moved the gray box once or twice.

I believe that the multiple subsets showing up in the Subset menu is because it is creating a new subset every time the gray box is dragged around after initially clicking and dragging with the x-range selector. This action should be editing the subset initially created, not creating new ones. I managed to trigger this behavior once in the image viewer as well, but it seems to be more easily triggered in the spectrum viewer.

**To Reproduce**
1. Run one of the Mosviz example notebooks
2. Try to select a spectral region in the 1D spectrum viewer with the x-range selection tool
3. After clicking and dragging to create the region selection, click the gray region and drag it around a few times 
4. See that it's broken as heck

**Expected behavior**
The x-range selection tool can be used to create a spectral region.

**Screenshots**
![Screen Shot 2021-08-25 at 10 45 17 AM](https://user-images.githubusercontent.com/39831871/130812859-0599591a-2959-4ee8-8665-a18e8f527316.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome 88, safari 22]
 - Jupyter: [run "jupyter --version"]

**Package versions (please complete the following information):**

macOS-10.14.6-x86_64-i386-64bit
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ]
Numpy 1.20.3
astropy 4.2.1
specutils 1.3
spectral-cube 0.5.0
pyyaml 5.4.1
click 8.0.1
asteval 0.9.23
idna 2.10
traitlets 5.0.5
bqplot 0.12.30
bqplot-image-gl 1.4.3
glue-core 1.0.1.dev88+ged71979f
glue-jupyter 0.6.dev56+gd1246a3
glue-astronomy 0.2
echo 0.5
ipyvue 1.5.0
ipyvuetify 1.7.0
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.2.10
vispy 0.6.6
Jdaviz 1.2.dev431+g68cc2b0.d20210819

**Comment by pllim** [comment]
@astrofrog , could this be a side effect of #708 , which was put in for Imviz?

**Comment by havok2063** [comment]
A related, or possibly duplicate, issue is https://github.com/spacetelescope/jdaviz/issues/776, regarding the same thing in Specviz2d.

**Comment by astrofrog** [comment]
I will investigate tomorrow

**Comment by rosteen** [comment]
Closing this since it was resolved, although note that a similar bug is being caused again somehow in the PR linked above.
