### ISSUE TITLE
Enable nitpicky mode in docs building

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/jdaviz#812]
Currently the two following lines are commented out in conf.py for the docs:

```
# nitpicky = True
# nitpick_ignore = []
```

We should ideally uncomment these and fix any warnings that come up and make sure we build the docs such that it will error if any warnings are emitted - this ensures that any intersphinx links are correct and is much easier to do earlier on in a project than later on - the more we wait to enable it the more of a pain it will be to fix all the warnings in one go 😄 

[🐱](https://jira.stsci.edu/browse/JDAT-1686)

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JDAT-1686](https://jira.stsci.edu/browse/JDAT-1686)._

**Comment by stscijgbot-jwql** [comment]
_This issue is tracked on JIRA as [JDAT-1740](https://jira.stsci.edu/browse/JDAT-1740)._

**Comment by stscijgbot-jwql** [comment]
_Comment by [Pey-Lian Lim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lim) on [JIRA](https://jira.stsci.edu/browse/JDAT-1740?focusedCommentId=549474#comment-549474):_

Huh... I think this is a duplicate.
