### ISSUE TITLE
specviz load data via API fails

### ISSUE THREAD

**Issue by kaya4me2** [spacetelescope/jdaviz#839]
Following instructions one page 5 of jdaviz.readthedocs.io/en/latest/pecviz/import_data.html there seems to
something missing as initiating from inside a juypter notebook: 

specviz = SpecViz()

does not seem to initiate the app window in the notebook, that will load the user defined spec1d  with the

specviz.load_spectrum(spec1d)

the spec1d array is created from reading in a user created ascii file with 3 columns, wavelength, flux, uncertainty in
the usual spectultils fashion.

note that insinuating a jdaviz app window with in the notebook environment does work, but the IMPORT+ fails
when attempting to read the file directly.

Is the code snippets presented in the documentation correct?

**Comment by pllim** [comment]
Is the doc at https://jdaviz--832.org.readthedocs.build/en/832/notebook/import_data.html clearer for you? See #832

**Comment by pllim** [comment]
Update: #832 should solve the original load data error message caused by incomplete documentation. Other issues will be tracked at #847 and #848 separately. Thanks!
