### ISSUE TITLE
Add Documentation on loading Jdaviz uncertainties

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#847]
As asked in https://github.com/spacetelescope/jdaviz/pull/832#issuecomment-914581684 . @javerbukh said something about `myinstance.app.get_viewer("spectrum-viewer").show_uncertainties()`. This needs to be documented.

Also see #839 .

[🐱](https://jira.stsci.edu/browse/JDAT-1742)

**Comment by camipacifici** [comment]
This can be achieved with
plotopt = viz.plugins['Plot Options']
plotopt.uncertainty_visible = True

Do we need anything else?

**Comment by pllim** [comment]
With the new API, yes, that might be all we need.

**Comment by pllim** [comment]
Hopefully https://github.com/spacetelescope/jdaviz/pull/1884 would resolve this. Please have a look. Thanks!
