### ISSUE TITLE
Specviz Y-axis showing all zeros

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#848]
As reported in https://github.com/spacetelescope/jdaviz/pull/832#issuecomment-914581684 and by @orifox .

Also see #839 .

[🐱](https://jira.stsci.edu/browse/JDAT-1743)

**Comment by javerbukh** [comment]
Related to #328

**Comment by pllim** [comment]
Is #142 also related?

**Comment by javerbukh** [comment]
Yes!
