### ISSUE TITLE
[BUG] Mosviz example notebook is broken

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#851]
As reported in https://github.com/spacetelescope/jdaviz/pull/843#issuecomment-915578705 .

To reproduce this, simply run the Mosviz example notebook in this repo.

**Comment by javerbukh** [comment]
@pllim This may not work for this issue but putting it out there for posterity, can you run rm -R mosviz_nirspec_data_0.3/ in your temp directory? That will remove a previous version of that directory that contains a different number of images from spectra.

**Comment by rosteen** [comment]
I think we need to update the zip file, I deleted mine to make sure I had an up-to-date copy and it still doesn't have the same number of images as spectra. @javerbukh I thought I you had already done that - did we just not update the link in the notebook?

**Comment by rosteen** [comment]
Wait, never mind - I'm wrong, there are the right number of fits images there. Looks like maybe I did break it, I guess there are more extensions in those files that are now getting loaded? I'll investigate further. Might need to associate the same image with every extension in the spectrum file.

**Comment by rosteen** [comment]
Ok, after all that it turns out @javerbukh's first comment was correct - this was due to having the older dataset cached. I had to remove the temp directory and then download the file with `cache=False`, then the notebook works. So a new user wouldn't see any problems. I think we can close this.

**Comment by pllim** [comment]
I just downloaded new tarball but the filenames look weird:

![Screenshot 2021-09-09 120210](https://user-images.githubusercontent.com/2090236/132721360-652a74a5-f107-42ec-9bf9-57f3c5ec7770.jpg)

**Comment by pllim** [comment]
Also weird how the notebook didn't crash before with the same files. Was it just ignoring the mismatch?

**Comment by pllim** [comment]
Weird names aside, and the fact that some images appear as all black (no data?), it does load now.
