### ISSUE TITLE
jdaviz import very slow (when not in GUI mode)

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#881]
Did this for `main` branch around the time before 2.0 release:

```python
In [1]: %time import jdaviz
```
```
CPU times: user 2.43 s, sys: 834 ms, total: 3.26 s
Wall time: 1min 5s
```

@kecnry confirmed it, "I get about the same, and it was even worse on the first import on a fresh install."

@rosteen confirmed it, "It did just take me 2.6 seconds to import Specviz."

[🐱](https://jira.stsci.edu/browse/JDAT-1772)

**Comment by astrofrog** [comment]
Running:

```
python -X importtime -c "import jdaviz" 2> out.log
tuna out.log
```

![Screenshot from 2021-09-16 15-31-07](https://user-images.githubusercontent.com/314716/133632202-19a0f35d-b12a-49c8-8006-d2d8b6fec1e3.png)


doesn't seem to show a single culprit - it's more that e.g. specutils takes 0.4s to import, astropy and glue-related stuff similar and so on.

**Comment by pllim** [comment]
Looks like the refactoring in https://github.com/spacetelescope/jdaviz/pull/1681 fixed this mostly. It went from many seconds to like 2 seconds, which I can stand.
