### ISSUE TITLE
Implement sub-set cube collapsing

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#89]
The cube collapse plugin currently collapses along the full cube instead of the selected subset.  For many/most use cases, it's more desirable to use the subset (this is already implemented in glue we think, but not exposed in the UI).

Probably it also makes sense to have the "most recent" subset auto-selected since that's a pretty natural user workflow (as opposed to defaulting to the full cube and making them click down to the subset)

**Comment by rosteen** [comment]
This has been implemented, closing.
