### ISSUE TITLE
jdaviz does not display content

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#91]
The latest pull of jdaviz repo for me does not render content when I try to test it.  Are there other dependencies that I need to install/update that are not yet documented?  I created a fresh conda environment and installed jdaviz
```
conda create -n testviz python=3.7 ipython
conda activate testviz
cd /git/repo/jdaviz
pip install -e .
```
When I run `jdaviz --layout=cubeviz manga-7495-12704-LOGCUBE.fits` or load the `notebooks/Example.ipynb` in jupyter, I get empty content.  

<img width="1674" alt="Screen Shot 2020-04-15 at 12 08 58 PM" src="https://user-images.githubusercontent.com/1836302/79360504-04822b80-7f12-11ea-8a77-7ecfb23b3ccd.png">
<img width="1048" alt="Screen Shot 2020-04-15 at 12 09 22 PM" src="https://user-images.githubusercontent.com/1836302/79360505-051ac200-7f12-11ea-97e7-f11b8ed91b7d.png">

The console throws a bunch of errors regarding `consle is not defined` coming from `goldenlayout.js`
```
vue.min.js:6 ReferenceError: consle is not defined
    at stateChanged (eval at Ya (vue.min.js:6), <anonymous>:3:1160)
    at He (vue.min.js:6)
    at a.n (vue.min.js:6)
    at He (vue.min.js:6)
    at a.e.$emit (vue.min.js:6)
    at Object.<anonymous> (vue-golden-layout.js:1335)
    at s.items.Root.emit (goldenlayout.js:255)
    at s.items.RowOrColumn._propagateEvent (goldenlayout.js:3643)
    at s.items.RowOrColumn.emit (goldenlayout.js:265)
    at s.items.RowOrColumn._propagateEvent (goldenlayout.js:3643)
```

**Comment by nmearl** [comment]
Are you selecting your data to be plotted?

![hint](https://user-images.githubusercontent.com/4141126/79361657-963e6880-7f13-11ea-9e84-c7b4bedc4ce1.gif)

**Comment by havok2063** [comment]
Ha.  Nope.  That would do it, thanks.  This has evolved quite a bit since last I loaded it.  Is there a way to programmatically tell the panes to load data?  Or a config option to tell which data to load by default?

As an aside, I had no idea that the app was ready and data had been successfully loaded.  It might be a good idea to add some kind of info bar that could display helpful prompts, e.g. "Data loaded.  Try selecting data from settings pane" or something.   When nothing happened my default trigger was error.

**Comment by nmearl** [comment]
> Is there a way to programmatically tell the panes to load data?

The API for this is being converged on with #70 and #83.

> Or a config option to tell which data to load by default?

This is more difficult since it requires knowing something about the data (i.e. custom loaders) in order to parse what data goes where (for example, how do we define what's the mask or uncertainty component?) We are exploring easy heuristics for more obvious cases.

> It might be a good idea to add some kind of info bar that could display helpful prompts, e.g. "Data loaded. Try selecting data from settings pane" or something. When nothing happened my default trigger was error.

Yep. The current state is not the envisioned way it'd operate, we've just been more focused on the underlying infrastructure at the expense of these niceties for now, but these things are being captured by work done by Jennifer Kotler.

**Comment by havok2063** [comment]
Ok, thanks! I'll take a look at the PRs to get up to speed.  Regarding default loading, I think for ASB's purposes we may need to figure out some solution to this.  Or at least use the API to load the data beforehand.  When our user navigates to the quicklook I think we'll want the data to be loaded in some form.  If there's some work that I can do to help with this, I'm happy to help.  Integrating jdaviz fully into the ASB workflow is our priority for Q3 and Q4.  Can I be folded back into your sprint planning and review sessions for this quarter?
