### ISSUE TITLE
[BUG] Specviz: Can't create or open spectrum without WCS coordinates

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdaviz#910]
Following the documentation yields suggests you can create your own spectrum: https://jdaviz.readthedocs.io/en/latest/specviz/import_data.html#loading-data-via-the-api

```python
import numpy as np
from astropy import units as u

from specutils import Spectrum1D

from jdaviz import Specviz

specviz = Specviz()

flux = np.random.randn(200) * u.Jy
wavelength = np.arange(5100, 5300) * u.AA
spec1d = Spectrum1D(spectral_axis=wavelength, flux=flux)
specviz.load_spectrum(spec1d)

specviz.show()
```

Furthermore, a similar error occurs when you extract a 1D spectrum from Cubeviz (or Specviz) and reopen in Specviz.

@pllim thinks it may be due to not having WCS coordinates.

I suggest this problem should be resolved by allowing spectra to be opened without WCS coordinates, updated documentation, or some combination of the two.

[🐱](https://jira.stsci.edu/browse/JDAT-1791)

**Comment by orifox** [comment]
Updated to 2.0

**Comment by orifox** [comment]
This works:flux=spec_agb.flux
wavelength=spec_agb.spectral_axis
spec1d = Spectrum1D(spectral_axis=wavelength, flux=flux)
specviz.load_spectrum(spec1d)
 
This does not:
specviz.load_spectrum(spec_agb)
 
Different WCS?

**Comment by orifox** [comment]
<img width="432" alt="Screen Shot 2021-09-24 at 2 05 47 PM" src="https://user-images.githubusercontent.com/5994975/134725480-4bacfb31-8652-4e17-8dbb-3e84bffa2844.png">

**Comment by pllim** [comment]
How does one get the `spec_agb` that would crash Specviz? Can you please provide code to reproduce this problem? Thanks!

**Comment by orifox** [comment]
spec_agb = cubeviz.app.get_data_from_viewer('spectrum-viewer', 'Subset 1') #AGB star only

**Comment by pllim** [comment]
`get_data_from_viewer` defers the translation to `glue-astronomy`, so if the WCS is incorrect, the fix is probably upstream over there.

**Comment by pllim** [comment]
I cannot reproduce the error anymore. The given example works fine. The returned bounds being misleading/wrong is being tracked separately in https://github.com/spacetelescope/jdaviz/issues/1892
