### ISSUE TITLE
toolbar icons do not display with mast embed

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#92]
When jdaviz is embedded into a separate website using https://github.com/mariobuikhuizen/voila-embed, the toolbar widget icons do not display correctly.  I'm serving from an environment where I have both voila-embed and jdaviz installed.  The toolbar displays correctly both in the notebook and when run as a desktop app with `jdaviz --layout ...`.  Are there some additional style files that need to be included in our frontend?   The functionality of the buttons still exist.  

<img width="1198" alt="Screen Shot 2020-04-21 at 11 19 13 AM" src="https://user-images.githubusercontent.com/1836302/79883498-fcb70100-83c1-11ea-9d0c-69cbf8a15d58.png">

**Comment by mariobuikhuizen** [comment]
jdaviz now uses https://cdn.materialdesignicons.com/4.4.95/ icons which were recently added to ipyvuetify.

In voila-embed these icons have to be added to the page:
``` html
<head>
    ...
    <link href='https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css' rel="stylesheet">
</head>
```

**Comment by havok2063** [comment]
Thanks @mariobuikhuizen.  That fixed it.

**Comment by havok2063** [comment]
Turns out that adding this css didn't completely fix the problem.  The `toy-brick-plus` icon on the far right of the toolbar does not display.  The button functionality is present.  All the other existing buttons in the toolbar display correctly.

**Comment by duytnguyendtn** [comment]
I want to say this has been fixed, since we've seen recent demos and everything has *looked* okay? @havok2063 Feel free to reopen this again if it's still relevant!

**Comment by havok2063** [comment]
Oddly enough we're just now noticing different icon issues we're having with the plugin tray icon and others not showing up.  An issue with `materialdesign` icons not loading in Chrome, but loading correctly in Firefox and Safari.  I think we can still safely close this issue as it seems related but unrelated.   If it's not something we can resolve on our side, we'll open up a new issue.
