### ISSUE TITLE
[BUG] Cubeviz: Cubeviz crashes when trying to delete subset

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdaviz#928]
Reporting on behalf of a user in a Hack Session, but they showed that when trying to define multiple apertures in the Cubeviz viewer, sometimes the window crashes and doesn’t let me define new apertures - I’m attaching screenshots below.
![Screenshot 2021-10-08 at 15 14 50](https://user-images.githubusercontent.com/5994975/136660579-7ae76973-b317-4839-b6c6-81bdf0b0206f.png)
![Screenshot 2021-10-08 at 15 13 41](https://user-images.githubusercontent.com/5994975/136660580-52c4d09b-3253-41e3-871b-d7f194f814c8.png)

[:cat:](https://jira.stsci.edu/browse/JDAT-1849)

**Comment by cbertemes** [comment]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/astroconda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/anaconda3/envs/astroconda/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    117         if type is None:
    118             try:
--> 119                 next(self.gen)
    120             except StopIteration:
    121                 return False

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1212                 for changes in cache.values():
   1213                     for change in changes:
-> 1214                         self.notify_change(change)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/glue_jupyter/widgets/subset_select_vuetify.py in _sync_selected_from_ui(self, change)
     85     def _sync_selected_from_ui(self, change):
     86         self.edit_subset_mode.edit_subset = [self.data_collection.subset_groups[index] for index in
---> 87                                              change['new']]
     88 
     89     @traitlets.observe('multiple')

~/anaconda3/envs/astroconda/lib/python3.7/site-packages/glue_jupyter/widgets/subset_select_vuetify.py in <listcomp>(.0)
     84     @traitlets.observe('selected')
     85     def _sync_selected_from_ui(self, change):
---> 86         self.edit_subset_mode.edit_subset = [self.data_collection.subset_groups[index] for index in
     87                                              change['new']]
     88 

IndexError: tuple index out of range

**Comment by pllim** [comment]
It is crashing here with the following values... Still trying to wrap my head around this one.

https://github.com/glue-viz/glue-jupyter/blob/d0311863b6e72d07428415fc41ee6a6b243c3326/glue_jupyter/widgets/subset_select_vuetify.py#L84-L87

```python
index = 7
change["new"] = [7]
len(self.data_collection.subset_groups) = 7
```

Why is there an off-by-one error but only for specific use cases?
