### ISSUE TITLE
[BUG] Cubeviz: Cannot Open Cubes Produced in JWST ETC

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdaviz#935]
Users get the following errors when reading this file:
https://stsci.box.com/s/d2viaaxns9rr36xpct4kig9q7idcot45

<img width="1043" alt="Screen Shot 2021-10-14 at 6 50 37 AM" src="https://user-images.githubusercontent.com/5994975/137303779-d9512136-2a32-4bc4-9998-74f568a944b8.png">

**Comment by pllim** [comment]
@orifox , is this using `main` branch or Jesse's work at #547 ? If the former, I think this behavior might change once we get rid of spectral-cube.

**Comment by pllim** [comment]
ETC claimed "well, DS9 can open it" so I looked into the error myself and concluded that they are populating the header with the wrong value for CTYPEn. Ref: https://github.com/astropy/astropy/blob/01dac1a0e2f47fc3e0e68743af5a4cdffb15cba2/astropy/wcs/wcsapi/fitswcs.py#L114

Here is how I fixed the data to get it to load (Ori had the right idea above but his fix was more than what was needed:

```python
from astropy.io import fits

pf = fits.open('miri_etc_cube_galaxy_fixed.fits')

# Cubeviz also look for certain extension names.
pf[1].name = 'SCI'
pf[2].name = 'ERR'
pf[3].name = 'DQ'

# Not sure why primary header extension has data, might as well clean it up to save storage space.
pf[0].data = None

# The important fix to WCS.
pf[1].header['CTYPE3'] = 'WAVE'
pf[2].header['CTYPE3'] = 'WAVE'
pf[3].header['CTYPE3'] = 'WAVE'

pf.writeto('miri_etc_cube_galaxy_fixed.fits', overwrite=True)

pf.close()
```

Now, we can load the fixed version of the file:

```python
from jdaviz import Cubeviz

viz = Cubeviz()
viz.load_data('miri_etc_cube_galaxy_fixed.fits')
```

![Screenshot 2021-12-20 141921](https://user-images.githubusercontent.com/2090236/146820866-e83a8a4e-c52d-4378-82b8-d9386a674005.jpg)

Conclusion: It is the data that is the problem, there is nothing for us to fix at Jdaviz.
