### ISSUE TITLE
[BUG] UI: app-level toolbar does not render correctly in Lab

### ISSUE THREAD

**Issue by rosteen** [spacetelescope/jdaviz#946]
**Describe the bug**
In Jupyter Lab, the app-level toolbar tools do not render properly, either in-line or using "new view for output". See the screenshot below. In Jupyter Notebook everything looks fine. @kecnry I don't know the timing on when this appeared, so I don't know if it's related to your recent changes to add vertical dividers. 

**To Reproduce**
1. Open one of the sample notebooks in Jupyter Lab and run the app. 

**Screenshots**

![Screen Shot 2021-10-21 at 11 38 27 AM](https://user-images.githubusercontent.com/39831871/138311342-857fc962-b26e-49b8-963b-51b02cd003c8.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome 88, safari 22]
 - Jupyter: [run "jupyter --version"]

**Package versions (please complete the following information):**

macOS-10.15.7-x86_64-i386-64bit
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ]
Numpy 1.20.3
astropy 4.3.1
specutils 1.4.2.dev31+g1d300f1a
spectral-cube 0.5.0
pyyaml 5.4.1
click 8.0.1
asteval 0.9.23
idna 2.10
traitlets 5.0.5
bqplot 0.12.30
bqplot-image-gl 1.4.3
glue-core 1.2.2
glue-jupyter 0.10.1
glue-astronomy 0.3.2
echo 0.5
ipyvue 1.5.0
ipyvuetify 1.7.0
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.2.10
vispy 0.6.6
Jdaviz 2.0.1.dev77+g2695dca6.d20211021

**Comment by pllim** [comment]
Just to make sure, did you do a clean install of the dev version?

**Comment by rosteen** [comment]
I just installed the latest dev version and still see this. I wonder if I need to update a lab extension or something...
