### ISSUE TITLE
vuetify sidebar does not properly toggle in mast embed

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#95]
The vuetify sidebar does not collapse as expected.  The icons remain outwards no matter the state the sidebar is in.  

In State
<img width="243" alt="Screen Shot 2020-04-21 at 1 18 34 PM" src="https://user-images.githubusercontent.com/1836302/79894020-d8afeb80-83d2-11ea-97f0-a8e4bdfc407b.png">

Out State
<img width="271" alt="Screen Shot 2020-04-21 at 1 18 44 PM" src="https://user-images.githubusercontent.com/1836302/79894054-e6fe0780-83d2-11ea-8dae-c8fb16cefae8.png">

**Comment by nmearl** [comment]
Are they still buttons in the sense that you can click them?

**Comment by havok2063** [comment]
Yes the button functionality still works.

**Comment by duytnguyendtn** [comment]
@havok2063 This is probably outdated?

**Comment by havok2063** [comment]
Yep I think this can safely be closed.
