### ISSUE TITLE
Re-consider "each viewer has its own data" paradigm in light of user feedback

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#97]
Following a recent hack hour, there's been some concern raised that the current jdaviz paradigm that the each viewer has its own data "drawer" presents usability concerns. We should discuss if we want to rethink this paradigm, particularly given a shift to plugins-as-sidebar.

cc @nmearl

**Comment by eteq** [comment]
Some ideas to consider:

* Status quo, but depend on JDAT-378 or similar to address the usability concern.  I.e., if the viewers initially usually get populated with the right data, the data drawer is only an "advanced" option anyway.
* Switch to something more like Qt glue, where the data are "drag-and-dropped" into viewers.  I am strongly opposed to this paradigm for reasons I can give if desired (but am always open to being convinced otherwise...)
* Have a panel that maps data onto viewers somehow, but have the panel not be integrated with the viewer itself.  Simplest version might just be a table with two columns, one the viewer and the other a drop-down that looks just like the existing drawer

**Comment by rosteen** [comment]
@eteq I imagine this was considered, since it's been a year plus and we've had a consistent data paradigm. Closing, but feel free to correct me and reopen if there's more discussion needed.
