### ISSUE TITLE
change default data load/display for x1d data

### ISSUE THREAD

**Issue by havok2063** [spacetelescope/jdaviz#99]
For JWST x1d data, the first HDU extension is a binary table 
```
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     353   ()      
  1  EXTRACT1D     1 BinTableHDU     50   1331R x 9C   [D, D, D, D, D, J, D, D, D]   
  2  ASDF          1 BinTableHDU     11   1R x 1C   [33445B]  
``` 
with WAVELENGTH as the first column and FLUX/ERROR as the next two.  When loading this data, the current default is to plot is the 1st column.  This results in a wavelength vs wavelength plot and the user needs to change the Layer Attribute to get to FLUX.  Instead, the default should be to display the FLUX column and (probably also) overplot the ERROR.

**Comment by duytnguyendtn** [comment]
@havok2063 Is this still an issue?

**Comment by havok2063** [comment]
@duytnguyendtn No this is no longer an issue.  I think this was resolved once the parser logic got implemented.
