### ISSUE TITLE
Bump glue-astronomy minversion to v0.3.3 or later

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#991]
@astrofrog needs to do a new `glue-astronomy` release so we can bump the minversion here:

https://github.com/spacetelescope/jdaviz/blob/ef350a4ca1248ff692ba9cef5816d646f3cc917d/setup.cfg#L35

We need this to pick up the following fixes:

* glue-viz/glue-astronomy#56 for #967
* glue-viz/glue-astronomy#58

**Comment by astrofrog** [comment]
I think this can be closed as we now require glue-astronomy v0.7
